### PR TITLE
Checkbox to disable the pop up dialog box when creating share link with `Ctrl+s`

### PR DESCRIPTION
**Pull request by dead-tech**
I think this should do it for #3265.

I also took a look at #3289 as @mattgodbolt suggested me, this is what I had done before reading his comment, though if you want me to do something about that draft I would be happy to help.

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi! Thanks for taking the time to implement this!

There's a PR that heavily modifies static/settings.js (#3297) so it might be better if we hold this merge until that lands.

I'll let you know once it does so that you can rebase against the new changes :)

**Comment by dead-tech** [comment]
@RubenRBS Very good, thank you also for your time!

**Comment by RubenRBS** [comment]
Feel free to try now :)

**Comment by dead-tech** [comment]
I actually think I might have messed up something with git. Please let me know i will just recreate the PR.

**Comment by RubenRBS** [comment]
It might have been my bad, but it looks like it's doing something weird yeah. Sorry for the troubles, but yeah it would be great if you could recreate it :)

**Comment by dead-tech** [comment]
I will do it tomorrow. Sorry for the inconvenience and thanks for your patience!

**Pull request closed without merging**
