### PR TITLE
Rust 1.69.0

### PR DESCRIPTION
**Pull request by ojeda**
Infra: https://github.com/compiler-explorer/infra/pull/994.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks Miguel!

**Comment by partouf** [comment]
this is now live

**Comment by ojeda** [comment]
Thanks Matt/Patrick!

**Comment by githubsands** [comment]
Screen Shot 2023-05-10 at 5 41 56 PM

Having issues seeing updated rust compiler - any resolve here?

**Comment by partouf** [comment]
@githubsands  The error message seems clear to me? Are you expecting it to work in Edition 2015? (the default if you dont pass any --edition)

**Pull request merged**
