### PR TITLE
zig: add 0.7.0 and 0.7.1 versions

### PR DESCRIPTION
**Pull request by ifreund**

### CODE REVIEW

**Comment by partouf** [comment]
Can you add the versions to https://github.com/compiler-explorer/infra/blob/master/bin/yaml/zig.yaml as well?

**Comment by ifreund** [comment]
> Can you add the versions to https://github.com/compiler-explorer/infra/blob/master/bin/yaml/zig.yaml as well?

Thanks for the tip, done: https://github.com/compiler-explorer/infra/pull/453.

**Comment by partouf** [comment]
Thanks!

**Comment by partouf** [comment]
This is now live! Thanks again!

**Pull request merged**
