### PR TITLE
LLVM 11

### PR DESCRIPTION
**Pull request by ojeda**
Note: untested.
See: https://github.com/compiler-explorer/infra/pull/419

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Fab! Building llvm 11 now :)

**Comment by mattgodbolt** [comment]
Looks good: pushing to prod now.

We probably need another PR to add the llvm library to the libraries dropdown (if you fancy taking a look; else I'll raise an issue)

**Comment by ojeda** [comment]
Ah, yes, I always forget. I'll take a look.

**Comment by mattgodbolt** [comment]
Do you have a twitter account to thank when we tweet out that clang 11 is out?

**Comment by ojeda** [comment]
I have a completely unused one (Miguel__Ojeda), but don't worry about credit, these contributions are nothing!

**Comment by mattgodbolt** [comment]
Thanks! I named you anyway (thanks!!!) but couldn't find the twitter account you mentioned. This is now live ! Yay :)

**Pull request merged**
