### PR TITLE
Use non-private ways of context menu

### PR DESCRIPTION
**Pull request by mattgodbolt**
and fix up some things where previously we had odd null checks that somehow became .get() (which means it worked exactly once)

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Also simplifies some stuff

**Comment by mattgodbolt** [comment]
@RubenRBS or @partouf would love a post-hoc review, but gonna merge and push to fix #4182

**Comment by partouf** [comment]
:+1:

**Comment by RubenRBS** [comment]
👍 too, looks way better now

**Pull request merged**
