### PR TITLE
add some static liblinks for abseil

### LINKED ISSUE #2313: [REQUEST] please support absl::StrFormat, which requires linking an additional library
**Is your feature request related to a problem? Please describe.**

From the Abseil library, I wish to use absl::StrFormat for printing diagnostic strings in the Godbolt executor (for example: https://godbolt.org/z/Tb47oW).

Unfortunately, this doesn't work because str_format is one of the Abseil optional libraries. Godbolt has the header file, but using any of the non-default library methods (eg, absl::StrFormat) results in an "undefined reference" linker error.

See https://github.com/abseil/abseil-cpp/issues/145 for an explanation of how str_format is a separate library that must be linked in. Godbolt currently only has a single monolithing "Abseil" library option, and that only includes the Abseil components in the default library.

I use this absl::StrFormat ubiquitously in my professional work, and it's annoying to have to back-translate things to printf to get them working in Godbolt. Sometimes, I paste small snippets of (generic / non-sensitive) code into Godbolt for rapid exploration / prototyping.

It would be convenient to be able to use ALL of the Abseil libraries, and not just the ones that are compiled in by default.

**Describe the solution you'd like**

One simple solution would be to link in substantially ALL Abseil components whenever the user adds the "Abseil" library. That seems simpler than exposing more configuration state for selecting the individual sub-components of Abseil.

**Additional context**

FWIW, I happen to work at the company that develops Abseil. My work focuses on the retrieval systems known externally as [ScaNN](https://ai.googleblog.com/2020/07/announcing-scann-efficient-vector.html), which make heavy use of SIMD intrinsics. By my oblique reference to my employer, you can conclude that I'm NOT representing them in an official capacity.

As a show of my appreciation for all the hard work you've put into making Godbolt such a fantastic free tool, I just sent you a donation via PayPal (significantly more than a coffee, but nowhere near enough to qualify as a quid-pro-quo for implementing a feature request!). What a fantastic tool! Thanks for your efforts!

### PR DESCRIPTION
**Pull request by partouf**
Fixes #2313 - but not much else I'm guessing.

Turns out I couldn't autodownload binaries and let the user handle the linking, because of the command line order of things when it comes to static libraries.

So I had to add some in the properties in order.

However, there are about 60 libraries, and these are just a few of them.
Would need to find some examples to get everything linked up.

### CODE REVIEW

**Comment by partouf** [comment]
The library provides pkgconfig files, maybe I call pkgconfig with all of the libraries and maybe it will put everything in order for me?

**Review by mattgodbolt — APPROVED** [review]
Seems like a super pragmatic solution. Thanks @partouf

**Comment by partouf** [comment]
Alas,
I tried this:
```
partouf@ceub20:/opt/compiler-explorer/staging/g101_a3d436fd9d8a5a957e194e5f5aaf1fa2ec404857491d443d946a656d03254c56/lib/pkgconfig$ PKG_CONFIG_PATH=/opt/compiler-explorer/staging/g101_a3d436fd9d8a5a957e194e5f5aaf1fa2ec404857491d443d946a656d03254c56/lib/pkgconfig pkg-config --libs-only-l *
-labsl_bad_any_cast_impl -labsl_bad_optional_access -labsl_bad_variant_access -lrt -labsl_base -labsl_city -labsl_civil_time -labsl_cord -labsl_debugging_internal -labsl_demangle_internal -labsl_examine_stack -labsl_exponential_biased -labsl_failure_signal_handler -labsl_flags_commandlineflag_internal -labsl_flags_commandlineflag -labsl_flags_config -labsl_flags_internal -labsl_flags_marshalling -labsl_flags_parse -labsl_flags -labsl_flags_private_handle_accessor -labsl_flags_program_name -labsl_flags_reflection -labsl_flags_usage_internal -labsl_flags_usage -labsl_graphcycles_internal -labsl_hash -labsl_hashtablez_sampler -labsl_int128 -labsl_leak_check_disable -labsl_leak_check -labsl_log_severity -labsl_malloc_internal -labsl_periodic_sampler -labsl_random_distributions -labsl_random_internal_distribution_test_util -labsl_random_internal_platform -labsl_random_internal_pool_urbg -labsl_random_internal_randen_hwaes_impl -labsl_random_internal_randen_hwaes -labsl_random_internal_randen -labsl_random_internal_randen_slow -labsl_random_internal_seed_material -labsl_random_seed_gen_exception -labsl_random_seed_sequences -labsl_raw_hash_set -labsl_raw_logging_internal -labsl_scoped_set_env -labsl_spinlock_wait -labsl_stacktrace -labsl_statusor -labsl_status -labsl_strerror -labsl_str_format_internal -labsl_strings_internal -labsl_strings -labsl_symbolize -labsl_synchronization -labsl_throw_delegate -labsl_time -labsl_time_zone
```

But this isn't the correct order.
Seems maybe this ignores dependency order? or maybe there are too many .pc files to sort for the pkg-config this way?

**Comment by partouf** [comment]
AHA
I had to pass --static to pkg-config to get the dependency order correct!

**Comment by partouf** [comment]
This is now live

**Pull request merged**
