### PR TITLE
Stop duplicating `hasXXoutput` + `XXoutput`

### PR DESCRIPTION
**Pull request by OfekShilon**
When you need to check if `XXoutput` exists, check it directly.
+some TSification in CompilationResult

This follows @RubenRBS 's comment on #6471.

I know this is sensitive and still want to bash it a while longer - but if anyone thinks this is the wrong way to go, I'd appreciate early feedback.

### CODE REVIEW

**Review by RubenRBS — COMMENTED** [review]
We need to remember that these fields are part of the public api. Someone might be using them for their intended pourpose, and I think we would break them if we removed those flags 

Not sure how to best proceed 🤔

**Comment by partouf** [comment]
I think these fields are generally not used by external parties, so I don't mind breaking the API for this.

**Review by mattgodbolt — COMMENTED** [review]
Looks good to me: I'm in favour of this simplification; thank you!

**Comment by OfekShilon** [comment]
Thanks @RubenRBS @partouf @mattgodbolt . I still want to install haskell and do some smoke-testing. After that I'll merge and hope the fallout is benign..

**Pull request merged**
