### PR TITLE
Add libSegFault support as runtime tool

### LINKED ISSUE #6830: [REQUEST]: Add builtin/optional segfault support for c/c++ (linux)
### Is your feature request related to a problem? Please describe

When SIGSEGV's happen, it's not as easy to figure out what's going on without a debugger. It might be useful to offer help to users with these kind of problems.

### Describe the solution you'd like

A (useful) stacktrace of some kind when a segfault happens

### Describe alternatives you've considered

Handling segfaults is not easy to do for users within their own program, it usually seems to need external handling:
* https://github.com/stass/libsegfault + libunwind
* https://github.com/jeremy-rifkin/cpptrace/blob/v0.5.0/docs/signal-safe-tracing.md
* Build something into nsjail?

libsegfault might be the easiest to test around with as it's a LD_PRELOAD and requires nothing else (I think)

### Additional context

Not applicable

### PR DESCRIPTION
**Pull request by partouf**
Fixes #6830 together with https://github.com/compiler-explorer/glibc-tools

Todo:
* [x] Property in `compiler-explorer.amazon.properties` setting `libSegFaultPath=/opt/compiler-explorer/glibc-tools...`
* [x] Workflow to build `libSegFault` (should also later support aarch64 build)
* [x] Installer for libSegFault
* [x] Maybe make the other dumps optional, otherwise it's a bit wall-of-text-y

### CODE REVIEW

**Comment by partouf** [comment]
now live @jeremy-rifkin but it's not working as great as can be, I think
For example: works great with clang, not so much with gcc, also not with older versions

**Comment by partouf** [comment]
Just realized it worked locally and on GH, so maybe its libunwind not being found or something similar

**Comment by jeremy-rifkin** [comment]
Hmm, if libunwind isn't found then the stack trace would be empty. I'm wondering if there might be something going on with the sandbox that interferes with the fork+exec and access of  the original binary.

**Comment by partouf** [comment]
> Hmm, if libunwind isn't found then the stack trace would be empty. I'm wondering if there might be something going on with the sandbox that interferes with the fork+exec and access of the original binary.

But then why would it work under C++ Clang and Rust?
Because that's the difference, those have access to libunwind by default because it's in their library paths.

It's not available for everyone as it's not installed on the image

**Comment by partouf** [comment]
I can test this on the staging instance, let me try to install it on there

**Comment by partouf** [comment]
Ok this is not the problem, it is available

**Comment by jeremy-rifkin** [comment]
If libunwind were somehow not there I'd expect the trace to be empty. I guess the fact a trace is printed at all means the fork+exec worked, so it must be something in trace resolution. I'll see if I can repro.

**Comment by partouf** [comment]
> If libunwind were somehow not there I'd expect the trace to be empty. I guess the fact a trace is printed at all means the fork+exec worked, so it must be something in trace resolution. I'll see if I can repro.

yes, I can repro with gcc under nsjail as well

**Comment by partouf** [comment]
according to the strace it is able to find and open output.s

**Pull request merged**
