### PR TITLE
Allow to listen on unix socket instead of port

### PR DESCRIPTION
**Pull request by melven**
Dear compiler-explorer team

I tried to run compiler explorer on a linux machine and listen on unix socket instead of a port.
Works basically fine but I needed the changes below to be able to configure it properly.

**I don't know if this messes with some systemd integration (`systemdSocket` function call in `startListening`)**

Another problem occurs during logging (I assume) in production mode (works fine in dev-mode):
```
error: Internal server error: Cannot read property 'includes' of undefined {"domainThrown":true,"stack":"TypeError: Cannot read property 'includes' of undefined\n    at Proxy.anonymizeIp (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/lib/utils.js:161:12)\n    at Function.gdpr_ip (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/app.js:632:42)\n    at eval (eval at compile (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/morgan/index.js:411:10), <anonymous>:5:23)\n    at Array.logRequest (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/morgan/index.js:122:18)\n    at listener (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/on-finished/index.js:169:15)\n    at onFinish (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/on-finished/index.js:100:5)\n    at callback (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/ee-first/index.js:55:10)\n    at ServerResponse.onevent (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/ee-first/index.js:93:5)\n    at ServerResponse.emit (events.js:327:22)\n    at ServerResponse.EventEmitter.emit (domain.js:529:15)"}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at ServerResponse.header (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/express/lib/response.js:599:15)
    at ServerResponse.send (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/express/lib/response.js:145:14)
    at done (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/express/lib/response.js:1008:10)
    at Object.exports.renderFile (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/pug/lib/index.js:421:12)
    at View.exports.__express [as engine] (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/pug/lib/index.js:464:11)
    at View.render (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/zoel_ml/test/compiler-explorer-script/compiler-explorer/node_modules/express/lib/application.js:592:3)
```

Any thoughts on this?

### CODE REVIEW

**Review by mattgodbolt — COMMENTED** [review]
Looks pretty sensible to me. Will hold off approving though as you've indicated this is work in progress.

**Comment by mattgodbolt** [comment]
Thanks!
* I don't think this has any issues with the systemd stuff
* That production error you're seeing looks like a genuine issue though; how are you running the app?

**Comment by melven** [comment]
I run the server on Ubuntu 18.04.5 with:
```
SOCKET_FILE="${HOME}/compiler-explorer.sock"
(cd compiler-explorer &&  make dev NODE_DIR=../node-v12.20.1-linux-x64/ EXTRA_ARGS="--port=${SOCKET_FILE}")
```
Then, I make an ssh-tunnel from a Windows system:
```
ssh -L localhost:10240:/home/username/compiler-explorer.sock username@server
```
and open localhost:10240 in firefox.

With `dev` mode it works fine without the error. If I just listen on a port and use port-forwarding, it also works fine...<br>
I want to use a socket because the compiler-explorer server runs on a cluster as a normal user account and so it should only be accessible to the person that started it...<br>
I also tried a newer node.js version (14.15.4) but no change.

In the browser, everything seems to work fine but each change/click/etc generates a new error message like the one above.

In `dev` mode with the socket, everything looks fine. Output:
```
...
info: Fetching possible arguments from storage
info: Not configuring sentry
info: OPTIONS HASH: 1b0a611a400740730d0c54c887f3c629c24ed3b574c5da9d7857e7c7c625f7a8
info:   using webpack dev middleware
info:   Listening on socket: ///home/zoel_ml/compiler-explorer.sock/
info:   Startup duration: 4598ms
info: =======================================
info: GET / 200 1073.847 ms - -
info: wait until bundle finished: /static/main.css
info: wait until bundle finished: /static/vendor.css
info: wait until bundle finished: /static/runtime.js
info: wait until bundle finished: /static/vendor.js
info: wait until bundle finished: /static/main.js
info: GET /client-options.js?hash=1b0a611a400740730d0c54c887f3c629c24ed3b574c5da9d7857e7c7c625f7a8 200 1.032 ms - -
info: Compiled successfully.
info: GET /source/builtin/list 304 1.207 ms - -
info: POST /api/compiler/gdefault/compile 200 90.181 ms - -
info: POST /api/compiler/gdefault/compile 200 138.596 ms - -
info: POST /api/compiler/gdefault/compile 200 79.923 ms - -
info: POST /api/compiler/gdefault/compile 200 139.531 ms - -
```

**Comment by mattgodbolt** [comment]
So, to confirm, what command do you use when you see the issue? The exact same command but without the `dev` in `make dev` ?

**Comment by mattgodbolt** [comment]
AH! I see it now! :) `Proxy.anonymizeIp` is assuming it's a TCP connection coming in!!

**Comment by mattgodbolt** [comment]
@melven If you change line 620 of app.js from:

```js
    morgan.token('gdpr_ip', req => utils.anonymizeIp(req.ip));
```

to

```js
    morgan.token('gdpr_ip', req => req.ip ? utils.anonymizeIp(req.ip) : '');
```
then I think that will fix the issue!

**Comment by mattgodbolt** [comment]
(or something like that: the request no longer has an IP associated with it if it came over UNIX domain socket)

**Comment by melven** [comment]
Works fine now with:
```
    morgan.token('gdpr_ip', req => req.ip ? utils.anonymizeIp(req.ip) : '');
```

Thanks!

**Review by mattgodbolt — APPROVED** [review]
Looks good; thanks!

**Pull request merged**
