### PR TITLE
Use our own fork of approvals to fix a bunch of security warnings.

### PR DESCRIPTION
**Pull request by mattgodbolt**

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Ah Windows.

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t ssh://git@github.com/approvals/Approvals.NodeJS.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

not sure where it get the ssh:// thing from as I refer to it only as https:// in the package.json - any ideas anyone?

**Comment by mattgodbolt** [comment]
maybe it's something in the approvals itself...there's a dodgy `npm.cmd` thing...sec

**Comment by mattgodbolt** [comment]
Seems not - it's weird but not bonkers

**Comment by partouf** [comment]
node should definitely be updated to v16, theres a bunch of other warnings and errors that shouldnt be there either,
and if that doesn't help, perhaps add github host fingerprint to known_hosts?

**Comment by mattgodbolt** [comment]
You genius! thanks partouf!

**Pull request merged**
