### PR TITLE
[CI] Fix labeler configuration vor labler@v5

### PR DESCRIPTION
**Pull request by marcauberer**
This pr fixes the failing labeler action labeling pull requests, which was probably broken by renovate when upgrading the action from v4 to v5.
I wasn't able to test the configuration, but let's hope it works.

### CODE REVIEW

**Comment by dkm** [comment]
Looks nice, and it won't be worse than what we have now :D Thanks!

**Comment by dkm** [comment]
Note, seems to be "not enough":
https://github.com/compiler-explorer/compiler-explorer/pull/6105#issuecomment-1937091053

**Comment by marcauberer** [comment]
Yes. Let me see if I can fix it ...

**Comment by marcauberer** [comment]
@dkm See #6117

**Pull request merged**
