### PR TITLE
Add Crystal 1.10.1

### PR DESCRIPTION
**Pull request by HertzDevil**

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
This is now live

**Comment by partouf** [comment]
Crystal doesn't generate any asm by default anymore since 1.9.2, someone might want to look into that

**Comment by HertzDevil** [comment]
It now generates the assembly and LLVM IR files in the same directory as the output executable, rather than the current working directory

**Pull request merged**
