### PR TITLE
add taoJSON

### PR DESCRIPTION
**Pull request by toughengineer**
taoJSON is in beta, so only the trunk version at this time.

Corresponding infra PR:  
https://github.com/compiler-explorer/infra/pull/547

### CODE REVIEW

**Review by RubenRBS — CHANGES_REQUESTED** [review]
Can you order this alphabetically in both places please? :)

**Comment by toughengineer** [comment]
@RubenRBS, sure, you should state this requirement [here](/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md) though.

**Comment by toughengineer** [comment]
@RubenRBS, unable to place the item in infra in its alphabetic place 'cause `nightly` items are not in alphabetic order.

**Comment by RubenRBS** [comment]
oops, sorry! I did not explain myself correctly! I meant both in the libs list (Line 1049) and the other one you already did

**Review by RubenRBS — APPROVED** [review]

**Comment by mattgodbolt** [comment]
This is now live.

**Pull request merged**
