### PR TITLE
Highlight pattern matching contextual keywords.

### PR DESCRIPTION
**Pull request by mpark**
Contextual keywords being introduced by P2688. Arguably this approach is being too liberal though since it's still only a proposal, so we may want it to be more constrained.

### CODE REVIEW

**Comment by partouf** [comment]
I'm a little hesitant about this change. We have not seen or merged any proposed feature keywords before, and I'm not sure we should start doing so.

**Comment by mpark** [comment]
I get that. Ideally the change would only apply for the pattern matching compiler build, but my understanding is that there's no compiler build specific way to do this at the moment. I think I see some language variants like cxx open CL or and stuff like that. I wonder if that approach could be taken?

**Comment by partouf** [comment]
> I get that. Ideally the change would only apply for the pattern matching compiler build, but my understanding is that there's no compiler build specific way to do this at the moment. I think I see some language variants like cxx open CL or and stuff like that. I wonder if that approach could be taken?

It would be an approach, but we do not have a way to change this on the fly when changing compiler, only when changing language, so currently this is not possible.

**Comment by jeremy-rifkin** [comment]
I have a little bit of FUD adding these before P2688 is accepted. I agree `let` is a lot less concerning than `match` though.

**Comment by mattgodbolt** [comment]
Sorry to cause issue here: @mpark and I discussed on Discord and I said it'd probably be ok...without context and/or special enable/disable then maybe this is a bridge too far.

**Comment by mattgodbolt** [comment]
Adding it as a new language would work - but does inhibit discoverability a bit.

**Comment by mattgodbolt** [comment]
Hi @mpark - sorry for leading you astray on this: I'm going to close this for now as I thought about it some more and I think `match` is too generic and obvious a variable name to highlight without some way to detect this. See #7121

**Comment by mpark** [comment]
Fair enough. No problem!

**Pull request closed without merging**
