### PR TITLE
Refactor and adding new dotnet compilers

### PR DESCRIPTION
**Pull request by hez2010**
Depends on https://github.com/compiler-explorer/infra/pull/1312.

I'm considering to unify all old compiler versions per dotnet minor version as patch upgrade in dotnet doesn't change the codegen. New patch versions come with quality updates like bug and security fixes, we only need the latest version per minor dotnet version instead. Here a version is consisting of `major.minor.patch`, such as `7.0.3` and `8.0.5`.

i.e.
- `dotnet6030csharp:dotnet6018csharp:dotnet6014csharp:dotnet6011csharp` -> `dotnet60csharp`, and rename it to `.NET 6.0`, as `6.0.30`, `6.0.18`, `6.0.14` and `6.0.11` are all `6.0`
- `dotnet6030fsharp:dotnet6018fsharp:dotnet6014fsharp:dotnet6011fsharp` -> `dotnet60fsharp`, and rename it to `.NET 6.0`, as `6.0.30`, `6.0.18`, `6.0.14` and `6.0.11` are all `6.0`
- `dotnet6030vb:dotnet6018vb:dotnet6014vb:dotnet6011vb` -> `dotnet60vb`, and rename it to `.NET 6.0`, as `6.0.30`, `6.0.18`, `6.0.14` and `6.0.11` are all `6.0`
- `dotnet7019csharp:dotnet707csharp:dotnet703csharp:dotnet701csharp` -> `dotnet70csharp`, and rename it to `.NET 7.0`, as `7.0.19`, `7.0.7`, `7.0.3` and `7.0.1` are all `7.0`
- `dotnet7019fsharp:dotnet707fsharp:dotnet703fsharp:dotnet701fsharp` -> `dotnet70fsharp`, and rename it to `.NET 7.0`, as `7.0.19`, `7.0.7`, `7.0.3` and `7.0.1` are all `7.0`
- `dotnet7019vb:dotnet707vb:dotnet703vb:dotnet701vb` -> `dotnet70vb`, and rename it to `.NET 7.0`, as `7.0.19`, `7.0.7`, `7.0.3` and `7.0.1` are all `7.0`

I'm keeping the minor version (ie. `.0`) in the name as there may be updates like `.NET Core 3.1` to `.NET Core 3.0` which does change the codegen.

The compiler structure now is:

```
group: dotnetcoreclr
.NET (main)
.NET 8
.NET 7
group: dotnetcrossgen2
.NET (main)
.NET 8
.NET 7
.NET 6
group: dotnetlegacy
existing compilers for backward compact
```

### CODE REVIEW

**Comment by hez2010** [comment]
I have some plans to refactor the dotnet compilers a bit so that it will look like below:

```
group: coreclr
.NET (main)
.NET 8
.NET 7
.NET 6
group: crossgen2
.NET (main)
.NET 8
.NET 7
.NET 6
group: legacy
existing compilers for back-compact
```

Do you think should I do it in this PR?

**Comment by mattgodbolt** [comment]
Feel free to do it in this PR. Let me know

**Comment by hez2010** [comment]
Done. PTAL @mattgodbolt.

**Comment by mattgodbolt** [comment]
Thank you :)

**Pull request merged**
