### PR TITLE
Make Clang parser logic shorter

### PR DESCRIPTION
**Pull request by juanarbol**

### CODE REVIEW

**Review by partouf — APPROVED** [review]

**Comment by partouf** [comment]
Not exactly the same, but I don't think it will give issues. Lgtm

**Review by matsjla — APPROVED** [review]
The extra space shouldn't matter, LGTM

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
Looks like this broke our formatting rules - @juanarbol do you have the pre-commit hooks installed (they should be autoinstalled but who knows).

**Comment by juanarbol** [comment]
> Looks like this broke our formatting rules - @juanarbol do you have the pre-commit hooks installed (they should be autoinstalled but who knows).

That's weird, husky passes locally , and a I double checked with make check task

**Comment by partouf** [comment]
now live

**Pull request merged**
