### PR TITLE
Add Boost 1.86.0

### PR DESCRIPTION
**Pull request by pdimov**

### CODE REVIEW

**Comment by partouf** [comment]
Will try to deploy this tonight if I remember

**Comment by partouf** [comment]
this is now live

**Comment by pdimov** [comment]
Thanks!

Seems to work for clang 8 to 18 inclusive, but not for 7 and below, or 19; tiered deployment?

**Comment by partouf** [comment]
this is a list of current supported compilers https://conan.compiler-explorer.com/libraries_cpp.html#boost_bin/1.86.0
clang 7 and below are a part of that, so you'll have to provide me with more details of whats not working
(but also yes, tiered, more compilers will be available next week)

**Comment by pdimov** [comment]
Looks like I've been trying e.g. 7.1.0 and 4.0.1, whereas the working ones are 7.0.0 and 4.0.0.

**Comment by pdimov** [comment]
Another thing I notice is that Boost headers don't work with -m32 at all, even for 1.85.0: https://godbolt.org/z/87Taq1PTe

That's probably because Boost isn't being built for -m32, but it's a regression compared to 1.84 and below.

**Comment by partouf** [comment]
We do build for -m32, but unfortunately it seems we need to do more. It seems some of the boost modules ignore -m32 and we probably need to add some extra variables. Will investigate later.
For reference the error log for gcc 14.2.0 with -m32 https://conan.compiler-explorer.com/getlogging/20240917024443

**Comment by pdimov** [comment]
From the log it looks like Context and Container fail, first one because -m32 isn't passed to the assembler, second one because -m32 isn't passed to the C compiler. Maybe CMAKE_CXX_FLAGS are being set, but CMAKE_ASM_FLAGS and CMAKE_C_FLAGS are not?

**Comment by pdimov** [comment]
Would it be possible to keep the header-only Boost present for lower priority configurations such as Clang/P2996, EDG/reflection, or GCC/s390x? Right now only 1.84 works there, 1.85 and 1.86 do not, and that's inconvenient.

**Pull request merged**
