### PR TITLE
Changes for NVIDIA HPC SDK 24.1 #2

### PR DESCRIPTION
**Pull request by jmuddnv**
Fixed issues in first PR
Add HPC SDK 24.1 to  etc/config/c++.amazon.properties

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
LGTM! thanks

**Comment by jmuddnv** [comment]
Both the PRs for compiler-explorer and infra were accepted and integrated into the sources.  Yet I do not see it on godbolt.org (image below).  Is there something more I need to do on my side (as the NVIDA person pushing the new HPC SDK releases to CE)?

***@***.***

**Comment by partouf** [comment]
We have not pushed the merged PR's to production yet, when we have, we will post here that its live

**Comment by jmuddnv** [comment]
Thanks.  I wasn’t sure of the post PR process so your explanation helps a lot.

**Comment by mattgodbolt** [comment]
Sorry for the delay. Our GPU-running compilers have an extra step that I often forget to do too; I'm not sure if that's what happened here but I'll try and remember to do it next time

**Comment by partouf** [comment]
this is now live

**Pull request merged**
