### PR TITLE
Filter compilers in execution panel

### LINKED ISSUE #1506: Filter executable compilers on execute only pane
As mentioned by @apmorton in https://github.com/mattgodbolt/compiler-explorer/issues/1502#issuecomment-512588950, we should filter the compilers on the dropdown one way or another

I think the best choice between the three given alternatives is to gray those unsupported compilers. It does not clutter the UI further and I think selectize js already supports this feature out of the box.

### LINKED ISSUE #2026: [BUG] Error with compilation/execution and confusing error message
Seen on twitter: https://twitter.com/Doomed_Daniel/status/1271860881127804929?s=20

> Seems like Wine+MSVC compilation+execution is currently broken, I get "Command line error D8021 : invalid numeric argument '/Wl,-rpath,/opt/compiler-explorer/windows/19.10.25017/lib/native/bin/lib'"
(I guess cl.exe or windows in general doesn't support RPATH?) 
@mattgodbolt

Possibly relating to #2022 where the poster there is seemingly able to mostly execute on windows?

### LINKED ISSUE #2180: Filter out compilers that don't supportExecute in the Execution pane
Suggested to do have the API recognize this as well and not try even if it's requested.

### PR DESCRIPTION
**Pull request by partouf**
Fixes #2180
Fixes #2026 
Fixes #1506

- [x] Doesn't show compilers that don't have supportsExecute=true
- [x] Links should still work if something was selected that doesn't supportExecute
- [x] Block execution serverside when !supportsExecute

### CODE REVIEW

**Comment by shunding** [comment]
Looks like Swift executor become broken after this was merged. Hope this could be fixed by updating configs.

**Comment by partouf** [comment]
> Hi @partouf! Looks like Swift executor become broken after this was merged. Hope this could be fixed by updating configs.

Got it, do you have an example that should execute?

**Comment by shunding** [comment]
> > Hi @partouf! Looks like Swift executor become broken after this was merged. Hope this could be fixed by updating configs.
> 
> 
> 
> Got it, do you have an example that should be able to execute?

Sure, https://godbolt.org/z/7jxWMh, I've just started explorer, switched to Swift and added executor pane

**Comment by partouf** [comment]
> > > Hi @partouf! Looks like Swift executor become broken after this was merged. Hope this could be fixed by updating configs.
> > 
> > 
> > Got it, do you have an example that should be able to execute?
> 
> Sure, https://godbolt.org/z/7jxWMh, I've just started explorer, switched to Swift and added executor pane

Right, but this wouldn't work, do you have an example with the entrypoint/main ?

**Comment by shunding** [comment]
According to Swift [documentation](https://docs.swift.org/swift-book/GuidedTour/GuidedTour.html): "Code written at global scope is used as the entry point for the program, so you don’t need a main() function."

**Comment by partouf** [comment]
Execution has only worked from v5.1, so we never noticed this was actually working.

So execution for Swift is now live https://godbolt.org/z/6cMrMW

**Comment by shunding** [comment]
That's great! Thanks!

**Pull request merged**
