### PR TITLE
Use EXECVE mode instead of ONCE

### LINKED ISSUE #5224: [BUG]: SIGABRT reported as SIGSEGV
### Describe the bug

A program that terminates signaled with SIGABRT is reported as having been signaled with SIGSEGV. This is misleading and confusing for beginners (see: https://www.reddit.com/r/Cplusplus/comments/14n0kh3/why_do_my_unhandledexceptionprogram_result_in/ )

### Steps to reproduce

Using any runnable x86 or x86-64 compiler (e.g. gcc 13.1):
```c++
#include <stdlib.h>
int main() {
    abort();
}
```

### Expected behavior

Reported status should be:
```
Program returned: 134
  Program terminated with signal: SIGABRT
```

### Reproduction link

https://godbolt.org/z/xTrh45W9M

### Screenshots

Reported status is:
```
Program returned: 139
  Program terminated with signal: SIGSEGV
```

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by ecatmur**
In ONCE mode, the program is the init process of the pid_namespace which means it won't receive signals for which it hasn't established a signal handler, so if it tries to raise() a signal (e.g. SIGABRT from std::terminate in response to an uncaught exception) that will silently be ignored and the program will behave strangely (e.g. abort() will terminate it with SIGSEGV).

In EXECVE mode, nsjail provides an init process which is parent to the program, so it behaves as expected. Closes #5224 .

### CODE REVIEW

**Comment by ecatmur** [comment]
image

Note that by contrast to #3567, the signal is reported replacing the exit code (a POSIX process has either a WEXITSTATUS or a WTERMSIG, not both, whatever the shell says).

**Comment by ecatmur** [comment]
See also #2936.

**Comment by ecatmur** [comment]
^^ this is using upstream nsjail (google/nsjail@master), not the compiler-explorer fork, 3.3-11-ge507a64

**Comment by mattgodbolt** [comment]
Sounds like a good fix: Austin & Partouf, can you take a look: partouf I tihnk you made the CE branch of nsjail, and Austin does this look like a safe fix to apply to you?

**Comment by apmorton** [comment]
I don't think the description of ONCE vs EXECVE modes in nsjail is completely accurate.

In ONCE mode the user process is indeed PID1 inside a new PID namespace (and thus has the issues you described).

In EXECVE mode there is a dummy PID1 created in a new PID namespace, but the user process is not in that namespace - and thus cannot see itself in `/proc`.  It is also parented by the node app, not the dummy init process.  I think this is an equally weird situation to be in.  Try to read the contents of `/proc/self/cmdline` with EXECVE mode.

EXECVE also breaks `--time_limit`, since there is no longer a parent process to monitor and reap the child tree.

None of these issues are show stoppers, but I'm not sure the benefits outweigh the downsides, and I'm a bit weary of a big change to how our sandbox behaves - for both security and backwards compatibility reasons.

**Comment by mattgodbolt** [comment]
Thanks @apmorton - @ecatmur we very much appreciate the fix, but to me the loss of `--time-limit` is a concern. I'm sure you appreciate how important having a cast-iron guarantee on a timed process death is to us. Can you perhaps look and see if there's another option?

**Comment by mattgodbolt** [comment]
I'm going to close this. Thanks; but this isn't quite right for CE.

**Comment by mattgodbolt** [comment]
We may have to revisit this: perhaps I was too hasty...

**Pull request closed without merging**
