### PR TITLE
Add strict tsc flag for the backend ts code

### PR DESCRIPTION
**Pull request by RubenRBS**
This PR enables the strict tsc flag (minus explicit/implict any warnings as we still need them) in the backend code

There's also a version for the frontend side, but I decided to try to merge this one first as it changes less files so it will be easier to merge in parts rather than all at once

### CODE REVIEW

**Comment by RubenRBS** [comment]
The error comes from static/ansi-to-html.ts failing some checks, but that's weird because those do not trigger for me locally (as strict should be disabled there in the first place)

**Comment by mattgodbolt** [comment]
Hugely in favour of this PR, once we work out why the strict isn't being disabled in this case.

**Comment by RubenRBS** [comment]
It should now be fixed, I moved the strict stuff to the backend tsconfig file

**Comment by RubenRBS** [comment]
Or maybe not... 🤔 Now I'm confused

**Comment by RubenRBS** [comment]
Tested locally. Merging both PRs seems to work

**Pull request merged**
