### PR TITLE
Add NASM 2.16.01

### LINKED ISSUE #5506: [COMPILER REQUEST]: NASM 2.16.01
### Compiler name

NASM

### Compiler version

2.16.01

### Compiler language

Assembly

### Compiler homepage

https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/

### Motivation

The latest release of NASM hosted on compiler explorer is version is 2.14.02 from all the way back in [December 2018](https://www.nasm.us/pub/nasm/releasebuilds/?C=M;O=D)

I'm currently learning x86 assembly and it would be nice to use the latest version of the assembler with the latest macros for https://asm.godbolt.org 😄

### PR DESCRIPTION
**Pull request by wmentha**
Closes #5506 

See PR in infra: [Update NASM version to 2.16.01](https://github.com/compiler-explorer/infra/pull/1101)

Decided to have a go at adding latest NASM release. Let me know if there is anything I missed.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Due to unfortunate changes in our admin/setup, the infra build didn't work (no fault of yours). I filed compiler-explorer/infra#1102 to track

**Comment by mattgodbolt** [comment]
I think I have this sorted; will merge and get it working! thanks again!

**Comment by wmentha** [comment]
@mattgodbolt Thank you so much! ☺️

**Comment by mattgodbolt** [comment]
Hoping to get this live in the next hour or so if I have time before I need to get to bed.

**Comment by mattgodbolt** [comment]
This is rolling out now

**Pull request merged**
