### PR TITLE
Kind of ISA cleanup

### PR DESCRIPTION
**Pull request by dkm**
Initially wanted to simply add 'vax' in the compiler picker, but ended
up trying to cleanup a bit how ISA property is set.

For gcc compilers, I've tried to rely on the executable name matching
mechanism instead of having the property set all around in .properties
files.

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

### CODE REVIEW

**Comment by partouf** [comment]
what does this need in order to be ready?

**Comment by partouf** [comment]
oops, i broke something

**Comment by dkm** [comment]
> what does this need in order to be ready?

was too close to me being away for 10days, so was waiting to have some time to carefully test all these changes. Thanks for having spent some time on it, I'll try to resume work next week

**Comment by dkm** [comment]
Sorry, I've nuke previous changes. The merge in between make things a bit harder for diffing... So ended up squashing all changes and redoing everything.

**Review by jeremy-rifkin — APPROVED** [review]
I think these changes look good to me!

**Comment by RubenRBS** [comment]
Anything we can do to get this thru the finish goal?

**Comment by dkm** [comment]
Sorry, will try to finish this one this week (or maybe next week)

**Comment by dkm** [comment]
Looks like it seems to be OK:
image
image
image

**Comment by jeremy-rifkin** [comment]
🎉

**Pull request merged**
