### PR TITLE
Enable diff view to use GNAT (Ada) expanded code

### PR DESCRIPTION
**Pull request by dkm**
This change allows for the selection of the GNAT (Ada) expanded code to
be used in the diff pane.

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

### CODE REVIEW

**Comment by dkm** [comment]
The diff could probably be made a bit smarter by only showing active content from the selection picker instead of showing all the possible input (eg. having GNAT or execution in the list when only simple compilation for Rust is misleading).

Screenshot 2021-11-17 at 22-09-02 Compiler Explorer

**Review by partouf — APPROVED** [review]
Glad it wasn't hard to implement this, lgtm

**Comment by dkm** [comment]
Yes, that was easier than expected :)

**Comment by mattgodbolt** [comment]
this is now live, thanks!

**Pull request merged**
