### PR TITLE
Zig 0.8.0

### PR DESCRIPTION
**Pull request by ojeda**
Infra: https://github.com/compiler-explorer/infra/pull/526

### CODE REVIEW

**Comment by partouf** [comment]
Hi @ojeda it seems Zig 0.8.0 gives a PANIC on the basic example code, ideas?

**Comment by partouf** [comment]
```
./example.zig:7:71: error: container 'builtin' has no member called 'StackTrace'
pub fn panic(msg: []const u8, error_return_trace: ?*@import("builtin").StackTrace) noreturn {
                                                                      ^
/opt/compiler-explorer/zig-0.8.0/lib/std/builtin.zig:664:61: note: referenced here
pub const panic: PanicFn = if (@hasDecl(root, "panic")) root.panic else default_panic;
                                                            ^
Compiler returned: 1
```

**Comment by partouf** [comment]
trunk does too

**Comment by ojeda** [comment]
I have no knowledge on Zig internals at all, but it sounds like https://ziglang.org/download/0.8.0/release-notes.html#importbuiltin-no-longer-re-exports-stdbuiltin

i.e. it looks like the standard library uses the old way and should be updated. Is CE reusing an old version of the standard library or something like that?

Paging @andrewrk

**Comment by partouf** [comment]
Internally we prepend this to the code:
https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compilers/zig.js#L64

We might have to add extra version specific code to that then?

**Comment by ojeda** [comment]
Yeah, it looks like we would need to update it with `?*@import("std").builtin.StackTrace` instead (a guess).

**Comment by partouf** [comment]
> Yeah, it looks like we would need to update it for >= 0.8.0 with `?*@import("std").builtin.StackTrace` instead (a guess).

Testing this locally, local pc being slow though...

**Comment by partouf** [comment]
This is now live

**Comment by andrewrk** [comment]
Yep that's the fix. Apologies for the breakage, and much love to compiler-explorer project for being willing to support a pre-1.0 compiler/language that is still undergoing breaking changes.

We do have test coverage for the compiler-explorer use case upstream, which notified me of the breakage. I intended to submit a PR but got overwhelmed and didn't get around to it. Thank you for fixing it!

**Pull request merged**
