### PR TITLE
Added TypeScript Native 0.0.27 alpha

### PR DESCRIPTION
**Pull request by ASDAlexander77**
Added TypeScript compiler for Ubuntu 20.04 ver 0.0.27-alpha

### CODE REVIEW

**Comment by partouf** [comment]
From our CI checks:

```
## typescript.amazon.properties
bad_compilers_exe:
  Line 22: tsc_0_0_27_gc
  Line 26: tsc_0_0_27_nogc
bad_compilers_id:
  Line 22: tsc_0_0_27_gc
  Line 26: tsc_0_0_27_nogc
bad_default:
  Line 30: tsc_0_0_27_gc
```

**Comment by ASDAlexander77** [comment]
> From our CI checks:
> 
> ```
> ## typescript.amazon.properties
> bad_compilers_exe:
>   Line 22: tsc_0_0_27_gc
>   Line 26: tsc_0_0_27_nogc
> bad_compilers_id:
>   Line 22: tsc_0_0_27_gc
>   Line 26: tsc_0_0_27_nogc
> bad_default:
>   Line 30: tsc_0_0_27_gc
> ```

Hi Guys,

Can u help me to find out what is the error?  I see that  "propscheck.py" seems that (I guess) compiler is missing but this is in "infra" at that moment.

Thank you.

**Comment by partouf** [comment]
the propcheck is Only about the properties file, not about the actual locations of the exe's
you didn't add tsc_0_0_27_nogc and tsc_0_0_27_gc to this line https://github.com/compiler-explorer/compiler-explorer/pull/5023/files#diff-25782bdfbf0caa7040b7294e8eb175db693c7b8ae66b19c017a48823eeef6f5fL5

**Comment by ASDAlexander77** [comment]
> 

Thank you, I was running propscheck.py in debug mode and found the issue,

**Comment by partouf** [comment]
this is now live

**Pull request merged**
