### PR TITLE
Make scroll-up increase the font size and scroll-down decrease it

### PR DESCRIPTION
**Pull request by OfekShilon**
Just feels more natural

### CODE REVIEW

**Comment by OfekShilon** [comment]
Whoa, how did the `defaultDelayAfterChange` end up here

**Comment by AbrilRBS** [comment]
It feels more natural for me the way it is right now, but looks good to me to like this - Don't know what the rest thinks, happy to hear their opinion

**Comment by OfekShilon** [comment]
> It feels more natural for me the way it is right now, but looks good to me to like this - Don't know what the rest thinks, happy to hear their opinion

Sure - if others feel like you I'll happily take this down.

**Comment by OfekShilon** [comment]
@mattgodbolt  @partouf   wdyt?

**Comment by partouf** [comment]
I don't have an opinion, I never use the font setting

**Comment by mattgodbolt** [comment]
I do use it and I think this is a good idea: thank you!

**Comment by partouf** [comment]
this is now live

**Pull request merged**
