### PR TITLE
Add Multi library to Circle compiler

### PR DESCRIPTION
**Pull request by correaa**
This library with C++ compiler already

library source and details here: https://gitlab.com/correaa/boost-multi

### CODE REVIEW

**Comment by correaa** [comment]
I understand that the corresponding change for the live site is not necessary.
Because the infrastructure is already declared there: https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L770-L777

Please correct me if I am wrong.

**Comment by RubenRBS** [comment]
Hola! Thanks for the PR. You're correct, the config already present in the infra repo is enough.
I'll merge now and it should be live in the next few days :)

**Comment by correaa** [comment]
Gracias! Next step will be to add it to the CUDA compiler. The library works nicely with CUDA and with Thrust.

**Comment by RubenRBS** [comment]
We're currently working with nvidia to support code execution in the GPU, so anything regarding cuda might take a bit before it can get merged until we sort things out with that

**Comment by RubenRBS** [comment]
I'm not too knowledgeable with the nvc stuff so I might be wrong, but I _think_ it would work, yes. We can test it once we merge it

**Comment by correaa** [comment]
done. #4367

**Comment by dkm** [comment]
this is live :rocket:

**Comment by correaa** [comment]
and works well: https://godbolt.org/z/fMxE5GhYr

**Comment by dkm** [comment]
Thanks for the confirmation @correaa !

**Pull request merged**
