### PR TITLE
Add the LLVM TableGen language

### PR DESCRIPTION
**Pull request by DavidSpickett**
LLVM TableGen is used to generate complex output files in the llvm project. A generic description of classes and definitions produces "records" that can then be walked by a TableGen backend to produce things like C++ code, configuration files, etc.

The biggest examples are LLVM's assembler and disassembler where all the targets' instructions are defined in TableGen.

https://llvm.org/docs/TableGen/ProgRef.html

An example:
```
class Register<int _size, string _alias=""> {
    int size = _size;
    string alias = _alias;
}
def X0: Register<8> {}
def X29: Register<8, "frame pointer"> {}
```
```
------------- Classes -----------------
class Register<int Register:_size = ?, string Register:_alias = ""> {
  int size = Register:_size;
  string alias = Register:_alias;
}
------------- Defs -----------------
def X0 {        // Register
  int size = 8;
  string alias = "";
}
def X29 {       // Register
  int size = 8;
  string alias = "frame pointer";
}
```

It's often a pain point for people new to LLVM so having a quick way to experiment would be a great benefit for the community (we have a Jupyter kernel which is good but not as simple as Compiler Explorer).

The compiler for TableGen is `llvm-tblgen`. This comes with most release builds of LLVM in /bin along with clang and the others. Its default is to output a text dump of the records defined so that's what I've used here. This is not executable code so I've disabled the features related to that.

A user could pass options to `llvm-tblgen` to produce text in a format other than this, C++ code or JSON for example. However this text dump is the main use case.

I've re-used an existing clang install, since that includes `llvm-tblgen` in `bin/`. I just added the 17.01 version for this first change.

Syntax highlighting is a mix of the Fortran and Ada configuration, following the language spec I linked above. Though I am very new to that so it is likely incomplete.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
I realise that because TableGen doesn't and cannot produce executable code, it may be out of scope for Compiler Explorer but I figured I'd give it a go in anyway.

I don't speak for the LLVM project itself, this is just my initiative. So if it looks like you would accept TableGen in Compiler Explorer, I'll bring in some folks from LLVM to check that I'm not misrepresenting anything.

As stated, I'm reusing one of the clang installs. I did install it locally and check the file exists, but wasn't sure how to locally use the `amazon` config, it wanted to use `default`. If there's a way to change that I can test it locally.

**Comment by partouf** [comment]
> I realise that because TableGen doesn't and cannot produce executable code, it may be out of scope for Compiler Explorer but I figured I'd give it a go in anyway.

That's no problem at all

> I don't speak for the LLVM project itself, this is just my initiative. So if it looks like you would accept TableGen in Compiler Explorer, I'll bring in some folks from LLVM to check that I'm not misrepresenting anything.

> As stated, I'm reusing one of the clang installs. I did install it locally and check the file exists, but wasn't sure how to locally use the `amazon` config, it wanted to use `default`. If there's a way to change that I can test it locally.

Just tested the amazon config, looks great

One thing I'm wondering about is if the language's name should be "LLVM TableGen" instead of just "TableGen", just so that the sorting brings it together with LLVM IR and LLVM MIR

**Comment by DavidSpickett** [comment]
> One thing I'm wondering about is if the language's name should be "LLVM TableGen"

Done.

**Comment by DavidSpickett** [comment]
Posted https://discourse.llvm.org/t/rfc-tablegen-on-compiler-explorer/74316 to gather any comments from the llvm side.

**Review by mattgodbolt — APPROVED** [review]
Looks good to me: thank you!

**Comment by mattgodbolt** [comment]
I'll happily merge and get this launched; and any comments from the discourse could be applied in subsequent PRs :)

**Comment by mattgodbolt** [comment]
This is now live :)

**Pull request merged**
