### PR TITLE
For clang cross-compiles with libc++, explicitly add `-I../include/x86_64…

### LINKED ISSUE #5293: [BUG]: LLVM cross compilers fail with -stdlib=libc++
### Describe the bug

When using armv8-a clang and using LLVM's own libc++ compilation fails, see https://godbolt.org/z/rYEG39j96

This seems to be another manifestation of a clang bug https://github.com/llvm/llvm-project/issues/57104 in that the LLVM build system doesn't correctly normalize targets.  from https://github.com/llvm/llvm-project/issues/57104#issuecomment-1336442726 it seems like setting LLVM_RUNTIME_TARGETS during build should maybe fix it So I think here? https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh#L167

### Steps to reproduce

on a C++ compiler, use `-O3 -stdlib=libc++` and use a standard header.

compilation should succeed.

### Expected behavior

expected compilation to work

### Reproduction link

https://godbolt.org/z/rYEG39j96

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by OfekShilon**
…-unknown-linux-gnu/c++/v1/`

This hopefully fixes #5293 and #5143. 
But must be tested in staging first - the workaround depends indirectly on `/usr/include` contents and so I can't test locally.

### CODE REVIEW

**Comment by partouf** [comment]
Sorry, I mixed up things in my brain when reading this on discord, but this is not actually correct when it is concerning cross builds.
The problem with cross builds with libc++ is that clang does not include the different targets.

It will always look for the triple that is either default (x86_64 linux) or when you pass a different one, that one. So that's why it's not included by default, which is correct.

In the case of gcc's stdlib, we also always have to supply the correct architecture toolchain, and the target triple + include directory name have to match there, otherwise it will give similar errors.

The last time I was looking at how we build clang, I got the feeling there's just a bug in Clang's cmake. But I'm just going to investigate that right now, because i'm kind of sick of this issue.

**Comment by partouf** [comment]
I've been running a test for targetting only aarch64, and it still produces only a `include/x86_64-unknown-linux-gnu/c++/v1` directory, it's probably just using the host's guestimated triple.

Comparing the directory, I noticed there's really only a `__config_site` header and no other files, and its contents aren't target related.

The configuration is I think defined here https://github.com/llvm/llvm-project/blob/9632e1515c93453efc39752b1c9f32aedd358fbc/libcxx/include/__config_site.in#L9 which is similar to the defines in the config site header.

So maybe this is a fine solution, although the header should probably just be moved to `include/c++/v1`

Going to investigate a bit further

**Comment by partouf** [comment]
Here's a hint on what's going on:
https://github.com/llvm/llvm-project/blob/9632e1515c93453efc39752b1c9f32aedd358fbc/libcxx/CMakeLists.txt#L435C4-L435C38

(and there's even a TODO https://github.com/llvm/llvm-project/blob/9632e1515c93453efc39752b1c9f32aedd358fbc/libcxx/CMakeLists.txt#L422)

The LIBCXX_GENERATED_INCLUDE_TARGET_DIR is set to something that uses LLVM_DEFAULT_TARGET_TRIPLE (instead of looping over LLVM_TARGETS_TO_BUILD)

**Comment by partouf** [comment]
(and we can't really set LLVM_ENABLE_PER_TARGET_RUNTIME_DIR as it's set automatically by https://github.com/llvm/llvm-project/blob/9632e1515c93453efc39752b1c9f32aedd358fbc/llvm/CMakeLists.txt#L888)

**Comment by partouf** [comment]
The same issue applies to `lib/x86_64-unknown-linux-gnu` which contains `libc++.so` and related files
So those aren't built correctly either for crosscompiling

**Comment by OfekShilon** [comment]
A heretic thought here: what if we don't do cross-compile?
If we take an ARM instance on AWS and build clang (at least recent versions) for ARM, we could also offer ARM execution.
This cross-compiling llvm issue has been known for 1.5Y+. Waiting for it to be solved can be a while.

**Comment by partouf** [comment]
> A heretic thought here: what if we don't do cross-compile? If we take an ARM instance on AWS and build clang (at least recent versions) for ARM, we could also offer ARM execution. This cross-compiling llvm issue has been known for 1.5Y+. Waiting for it to be solved can be a while.

Definitely an option, and something we might do anyway. But that wouldn't solve anything for any of the other targets.

**Comment by partouf** [comment]
(and having to compile all our clang trunk varieties on arm)

**Comment by OfekShilon** [comment]
Yep.

**Comment by partouf** [comment]
Maybe it's possible to only build libcxx and then build it for a couple of different targets, perhaps that wouldn't also require to build llvm or clang.. Going to give it a try

**Comment by partouf** [comment]
long story short - it's not trivial to build subprojects of llvm, and building llvm with a gcc crosscompiler results in errors as well

I'm a little lost

**Comment by OfekShilon** [comment]
> ... this is not actually correct when it is concerning cross builds. The problem with cross builds with libc++ is that clang does not include the different targets.

Another thought: 
I know this PR wasn't a safe long-term solution (was well aware when submitting it) but maybe after all it is good enough as a workaround? I'm not sure what the `unknown-linux-gnu` triple was designed for, but empirically adding it to the include path does enable compiles that currently fail.

**Comment by partouf** [comment]
> Another thought: I know this PR isn't a safe long-term solution (was well aware when submitting it) but maybe after all it is good enough as a workaround? I'm not sure what the `unknown-linux-gnu` triple was designed for, but empirically adding it to the include path does enable compiles that currently fail.

I agree

**Comment by partouf** [comment]
now live

**Pull request merged**
