### PR TITLE
Correct several colors in one dark

### PR DESCRIPTION
**Pull request by mguid65**
Fixed:
- Dropdown menu disabled color
- Dropdown menu active color
- General panel background color
- Separator line for minimap
- Output text-count color
- Remove pure white across theme
- Fix custom-select in popout

### CODE REVIEW

**Comment by mguid65** [comment]
Screenshot from 2024-04-10 14-38-48

I added this border to the minimap so that there is a visual separation between the editor and the minimap. In the dark theme, the minimap is a slightly different color.

I want feedback about this. I tried to lighten the color of the minimap but I couldnt figure out the right place in the CSS to modify the color. I settled on this 1px border.

I want feedback on this

**Comment by partouf** [comment]
> I added this border to the minimap so that there is a visual separation between the editor and the minimap. In the dark theme, the minimap is a slightly different color.
> 
> I want feedback about this. I tried to lighten the color of the minimap but I couldnt figure out the right place in the CSS to modify the color. I settled on this 1px border.

I like the border. Is the shadowed border on the output side of things on purpose? that one is a bit extreme

Just my opinion ofcourse

**Comment by mguid65** [comment]
> > I added this border to the minimap so that there is a visual separation between the editor and the minimap. In the dark theme, the minimap is a slightly different color.
> > 
> > I want feedback about this. I tried to lighten the color of the minimap but I couldnt figure out the right place in the CSS to modify the color. I settled on this 1px border.
> 
> I like the border. Is the shadowed border on the output side of things on purpose? that one is a bit extreme
> 

The shadow border always appears when there is a horizontal overflow. This is also the case on the other themes.

**Comment by partouf** [comment]
> The shadow border always appears when there is a horizontal overflow. This is also the case on the other themes.

Ahhh ok

**Comment by jeremy-rifkin** [comment]
The 1px border looks good to me. It looks like when text actually goes past the map monaco does add a drop shadow as well:
image

I think the minimap background is a monaco setting rather than a css thing, if you want to play around with that.

**Comment by mguid65** [comment]
> The 1px border looks good to me. It looks like when text actually goes past the map monaco does add a drop shadow as well: image
> 
> I think the minimap background is a monaco setting rather than a css thing, if you want to play around with that.

I found the setting and tried a few colors and I think it is best as it is already with the 1px border.

**Review by jeremy-rifkin — APPROVED** [review]
Sounds good to me!

**Pull request merged**
