### PR TITLE
Add profile support for dex2oat.

### PR DESCRIPTION
**Pull request by kevinjeon-g**
dex2oat supports profile-guided compilation. In addition to taking dex code as an input, it can take a profile as another input, to guide the compilation. The profile determines which methods need to be compiled, how calls can be inlined, and so on.

Because Compiler Explorer doesn't support multiple input files, the profile is added as a comment block in the Java/Kotlin source code. A post-processor extracts the profile from the comment block into a separate file, in order to input it to dex2oat.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
> Because Compiler Explorer doesn't support multiple input files, the profile is added as a comment block in the Java/Kotlin source code. A post-processor extracts the profile from the comment block into a separate file, in order to input it to dex2oat.

We do, though maybe not in a useful way? we support full linking of C++ programs with [multiple sources](https://godbolt.org/z/WE9T6K17W). But I suspect that's too heavyweight for what you're talking about here. I'm happy to merge this like it is though:

**Review by mattgodbolt — APPROVED** [review]
Will merge as-is to unblock you. Let me know if you need anything else.

**Comment by mattgodbolt** [comment]
This is now live

**Comment by kevinjeon-g** [comment]
> We do, though maybe not in a useful way? we support full linking of C++ programs with [multiple sources](https://godbolt.org/z/WE9T6K17W). But I suspect that's too heavyweight for what you're talking about here. I'm happy to merge this like it is though:

I didn't know this was supported, this is good to know! I agree, I think it might be a bit more difficult to implement compared to the comment parsing.

Thank you for taking a look!

**Comment by kevinjeon-g** [comment]
> > We do, though maybe not in a useful way? we support full linking of C++ programs with [multiple sources](https://godbolt.org/z/WE9T6K17W). But I suspect that's too heavyweight for what you're talking about here. I'm happy to merge this like it is though:
> 
> I didn't know this was supported, this is good to know! I agree, I think it might be a bit more difficult to implement compared to the comment parsing.

Actually, one of my coworkers wrote a patch that uses the multiple-inputs + templates instead—I'll upload that change once the fix for the sandbox-write issue is live.

**Pull request merged**
