### PR TITLE
Added Clang 10.0.1 and 11.0.0 for Arm

### PR DESCRIPTION
**Pull request by willlovett-arm**
Change-Id: Ice34c191adf832d1e874f3ba8fbec7c81ef1f125

### CODE REVIEW

**Comment by willlovett-arm** [comment]
11.0.0 brings support for v8.6a with it, so we should bump the 'trunk all features' compilers also.  To do that, we'd want to rename the v8.5a compiler (oops) to something more generic, and add an alias.
**Question:** is that ok? I *think* it will mean that links that previously built with v8.5a trunk will now build with v8.6a trunk - but maybe that's not a problem for trunk builds?

**Comment by willlovett-arm** [comment]
I've added another patch, as described above.  Note that I've checked the 10.0.1 and 11.0.0 compilers work locally, but I don't have a local trunk build so the second patch is untested.

**Comment by willlovett-arm** [comment]
Sigh - my cleanup is broken on my local instance.  Hold on

**Review by mattgodbolt — APPROVED** [review]
Sorry for taking so long on this; just testing locally and then will merge!

**Pull request merged**
