### PR TITLE
Update Makefile

### LINKED ISSUE #2595: Make issues everywhere
The last couple of months we've been hearing more and more issues with `make` and it not doing enough work to start CE.

Issues are always resolved by "just doing" `npm i` + `npm run` dev/start.

### Mac issues
* Not sure what the problem is here, it doesn't seem to npm install, the rest appears to work.

### Node 15
Recently we had someone with node 15 on arch linux that had 2 issues after a `make`:
* Supervisor was not installed
  * Not sure how to resolve this
* The line with npm install --only=dev doesn't work
  * https://github.com/compiler-explorer/compiler-explorer/blob/a194b5a591658d69eba5a9f12d7b5e596d82c561/Makefile#L39

### Other issues after updating node/npm
* `webpack-cli/bin/cli.js`: No such file or directory
  * It seems webpack-cli is not installed (so also the dev bits) with `make`

### LINKED ISSUE #3230: [BUG]: Running locally in Ubuntu 21.10 gives an error "cli.js not found"
### Describe the bug

Running locally in Ubuntu 21.10 generates an error regarding `cli.js`

```
$ make
Warning: Compiler Explorer is only tested against v14.x, but v17 was found.
Note that you might find issues if you decide to keep this version
Visit https://nodejs.org/ for installation instructions for the required version
To configure where we look for node, set NODE_DIR to its installation base
/usr/bin/npm install 
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated vis@4.20.1: Please consider using https://github.com/visjs

> compiler-explorer@0.0.3 prepare
> husky install

husky - Git hooks installed

added 557 packages in 9s

32 packages are looking for funding
  run `npm fund` for details
rm -rf out/dist/static out/dist/manifest.json
./node_modules/webpack-cli/bin/cli.js "--node-env=production"
/bin/sh: 1: ./node_modules/webpack-cli/bin/cli.js: not found
make: *** [Makefile:57: webpack] Error 127
```

### Steps to reproduce

1. Install node in Ubuntu 21.10

```
cd ~
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
```

2. Get Node.js and NPM installed by executing this command:

```
sudo apt-get install -y nodejs
```

```
$ node -v
v17.3.0
$ npm -v 
8.3.0
```

3. Clone

```
git clone git@github.com:compiler-explorer/compiler-explorer.git
cd compiler-explorer
make
```

### Expected behavior

Should install node packages and run server?

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

Ubuntu Linux 21.10

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by partouf**
Fixes #3230
(really) Fixes #2595
Maybe relates to #3226

### CODE REVIEW

**Comment by partouf** [comment]
Note: Will require `make clean` if you have a faulty installation before it will attempt to install node modules again.

**Comment by correaa** [comment]
Does this merge mean that compiler explorer might work with node v17.3.0 ?

**Comment by apmorton** [comment]
This now means all our dev dependencies will be installed all of the time (including when running `make dist`, which I believe is faulty.

If we are going to install everything all the time, we should simply do away with devDependencies.

I'd rather have the line be something like:
```
NODE_ENV=$(NPM_NODE_ENV) $(NPM) ...
```
and then default NPM_NODE_ENV to development (so we can override it when running `make dist`).

Although in all honesty, this might have already been very broken to begin with, since we definitely need webpack-cli to produce a dist, and it's only mentioned in devDependencies...

**Comment by partouf** [comment]
I thought about removing all the devDependencies, because we basically do need all of it because of how we do our dev, test, deploy, run pipeline. But that seemed like a crazy change to make.

And changing our pipeline seems wrought with similar problems.

So I agree with you, but I think it's too much trouble to make perfect.

**Pull request merged**
