### PR TITLE
propcheck: applies to local config

### PR DESCRIPTION
**Pull request by dkm**
Applies to local config and fix existing issues.

By defaults, local and defaults are not checked for suspicious path (exe
not starting with /opt/compiler-explorer). This can be forced with the
--check-suspicious-in-local-prop.

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

### CODE REVIEW

**Comment by dkm** [comment]
So, looks like the existing script could be used for defaults/local also :)

**Review by RubenRBS — APPROVED** [review]
Great catch, this makes _lots_ of sense! :)

**Review by jeremy-rifkin — COMMENTED** [review]
Would it be worth using adding `--check-suspicious-in-local-prop` to the invocation in .husky/pre-commit?

**Comment by mattgodbolt** [comment]
Enabling this in the pre-commit is showing up other issues- #5251 . I think we should ignore all local.properites for pre-commit hooks (and/or all checks here!)

**Pull request merged**
