### PR TITLE
Make bracket colourisation configurable.

### PR DESCRIPTION
**Pull request by mattgodbolt**
Blocked on microsoft/monaco-editor#3013

### CODE REVIEW

**Review by jeremy-rifkin — APPROVED** [review]
Looks perfect! Ty! (That being said, colour is spelled a little funny 😄)

**Comment by mattgodbolt** [comment]
hahah right, consistency with the UI which uses "colourisation" 😁

**Comment by mattgodbolt** [comment]
Using a workaround

**Comment by jeremy-rifkin** [comment]
This is live

**Pull request merged**
