### PR TITLE
Reimplement more options for Ctrl-S

### PR DESCRIPTION
**Pull request by RubenRBS**
It was easier to just create a new PR, as I had some problems with the old one. The changes have already been reviewed so I guess there should be no major things blocking this from getting merged

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks @RubenRBS

**Review by mattgodbolt — APPROVED** [review]
Did we lose the cute easter egg? :D This is great though. The only µsurprise is the `'true'` stuff but that's for backwards compatibilty, right? Maybe one day we can version the local settings like we do URLs and then update them to more sane stuff...but this is amazing :) Thanks!! Feel free to merge whenever!

**Comment by mattgodbolt** [comment]
(tested locally both with my current setup and also from a fresh incognito browser)

**Comment by RubenRBS** [comment]
The :) shows up for me, weird

**Pull request merged**
