### PR TITLE
Update default fortran example

### PR DESCRIPTION
**Pull request by Airbus5717**
integer reflects a more accurate example compared to other languages in the code

### CODE REVIEW

**Comment by dkm** [comment]
Looks correct, but not really sure what you mean by "more accurate" ? Do you mean that `real` is rarely used?

**Comment by Airbus5717** [comment]
compared to the other langs 
int is used instead of real (which is float in other languages)
it's not super important tho

**Review by jeremy-rifkin — APPROVED** [review]
Thanks @Airbus5717, looks good to me

**Review by dkm — APPROVED** [review]
thanks, understood :)

**Pull request merged**
