### PR TITLE
Add EricWF's contracts implementation

### PR DESCRIPTION
**Pull request by EricWF**

### CODE REVIEW

**Comment by AbrilRBS** [comment]
Related infra PR: https://github.com/compiler-explorer/infra/pull/1363

**Comment by EricWF** [comment]
I think this is ready to go.

https://github.com/compiler-explorer/compiler-workflows/actions/runs/9931667390/job/27431844133

Thanks for everyone's help with this.

**Comment by EricWF** [comment]
I still don't see the new compiler on the website.

The builds look successful, and I've downloaded and installed the compiler using compiler-explorer/infra.
Is there something more I need to do?

Thanks again!

**Comment by partouf** [comment]
sorry we were having a slight freeze of our production environment this week, but I'll get to this today

**Comment by partouf** [comment]
this is now live

**Pull request merged**
