### PR TITLE
Add Julia

### PR DESCRIPTION
**Pull request by aw32**
Adding basic Julia support as discussed in #331 based on code from @staticfloat.

The wrapper script `etc/scripts/julia_wrapper.jl` basically imports the input as a module,
which also executes the code.
Afterwards, the functions defined in the module are inspected for compiled methods.
(Function definitions use more generic types, while methods are generated by specializing
the types for a function call with definite argument types during dispatch. See [here](https://docs.julialang.org/en/v1/manual/methods/).)
Finally, the wrapper uses the Julia [introspection features](https://docs.julialang.org/en/v1/devdocs/reflection/) `code_native`, `code_warntype` and so on,
to print the generated code for the methods.

Per Julia design, methods are generated at the time of a function call, when the argument types are known.
To avoid executing a method just for code generation, a call to `precompile` can be executed to
trigger the code generation for specific argument types. In some cases this may fail.
Here is the example code:
```
function square(x)
    return x * x
end

precompile(square, (Int32,))
```

The output of the Julia introspection functions is printed as is, only prefixed by a header line that contains
the line number function from the input file and the number of output lines.
This allows to do a simple color mapping of output lines to (the first line of the) input function.
The server code `lib/compilers/julia.js` parses the header line in the output to create the mapping and passes the output lines.

As is, the wrapper only allows for very basic output of generated code.
Many other imaginable features, as integration with the LLVM tools and advanced syntax highlighting, might only be
possible with more advanced support from the Julia compiler.

The accompanying pull request to the infra repository is https://github.com/compiler-explorer/infra/pull/929

### CODE REVIEW

**Comment by partouf** [comment]
Thank you so much for doing this. Because this has been a thing hanging in the air for so long, I'm going to test it right now

**Comment by aw32** [comment]
@partouf Thanks for fixing the code. ♥

**Comment by partouf** [comment]
this is now live

**Comment by Seelengrab** [comment]
I'm trying to add ASM syntax switching support (since `code_native` also supports that), but I'm having trouble getting this to run locally with `make dev`, since the `--` ends up pushed into the `ARGS` as the first argument, causing `FileNotFound`. I suspect something is going wrong in the TS invocation/argument builder, but even with no changes to the `julia.defaults.properties` file, basic local usage doesn't seem to work. What am I doingwrong?

**Comment by aw32** [comment]
> I'm trying to add ASM syntax switching support (since `code_native` also supports that), but I'm having trouble getting this to run locally with `make dev`, since the `--` ends up pushed into the `ARGS` as the first argument, causing `FileNotFound`. I suspect something is going wrong in the TS invocation/argument builder, but even with no changes to the `julia.defaults.properties` file, basic local usage doesn't seem to work. What am I doing wrong?

The argument evaluation in the `etc/scripts/julia_wrapper.jl` script is very basic.
You can take a look inside and you will see that it simply iterates over the arguments and does string operations.
No argument parsing package was used to minimize dependencies and simplify deployment for a first version of the script.

**Comment by Seelengrab** [comment]
I'm not talking about the wrapper per se - it's perfectly clear what it's doing. I'm saying that the wrapper already gets `["--", "--help"]` as `ARGS` when passing `-h` locally, which then makes the script crash due to there not being a file called `--`.

**Comment by aw32** [comment]
If I start the current repo `main`with `make dev EXTRA_ARGS='--language julia'` it shows the same output with `-h` as the live version and `ARGS` is printed as `["--help"]`.

The Julia man-page defines `julia [OPTIONS...] -- [PROGRAMMFILE] [ARGS...]` as command line.
But actually, Julia also removes the `--` if it is set after [PROGRAMMFILE]`.
That's why the `--` from the julia.ts never reaches the wrapper script.

At least, that's what happens for me on MacOS, Homebrew Julia 1.8.5

**Comment by Seelengrab** [comment]
That is a buggy behavior that's been fixed, see https://github.com/JuliaLang/julia/pull/45335

**Pull request merged**
