### PR TITLE
[Library Request] Add async_simple library

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
Close https://github.com/compiler-explorer/compiler-explorer/issues/5380

The infra part was introduced in
https://github.com/compiler-explorer/infra/pull/1072

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
@mattgodbolt gentle ping~ given https://github.com/compiler-explorer/infra/pull/1072 is merged, I guess it may be OK to merge this one too?

**Comment by mattgodbolt** [comment]
Apologies! yes, looks good! Hope to get this rolled out on Wednesday!

**Comment by mattgodbolt** [comment]
this is live!

**Comment by ChuanqiXu9** [comment]
Thank you very much!

**Pull request merged**
