### PR TITLE
Use correct kokkos version and `packagedheaders=true`

### PR DESCRIPTION
**Pull request by cz4rs**
- fix a typo and use correct kokkos version
- drop `trunk` as it is not used in `infra`

### CODE REVIEW

**Comment by cz4rs** [comment]
Thanks for the update @partouf. Does this need any other changes?

**Comment by partouf** [comment]
The library seems to have a dependency on `libdl`, are users expected to add `-ldl` manually?

**Comment by cz4rs** [comment]
> The library seems to have a dependency on `libdl`, are users expected to add `-ldl` manually?

I think we can start with that. An alternative would be to add `libs.kokkos.options=-ldl`?

**Comment by partouf** [comment]
> > The library seems to have a dependency on `libdl`, are users expected to add `-ldl` manually?
> 
> I think we can start with that. An alternative would be to add `libs.kokkos.options=-ldl`?

we have some special mechanisms so the -ldl only gets sent when linking, ill try to remember how it works and push to prod

**Comment by partouf** [comment]
this is now live https://godbolt.org/z/xGMqjcKbc

**Pull request merged**
