### PR TITLE
Convert favicon images to png

### PR DESCRIPTION
**Pull request by Maddimax**
Storing the favicon images as png cuts down on the size of the image massively (11kb instead of 138kb)

If it was intended to be bmp please feel free to just reject it.

### CODE REVIEW

**Comment by apmorton** [comment]
TIL ico can contain png.

Can you also convert the remaining icons in the favicons folder?

Seems like this tool is pretty quick and easy to use: https://redketchup.io/icon-editor

**Comment by partouf** [comment]
Can every browser handle that? It's not exactly expected imo

**Comment by Maddimax** [comment]
> TIL ico can contain png.
> 
> Can you also convert the remaining icons in the favicons folder?
> 
> Seems like this tool is pretty quick and easy to use: https://redketchup.io/icon-editor

Done, but now I have carpal tunnel syndrome :)

**Comment by partouf** [comment]
> Can every browser handle that? It's not exactly expected imo

To answer my own question https://caniuse.com/link-icon-png

Not supported on IE 6-10, but we broke support for IE a few years ago now, so that's fine

**Comment by mattgodbolt** [comment]
Thanks! And sorry it caused extreme clicking!

**Comment by mattgodbolt** [comment]
This is now live: thanks again!

**Pull request merged**
