### PR TITLE
Add clang-cl to Windows compilers

### PR DESCRIPTION
**Pull request by Endilll**
Accompanied by https://github.com/compiler-explorer/infra/pull/1380

### CODE REVIEW

**Comment by Endilll** [comment]
I wish `llvm-cxxfilt` was capable of handling Microsoft mangling. Relying on MSVC toolchain for that is kinda embarrassing.

**Comment by mattgodbolt** [comment]
I'm slowly starting to look at this; sorry for the delay

**Comment by partouf** [comment]
Normal compilation works great, linking and executing gives the following warning/error:

```
clang-cl: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
clang-cl: warning: argument unused during compilation: '/FmC:\Windows\TEMP\compiler-explorer-compiler2024830-2344-l8flt7.km7s\output.s.exe.map' [-Wunused-command-line-argument]
clang-cl: error: unable to execute command: program not executable
clang-cl: error: linker command failed with exit code 1 (use -v to see invocation)
Execution build compiler returned: 1
```

**Comment by Endilll** [comment]
I don't think I will have the bandwidth in the near future to make that work. How can we (temporary) grey out linking and executing for clang-cl?

**Comment by partouf** [comment]
this is live btw https://godbolt.org/z/aaha3abT9

we can grey it out by setting `supportsBinary=false` and `supportsExecutable=false` in the properties...or something like that

**Comment by Endilll** [comment]
@partouf I opened #6925

**Comment by mstorsjo** [comment]
> I wish `llvm-cxxfilt` was capable of handling Microsoft mangling. Relying on MSVC toolchain for that is kinda embarrassing.

LLVM does have `llvm-undname` though, which mostly should do the same as MS `undname.exe` - have you tried using that?

**Comment by Endilll** [comment]
> > I wish `llvm-cxxfilt` was capable of handling Microsoft mangling. Relying on MSVC toolchain for that is kinda embarrassing.
> 
> LLVM does have `llvm-undname` though, which mostly should do the same as MS `undname.exe` - have you tried using that?

I'd expect it to work, but I learned about it after I merged this PR, and I didn't have a chance to look at this again.

**Comment by d3x0r** [comment]
``` c++
#include <memory>
```

doesn't work ....  yes I see the C runtime is there but it's missing the c++ runtime....

**Pull request merged**
