### PR TITLE
Rust 1.78.0

### PR DESCRIPTION
**Pull request by ojeda**
Infra: https://github.com/compiler-explorer/infra/pull/1290.

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]

**Comment by dkm** [comment]
This is live :rocket:

**Comment by ojeda** [comment]
Thanks! :)

**Comment by ojeda** [comment]
Hmm... It appears that the new version isn't live. Did something happen?

**Comment by partouf** [comment]
definitely not live, I believe @dkm did some steps towards it, but did not actually push it live.
I'll do it later tonight

**Comment by ojeda** [comment]
I see, thanks! No rush -- I just noticed it by chance and thought I would let you know.

**Comment by partouf** [comment]
now actually live

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
