### PR TITLE
Support numeric labels

### LINKED ISSUE #2032: [BUG] Unused numeric labels appear when using -fcf-protection
**Describe the bug**
When using the flag `-fcf-protection` with GCC on any mode other than `none`, unused numeric labels appear at the end of the output, even when filtering of unused labels is enabled.

**To Reproduce**
* Compile a C or C++ program with GCC 8 or newer, with the `-fcf-protection=full` flag
* Ensure that under "Filter", "Unused labels" is checked
* Note the labels `0`, `1`, `2`, `3`, and `4` in the output, even though they're not referenced

**Expected behavior**
I expect to not see any unused labels.

**Link**
https://godbolt.org/z/bCaNJk

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

### PR DESCRIPTION
**Pull request by RabsRincon**
Closes #2032

@cppchedy seems tro have found this some years ago https://github.com/compiler-explorer/compiler-explorer/issues/629#issuecomment-346849392

### CODE REVIEW

**Comment by partouf** [comment]
I'm not entirely sure this is the right way to do it, but apparently we don't have any unit tests that prove otherwise. Maybe it will be ok...

**Comment by mattgodbolt** [comment]
Thanks Ruben. I'm agreed with @partouf here: numeric labels are super odd in `gas` syntax:

```
1: blah
   bne 1b ; goes "back" to the blah 
   blt 1f ; goes to schmah
   moo
1: schmah
```

so we might come acropper later down the line (more info at https://docs.oracle.com/cd/E19120-01/open.solaris/817-5477/esqat/index.html )

Maybe this is different though? I've only ever seen the 1b/1f thing in hand-written asm, never from a compiler. Would be cool to have a test for the case linked too if you can make one?

I bet right now this works though, for the code the compiler emits at least.

**Comment by mattgodbolt** [comment]
Just took a look and without filtering this is what the example yielded:

```
        .long    1f - 0f
        .long    4f - 1f
        .long    5
0:
        .string  "GNU"
1:
        .align 8
        .long    0xc0000002
        .long    3f - 2f
2:
        .long    0x3
3:
        .align 8
4:
```
(via https://godbolt.org/z/odEKPi )

So this PR will fix this case (and so I think we can merge) but we should note that we're not actually processing the `1b`/`1f` syntax in a separate bug :)

**Comment by partouf** [comment]
Anything below 8 is probably Ok, but anything else might be a relative jmp and not a label jump

**Comment by partouf** [comment]
> Anything below 8 is probably Ok, but anything else might be a relative jmp and not a label jump

Realistically though, most asm includes debugging so labels are always named and never just relative numbers. But if you have for example objumps without dwarf or something it will be relative or far jumps we resolve manually.. currently there is no official compiler on the website that relies on us manually resolving labels... but in the future we might, starting with Msvc probably (and Delphi but likelyhood of that one happening ever is very low)

**Pull request merged**
