### PR TITLE
Compile CUDA with multiple versions of clang.

### PR DESCRIPTION
**Pull request by jlebar**
Not just clang trunk!

### CODE REVIEW

**Comment by jlebar** [comment]
I have no idea if this is right, but it does pass `make check`.

**Comment by partouf** [comment]
you'll need to copy paste the lot from here https://github.com/compiler-explorer/compiler-explorer/blob/master/etc/config/c%2B%2B.amazon.properties#L223
and need to give them a different name, probably cuclang700 etc

**Comment by jlebar** [comment]
cc @artem-b

**Comment by jlebar** [comment]
@partouf thank you!

> and remove/give appropriate options of course

Didn't add/remove any options because I think we can have the same options for all of the compilers.

At some point we might want to use newer versions of CUDA with newer versions of clang (CUDA is up to 11.1, but we're stuck at CUDA 9.1 here in CE), but that isn't a huge deal.

**Comment by partouf** [comment]
> @partouf thank you!
> 
> > and remove/give appropriate options of course
> 
> Didn't add/remove any options because I think we can have the same options for all of the compilers.
> 
> At some point we might want to use newer versions of CUDA with newer versions of clang (CUDA is up to 11.1, but we're stuck at CUDA 9.1 here in CE), but that isn't a huge deal.

Then you should remove the options from the individual compilers, so that the group options are used (`group.cuclang.options=--gcc-toolchain=/opt/compiler-explorer/gcc-7.2.0 --cuda-path=/opt/compiler-explorer/cuda/9.1.85 --cuda-gpu-arch=sm_35 --cuda-device-only`)

**Comment by jlebar** [comment]
Oh, I see, the options aren't merged.  Got it, done.

Thank you for stepping me through this.

**Comment by partouf** [comment]
I think this looks good now, thanks!

**Comment by Artem-B** [comment]
I wonder if it would make more sense to have an option to pick CUDA version for clang compilation.
That's where I'd expect to see more interesting variations in behavior.
We could limit it to trunk clang only as the full cartesian product of clang and CUDA versions may be rather unwieldy.

**Comment by mattgodbolt** [comment]
Hi @Artem-B - I'm inclined to merge this as-is and work on a separate change for what you suggest if @jlebar agrees. We have a big change-to-typescript PR waiting to merge and so I'm trying to get everything merged in first.

**Review by mattgodbolt — APPROVED** [review]

**Comment by jlebar** [comment]
> I'm inclined to merge this as-is and work on a separate change for what you suggest if @jlebar agrees.

Works for me; thank you for taking this patch, Matt, and thank you for running this service!

**Comment by Artem-B** [comment]
> Hi @Artem-B - I'm inclined to merge this as-is and work on a separate change for what you suggest if @jlebar agrees.

SGTM.

**Comment by partouf** [comment]
This is now live

**Pull request merged**
