### PR TITLE
Fix #4225: `make` now copies etc/scripts/disasms into out/dist

### LINKED ISSUE #4225: [BUG]: `make run` misses to deploy the "etc/scripts" folder
### Describe the bug

`make run` uses as root directory a new folder "out/dist/" which misses the "etc" folder from the repository.
Therefore, the scripts in "etc/scripts" are not available.
For example Python misses the "dis_all.py" script and fails with the following message:
```
/opt/homebrew/bin/python3.10: can't open file '/path/to/compiler-explorer/out/dist/etc/scripts/disasms/dis_all.py': [Errno 2] No such file or directory
Compiler returned: 2
```
This does not happen with the `make dev` command as it runs with the repository folder as root directory.

### Steps to reproduce

1. Clone the repository.
2. Configure "etc/config/python.defaults.properties" to define the installed Python versions.
3. Run `make run EXTRA_ARGS='--language python'`
4. Visit "http://localhost:10240/" for the local site.
5. The compilation of the example fails.

### Expected behavior

The `make run` rule should consider the necessary dependencies and/or the readme should explain how the "etc/scripts" folder is deployed to the root directory in this case.

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by OfekShilon**

### CODE REVIEW

**Comment by sasq64** [comment]
The `mkdir` and `cp` command line options does not work on macOS...

**Comment by OfekShilon** [comment]
> The `mkdir` and `cp` command line options does not work on macOS...

They should. What exactly are you running and what is the outout?

**Comment by sasq64** [comment]
```
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make prebuild
mkdir --parents out/dist/etc/scripts/disasms
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory_name ...
make[1]: *** [scripts] Error 64
make: *** [run] Error 2
```

**Comment by sasq64** [comment]
`man mkdir` mentions only `-p`, not `--parents`.

Same for `cp` and `--recursive` / `--update` ... no long options available

**Comment by partouf** [comment]
> `man mkdir` mentions only `-p`, not `--parents`.
> 
> Same for `cp` and `--recursive` / `--update` ... no long options available
> 
> macOS 15.1.1

fixed here https://github.com/compiler-explorer/compiler-explorer/commit/3c4e2bb178ff057d7710d4f3f7e699dc7399f831
though I doubt that's the only issue you'll have

**Pull request merged**
