### PR TITLE
Add clang "resugar" experimental variant (#3903)

### PR DESCRIPTION
**Pull request by mizvekov**
Signed-off-by: Matheus Izvekov <mizvekov@gmail.com>

### CODE REVIEW

**Comment by partouf** [comment]
this is now live

**Comment by mizvekov** [comment]
Thanks I saw it, awesome!

How often does it rebuild from the source branch?

**Comment by partouf** [comment]
I will add it to the nightly workflows

**Comment by mizvekov** [comment]
By the way, if this is something that I can help with by submitting a PR, don't hesitate to ask!

**Comment by partouf** [comment]
Hi @mizvekov - our automated build of resugar has been failing for a couple of days, any idea what the issue could be? Here's the latest logging https://github.com/compiler-explorer/compiler-workflows/runs/8165597340?check_suite_focus=true

**Comment by mizvekov** [comment]
I see, thanks for letting me know. I will push a workaround for it for now, and properly solve it later.

**Pull request merged**
