### PR TITLE
Hello again. Fixed snowball

### PR DESCRIPTION
**Pull request by mauro-balades**
"Fixed" snowball release build and fixed snowball version for the UI

### CODE REVIEW

**Comment by partouf** [comment]
Should we also be reinstalling the compiler?

we're getting this error:
```
[error]: (IO Error) Project configuration not found (/app/sn.toml)
help: try runing 'snowball init --cfg'
Compiler returned: 1
```

**Comment by partouf** [comment]
Fixed it by reinstalling

**Comment by partouf** [comment]
this is now live

**Comment by mauro-balades** [comment]
ok, thanks!

**Pull request merged**
