### PR TITLE
Add GLSL Logo

### PR DESCRIPTION
**Pull request by spencer-lunarg**
Follow-up of https://github.com/compiler-explorer/compiler-explorer/pull/6883

Someone pointed out today (since GLSL went live) that the OpenGL logo would be best reprentation for the language as the `GL` in `GLSL` does stand for the `GL` in `OpenGL`... also there is no other official logo and it feels like a bug that there is no logo for it :laughing:

### CODE REVIEW

**Review by junlarsen — APPROVED** [review]
Since the OpenGL logo is blue, do you think we could maybe use the same one for dark mode too? Alternatively download the white version from https://www.khronos.org/legal/trademarks/?

**Review by AbrilRBS — APPROVED** [review]
looks good to me too, but I agree with @junlarsen, seems like we can use the same dark one

(Which, as per https://github.com/compiler-explorer/compiler-explorer/blob/main/static/panes/editor.ts#L1956, will happen if we only set a light one, so this is good to go already!)

**Comment by spencer-lunarg** [comment]
I just noticed there was a `logoUrlDark` and :100: on the SVG

updated PR with new icons so please kindly take a re-review

**Review by AbrilRBS — APPROVED** [review]

**Review by junlarsen — APPROVED** [review]

**Comment by partouf** [comment]
this is now live

**Pull request merged**
