### PR TITLE
Fix unexpected es6 code in /static

### PR DESCRIPTION
**Pull request by matsjla**
Looks like some es6+ code slipped in. Also fixes a type problem in hub.ts

### CODE REVIEW

**Comment by matsjla** [comment]
You might be right, but my IDE isn't very happy with it.

**Comment by RubenRBS** [comment]
I think the proper solution here is to make the IDE allow ES6 code in static. I guess it's because some config we have that it's picking up, but no idea what that could be (As afaik, eslint is already told that it's ok to have that kind of code here)

**Comment by matsjla** [comment]
It looks like our webpack config isn't set up to transpile to es5/lower
https://static.ce-cdn.net/main.v9.e10013631aabf6f489d8.js
image

**Comment by partouf** [comment]
Disappointing...

Maybe we should just do a quick conversion to typescript and be done with it..

**Review by jeremy-rifkin — APPROVED** [review]

**Comment by matsjla** [comment]
+1 for a TypeScript conversion, but the compiler.js file is 3kloc so this will serve as a bandaid fix until then

**Pull request merged**
