### PR TITLE
Add Rust 1.50.0

### PR DESCRIPTION
**Pull request by ojeda**
Note: untested.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hi! Thanks for this. There's another change needed for this, but I've made it already in our infra repo!

**Comment by ojeda** [comment]
Oops, forgot Rust also needed it, sorry.

**Comment by mattgodbolt** [comment]
Not a problem at all: thanks for helping us keep up to date!

**Comment by mattgodbolt** [comment]
This is now live

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
