### PR TITLE
Set @typescript-eslint/no-unnecessary-condition to error

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
With #3535 all warnings are resolved and this can now be an error

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]

**Comment by matsjla** [comment]
(this depends on https://github.com/compiler-explorer/compiler-explorer/pull/3536)

**Review by matsjla — APPROVED** [review]

**Review by mattgodbolt — CHANGES_REQUESTED** [review]
So - seems that we have a bunch of errors still - the CI is complaining about a host of locations. Do you mind taking a look? Or do I need to merge something first?

**Comment by mattgodbolt** [comment]
Oh!!! @matsjla is ahead of me and I'm not reading things in order, sorry

**Comment by mattgodbolt** [comment]
So - yes, we merge the other then this. Sorry for the noise. I'm going to go and drink my morning coffee :)

**Pull request merged**
