### PR TITLE
Update descriptions for Thrust/CUB CUDA libraries.

### PR DESCRIPTION
**Pull request by allisonvacanti**

### CODE REVIEW

**Comment by partouf** [comment]
Excellent! Thanks!

If you want, you can also make examples via the share -> shortlink option, you only need the part after the /z/ and put it in a libs.thrustcub.examples=abc123 under .description

**Comment by allisonvacanti** [comment]
Ooo, good tip. I'll see what I can come up with.

**Comment by allisonvacanti** [comment]
Is there a way to name the examples in the UI?

**Comment by partouf** [comment]
> Is there a way to name the examples in the UI?

Unfortunately no. Not yet anyway.

**Comment by partouf** [comment]
This is now live, thanks again!

**Pull request merged**
