### PR TITLE
Updated doctest library to version 2.3.8

### PR DESCRIPTION
**Pull request by AMS21**
Requires [this](https://github.com/compiler-explorer/infra/pull/353) PR to be merged as well.

### CODE REVIEW

**Comment by RabsRincon** [comment]
One thing that's starting to worry me is that, with how many versions there can be on some libraries, we need to start looking into ways to reduce the visual clutter of the libraries dropdown. Either that, or cut back on how many versions we install. Happy to discuss ideas if you have any  :)

**Comment by AMS21** [comment]
Yes I agree.
One obvious idea would be to simply not list every patch version and just have the latest patch version for each minor release. So with doctest as an example you would have 2.3.8, 2.2.3, 2.1.0, 2.0.1, 1.2.9. But I guess that could theoretically break some links which only work on version 2.2.2 for example but would break on 2.2.3 (although they shouldn't if the author is actually following the semantic versioning system but I guess you never know).
Don't know if splitting the menu by their individual version components really makes sense, since it would make the menu for selecting basically bigger than it really needs to be and the whole selection process would become more tiresome.

**Comment by partouf** [comment]
maybe we could indicate to clientside that some versions can be hidden unless it's used in the current link

**Comment by AMS21** [comment]
That sounds like a good option to reduce the visual clutter.

**Pull request merged**
