### PR TITLE
Fix #5617

### LINKED ISSUE #5617: [BUG]: CFG is broken for clang-ARM compilers
### Describe the bug

It seems branches are wired only to one successor, resulting in a disconnected graph.
Is this an external tool or CE-internal logic?

### Steps to reproduce

Check this:
https://godbolt.org/z/Gfa11Wh7r

### Expected behavior

The `b.lt` instruction in the example (and many others in other places) should be connected to the upper right block ` mov     w8, w2` 
The `b.ne` instruction should be connected to `.LBB0_3`.

### Reproduction link

https://godbolt.org/z/Gfa11Wh7r

### Screenshots

image

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by OfekShilon**
Hopefully you guys are able to squash these two before merging.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks Ofek!

**Comment by mattgodbolt** [comment]
this is now live

**Comment by OfekShilon** [comment]
> this is now live

@mattgodbolt Sure it's live? If so my fix didn't solve the issue (which is surprising - I was able to reproduce locally and verify the fix).

**Comment by partouf** [comment]
it's definitely live.. I don't know enough about this to determine if this should have fixed the issue

**Comment by OfekShilon** [comment]
> it's definitely live.. I don't know enough about this to determine if this should have fixed the issue

So my fix is bad. Sorry, will take another look in the near days.

**Comment by OfekShilon** [comment]
I don't know what to say. I'm pulled to the latest code, in my local server the fix works:
image

and the live site is still broken:
image

Maybe any of you guys have access to a clang arm compiler and can try to reproduce locally? Maybe you'd have better luck than me.   Or is there a different potential diff that I'm not aware of?

**Comment by jeremy-rifkin** [comment]
Might be a caching issue?

**Comment by OfekShilon** [comment]
> Might be a caching issue?

I don't see how, I'm changing the source and am getting new instructions in the (broken) graph.

**Comment by jeremy-rifkin** [comment]
I see. I can try to take a look. Maybe there's some issue with the cfg not treating output from clang armv8 as arm?

**Comment by OfekShilon** [comment]
> I see. I can try to take a look. Maybe there's some issue with the cfg not treating output from clang armv8 as arm?

Right again! I had to add `... instructionSet=aarch64` to the compiler in my c++.local.properties and now am able to reproduce. Will return to investigating.

**Comment by OfekShilon** [comment]
Another fix implemented in PR #5646

**Pull request merged**
