### PR TITLE
Add mockup for env vars ui

### PR DESCRIPTION
**Pull request by RubenRBS**
This is not a confirmation that we will add support for them, but I wanted to test how the UI would look.

Maybe something like this:
imagen

### CODE REVIEW

**Comment by partouf** [comment]
Not the biggest fan of this. I don't really like giving this much direct control to the user and leaving it all to nsjail to hopefully take care of it.

But perhaps the most realistic version that we can provide without having to spend months on it.

We do need to consider the API carefully so that it's not a complete mess that we can't iterate on in the future.
So maybe something like (add to compile request):
```
compiler_overrides: [
{
   "env": {
      "hello": "123",
      "ABC": "123"
   }
}]
```

**Comment by mattgodbolt** [comment]
I've got no qualms about this from a security point of view: if we can't rely on nsjail to protect us there's any amount of havoc user programs can wreak on us as they're unrestricted.  Agreed re: the json request

**Comment by RubenRBS** [comment]
Sounds good, I'll implement it as soon as I can

**Comment by RubenRBS** [comment]
Been a bit busy lately, but I should have some free time to finish this at some point during this week!

**Comment by mattgodbolt** [comment]
Re-drafting for now, we can revisit when Ruben gets some more time, or if someone wants to pick this up :)

**Comment by partouf** [comment]
going to integrate this in a new branch along with https://github.com/compiler-explorer/compiler-explorer/pull/4999

**Comment by partouf** [comment]
superseded by https://github.com/compiler-explorer/compiler-explorer/pull/5001

**Pull request closed without merging**
