### PR TITLE
gcc: add old renovated versions

### LINKED ISSUE #6323: Build and install old GCC releases
Using https://github.com/jwakely/gcc/branches/all?query=renovated (and accordingly tagging these new compiler with "renovated").

### PR DESCRIPTION
**Pull request by dkm**
Add 3.4.6, 4.0.4 and 6.5.0.

fixes #6323

### CODE REVIEW

**Comment by mattgodbolt** [comment]
LMK if you need anything from me :)

**Comment by dkm** [comment]
> LMK if you need anything from me :)

Thanks :) I simply need to find a time slot to test on staging.

**Comment by dkm** [comment]
This is live :rocket:

**Comment by partouf** [comment]
now actually live

**Pull request merged**
