### PR TITLE
Bump jvms version to 18 and fix find-node path

### LINKED ISSUE #4186: [BUG]: Problem with JVM bytecode documentation
The "For more information, visit the <opcode> documentation" link currently links to JVM 16, however, Godbolt is running on Java 18.

### PR DESCRIPTION
**Pull request by matsjla**
Fixes #4186 

Updates the asmdocs generator for JVM bytecode to point to Java 18 documentation and fixes the path to the find-node script.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Looks ok to me once the tests are updated!

**Comment by matsjla** [comment]
Ah missed those, will take care of it first tomorrow morning

**Comment by gimbles** [comment]
I'll probably take a peek at this PR for a while and update it in the future [when another Java release happens] =)

**Comment by matsjla** [comment]
Should be good to go now

**Review by mattgodbolt — APPROVED** [review]

**Pull request merged**
