### PR TITLE
Add go 1.18

### PR DESCRIPTION
**Pull request by DmitriyMV**
Just like #2919 but for Go 1.18

### CODE REVIEW

**Comment by matsjla** [comment]
Needs a installer in our sister repo https://github.com/compiler-explorer/infra

**Comment by DmitriyMV** [comment]
Done in https://github.com/compiler-explorer/infra/pull/698

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
This is deploying now

**Pull request merged**
