### PR TITLE
Update Qt 6.5.3

### PR DESCRIPTION
**Pull request by jaheikk**
Change Qt 6.5.2 to Qt 6.5.3 (which is the lastest release from Qt 6.5 series)

### CODE REVIEW

**Comment by partouf** [comment]
Can you add it please instead of replacing 6.5.2?

And can you also send us a PR to add the version here https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L1711

**Comment by jaheikk** [comment]
> Can you add it please instead of replacing 6.5.2?

Sure, I was just wondering if we need several patch versions from one Qt series. I'll update this but what should be the rule for the future, how many releases we will keep here? There will be quite many Qt releases yearly...

> And can you also send us a PR to add the version here https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L1711

https://github.com/compiler-explorer/infra/pull/1105

**Comment by partouf** [comment]
> > Can you add it please instead of replacing 6.5.2?
> 
> Sure, I was just wondering if we need several patch versions from one Qt series. I'll update this but what should be the rule for the future, how many releases we will keep here? There will be quite many Qt releases yearly...

We cannot easily delete versions, and it requires a lot of storage and computing per version, so the best thing to do is to not suggest install new releases unless it's greatly different than the previous version and/or fixes some pressing bug that you also encounter on CE.

**Comment by jaheikk** [comment]
> > > Can you add it please instead of replacing 6.5.2?
> > 
> > 
> > Sure, I was just wondering if we need several patch versions from one Qt series. I'll update this but what should be the rule for the future, how many releases we will keep here? There will be quite many Qt releases yearly...
> 
> We cannot easily delete versions, and it requires a lot of storage and computing per version, so the best thing to do is to not suggest install new releases unless it's greatly different than the previous version and/or fixes some pressing bug that you also encounter on CE.

Ok, makes sense. So in that case I would do this so that we only add one version / minor release ( and so on next 6.6.0) and skip this one

**Pull request closed without merging**
