### PR TITLE
New snowball syntax

### PR DESCRIPTION
**Pull request by mauro-balades**

### CODE REVIEW

**Comment by mauro-balades** [comment]
idk why it includes other commits

**Comment by mauro-balades** [comment]
Don't merge yet, please

**Comment by jeremy-rifkin** [comment]
Hi @mauro-balades, I'll convert your PR to a draft so we don't merge it. Mark it ready for review when it's good to go.

**Comment by mauro-balades** [comment]
alr, fixed. 😌

**Comment by mauro-balades** [comment]
100% fixed now

**Comment by mattgodbolt** [comment]
Is this ready" You seem to have mostly added comments to your examples. Is the one-line fix that changes the base syntax the actual "new snowball syntax" ? Just trying to understand from the context of the PR, as you earlier said it included other commits

**Comment by mauro-balades** [comment]
Yeah, I don't know why it's past commits, GitHub is messing with me. I updated/fixed syntax highlighting and the examples. Since https://github.com/compiler-explorer/compiler-explorer/pull/5738/commits/ddea1d111ab06123a3610760c3c62826abdeffc5 basically

**Comment by mauro-balades** [comment]
If it's a problem, I can delete the repo and re-write the commits. Idk why GitHub just doesn't allow me to rebase

**Comment by mattgodbolt** [comment]
I'm cool with whatever, it'll get rebased as we merge here. I just wanted to make sure we had the right changes.

**Review by mattgodbolt — APPROVED** [review]

**Comment by mauro-balades** [comment]
Thanks! I think it looks much better with this syntax highlighting.

**Pull request merged**
