### PR TITLE
TSify the compiler args

### PR DESCRIPTION
**Pull request by mattgodbolt**
Draft for now due to pre-commit hook failure.

Somewhat straightforward port to TS otherwise...

### CODE REVIEW

**Comment by mattgodbolt** [comment]
minimal repro:
```
$ npx tsc -p ./tsconfig.frontend.json --noEmit
```
not sure what's going on.

running with `--showConfig` shows it's only looking in `static` and `types` and has an `exclude` that includes `compiler-args-app.ts`, `lib` and `test` so...perplexed

**Comment by mattgodbolt** [comment]
@jeremy-rifkin sussed it out - picking up stuff in the types. Fixing.

**Comment by mattgodbolt** [comment]
Ready for a look if anyone has a mo :)

**Review by jeremy-rifkin — APPROVED** [review]
I think all looks good to me:)

**Review by RubenRBS — APPROVED** [review]
Nice!

**Review by matsjla — APPROVED** [review]
looks great!

**Pull request merged**
