### PR TITLE
Convert executor.js to typescript

### PR DESCRIPTION
**Pull request by MarkusJx**
This migrates static/panes/executor.js to typescript.
I've also added some types to other interfaces.

See also #2981

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hi @MarkusJx - thanks so much for this contribution. Recently we're really starting to feel the pain of things not being in TS, and so we're moving a lot in that direction.

Unfortunately - and this is a big failing on my part - I didn't get to this in a timely fashion, so it has fallen behind the mainline, and so even if I reviewed it it's very much in need of bringing things up to date.

Are you still interested in pursuing this PR? If so - I will review as-is, or let you update and I can take another look.

If not: please let me know and I'll close this PR.

Either way I'll try and be better at keeping on top of the PRs. Thanks for your time!

**Comment by MarkusJx** [comment]
I can continue to work on this, just review the current status and I'll implement the changes

**Comment by mattgodbolt** [comment]
Hi Markus: sorry again for the slow response. So much has been changing as we've been reviewing and moving things around trying to get typescript going. We've had a number of site issues traced back to bad typescript typings, and so caution is our watchword.

Depending on how the other stuff goes I think we might end up teasing this into smaller PRs.

**Comment by partouf** [comment]
merged in https://github.com/compiler-explorer/compiler-explorer/pull/4605

**Pull request closed without merging**
