### PR TITLE
tsify asm-parser-beebasm

### PR DESCRIPTION
**Pull request by mattgodbolt**

### CODE REVIEW

**Review by jeremy-rifkin — COMMENTED** [review]
Woohoo 🎉

**Comment by mattgodbolt** [comment]
I'll happily accept reviews on these, but if they're simple I might just merge them after green build

**Comment by jeremy-rifkin** [comment]
Yeah that seems perfectly reasonable to me :)

**Comment by jeremy-rifkin** [comment]
This is live

**Pull request merged**
