### PR TITLE
Upgrade and audit npm packages

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
This upgrades monaco-editor from 0.32.1 to 0.34.1 which I'm hoping may fix some of the monaco related errors we've been seeing in sentry and also upgrades mocha from 8.4.0 to 10.2.0, which fixes vulnerabilities npm is complaining about:

```
minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix --force`
Will install mocha@10.2.0, which is a breaking change
node_modules/mocha/node_modules/minimatch
  mocha  5.1.0 - 9.2.1
  Depends on vulnerable versions of minimatch
  Depends on vulnerable versions of nanoid
  node_modules/mocha

nanoid  3.0.0 - 3.1.30
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix --force`
Will install mocha@10.2.0, which is a breaking change
node_modules/nanoid
```

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Ok, not surprised things broke 😄

**Comment by jeremy-rifkin** [comment]
This is esm/commonjs/module nonsense so we can deal with upgrading mocha later

**Comment by RubenRBS** [comment]
Yeah we have had some warnings about mocha, but until we properly fix all the modules stuff, we can't upgrade from our current version. Note that this also affects some other packages

**Comment by jeremy-rifkin** [comment]
I'm going to go ahead and merge, testing looks ok to me

**Comment by jeremy-rifkin** [comment]
This is now live

**Pull request merged**
