### PR TITLE
Patch highlighting color scheme setting bug

### LINKED ISSUE #4618: [BUG]: Cannot change colour scheme/themes, going to settings bugs the visuals too
### Describe the bug

There are no colour schemes/themes listed. By solely opening and closing the settings dialog it changes visual making them look buggy.

### Steps to reproduce

1. Visit godbolt.org
2. Open More dropdown
3. Open Settings
4. Try change "Line highlighting colour scheme"

### Expected behavior

There should be things to chose from

### Reproduction link

Not applicable

### Screenshots

image

Looks like the HTML isn't properly populated...
image

And sadly it makes code hard to read:
image

### Operating System

Windows 10

### Browser version

109.0.5414.75 (official) (64-bit) (cohort: Stable)

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Fixes #4618

### CODE REVIEW

**Comment by AgainPsychoX** [comment]
Will it make the list to be populated too?

**Comment by jeremy-rifkin** [comment]
Yeah, the early return was preventing the selector from being populated

**Comment by RubenRBS** [comment]
This looks like an issue old me added, thanks so much for the quick patch @jeremy-rifkin :)

**Review by RubenRBS — APPROVED** [review]

**Comment by dkm** [comment]
This is now live :rocket:

**Pull request merged**
