### PR TITLE
Support fmt 8.[01].1 (#3438)

### PR DESCRIPTION
**Pull request by m8mble**
Following `1e3da6eefdc2a6bfaca14af340971a8159557105` as a blueprint.
Verified mp-units uses fmt v8.1.1 in trunk.

Addresses issue #3438.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hi! This also needs a PR in our sister repo https://github.com/compiler-explorer/infra/

I'll do so now and link back here - for future reference we have a few docs in https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
Now live: thanks!

**Comment by m8mble** [comment]
Thanks for your help on this PR and also all your great work on CE!

**Pull request merged**
