### PR TITLE
GCC 8.4 and 8.5

### PR DESCRIPTION
**Pull request by ojeda**
GCC 8.5 was just released, 8.4 was released a couple months ago.

https://github.com/compiler-explorer/infra/pull/519

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thank you for this, and being patient with our frustrating configuration files!

**Comment by ojeda** [comment]
You're very welcome! But yeah, a templating script would be nice to automate GCC, LLVM and a few other folks :)

**Comment by mattgodbolt** [comment]
This is now lice :)

**Comment by mattgodbolt** [comment]
er, live!

**Pull request merged**
