### PR TITLE
Add libuv to C & C++ libraries

### PR DESCRIPTION
**Pull request by jtbandes**
Not sure if I'm doing this right — feedback welcome! How do I test this locally?
Depends on https://github.com/compiler-explorer/infra/pull/350.

### CODE REVIEW

**Comment by partouf** [comment]
Hi, we can get this to work with at last the headerfiles, but the linking support is still in the works - so you'll have to wait for that for execution and binary mode.

**Comment by partouf** [comment]
Although I guess we can use the shared library and build it manually for x86 and x86-64, but I prefer to not have more of those exceptions (currently its just openssl and cs50 that use the shared library setup).

**Comment by jtbandes** [comment]
Ok, thanks! Where can I follow the status of the linking support? Is any help needed?

**Comment by RabsRincon** [comment]
Library linking is being track on #1932 :)

**Pull request merged**
