### PR TITLE
Add Zig cc as a C compiler

### PR DESCRIPTION
**Pull request by RubenRBS**
This commit is currently untested- I have no way to do it locally
 (Even though installing Zig is awesomely simple!), so it might be pretty broken.

I have no idea if setting the exe like this even works! I'll find out once I test it on beta :)

Releated issue: #2427

### CODE REVIEW

**Comment by RubenRBS** [comment]
Ran out of time to test this today. Oops

**Comment by partouf** [comment]
The exe's "cc" part definitely does not belong there, it won't pass the fs.stat checks etc. Have you tried it as part of .options?

**Comment by partouf** [comment]
lgtm, I can test later this week if noone gets around to it before me

**Comment by RubenRBS** [comment]
`.options` is concatenated after the options for filters, so that the cc is not properly recognized. 
I thought that we could either use the `compiler-wrapper` stuff, or add a `.prependOptions` (or similar) key.

¿Any thoughts?

**Comment by partouf** [comment]
> `.options` is concatenated after the options for filters, so that the cc is not properly recognized.
> I thought that we could either use the `compiler-wrapper` stuff, or add a `.prependOptions` (or similar) key.
> 
> ¿Any thoughts?

hmm ok, doesn't sound consistent with other compilers.. should zig.js not be changed for this to put .options in the right spot?

**Comment by partouf** [comment]
Doesn't easily work with `compilerType=zig` either - I think we need to make a `zigcc` mixing things from clang and zig or something.

**Comment by partouf** [comment]
* [ ] trunk - asm - not working
* [x] trunk - binary
* [x] trunk - run

* [ ] 0.7.1 - asm
* [x] 0.7.1 - binary
* [x] 0.7.1 - run

* [ ] 0.7.0 - asm
* [x] 0.7.0 - binary
* [x] 0.7.0 - run

* [x] 0.6.0 - asm
* [x] 0.6.0 - binary
* [x] 0.6.0 - run

**Comment by partouf** [comment]
I'm not sure why normal asm mode isn't working for >=0.7.0

Also pointed out in https://github.com/ziglang/zig/issues/8153

Will wait until there's response for a workaround, otherwise I'll force binary mode on those compilers.

**Comment by partouf** [comment]
Using binary mode for all versions except 0.6.0 because the zig repo doesn't seem to be moving on this

**Comment by partouf** [comment]
this is now live

**Comment by kassane** [comment]
Cool! Even without solving the compiler problem, it works well.
So, the same would happen with `zig c++`.

**Pull request merged**
