### PR TITLE
New C3 compiler options

### PR DESCRIPTION
**Pull request by aliaegik**
Regarding the issue discussed in https://github.com/compiler-explorer/compiler-explorer/pull/5086#issuecomment-1578715708

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Hey @aliaegik, I haven't tested them locally but I'll trust they work. If you could run a quick npm format to fix the line length issue that'd be great!

**Comment by aliaegik** [comment]
> Hey @aliaegik, I haven't tested them locally but I'll trust they work. If you could run a quick npm format to fix the line length issue that'd be great!

Hi. I fixed the length issue. But in order for these options to work, the new compiler should be first installed (I made a PR in Infra before).

**Comment by mattgodbolt** [comment]
Hi @aliaegik - I've installed the "new" v0.4, and so I will trust that contains the command-line flags needed (at first cursory test it appeared to)

**Comment by mattgodbolt** [comment]
This is now live.

**Comment by aliaegik** [comment]
> Hi @aliaegik - I've installed the "new" v0.4, and so I will trust that contains the command-line flags needed (at first cursory test it appeared to)

Hello. Thank you very much.

**Pull request merged**
