### PR TITLE
Add python 3.10 and make it the default.

### PR DESCRIPTION
**Pull request by mCodingLLC**
Python 3.10.0 was released as the next stable version today.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
This is now live, thank you!

**Comment by mattgodbolt** [comment]
I spoke too soon, darn!

**Comment by mattgodbolt** [comment]
Will investigate tomorrow, sorry!

**Comment by mCodingLLC** [comment]
I tried to mimic the two commits for adding 3.9 support, one in this repo and one in infra (related PR: https://github.com/compiler-explorer/infra/pull/603). I've noticed there is a file python.defaults.properties but I didn't modify it since 3.9 appears to be working even though it doesn't appear in that file. Perhaps that could be related.

**Comment by apmorton** [comment]
This should be fixed, although not sure if it's been deployed to prod yet.

919a50ffd3aa072715e7b3b10985395fb3102214

The issue is python310 wasn't added to the group in your PR and I didn't notice when reviewing.

**Comment by mattgodbolt** [comment]
Just deployed now! Yay!

**Pull request merged**
