### PR TITLE
Add RGA 2.9

### PR DESCRIPTION
**Pull request by partouf**
Reguires https://github.com/compiler-explorer/infra/pull/1277

### CODE REVIEW

**Comment by partouf** [comment]
On discord we've been discussing that 2.9.1 might be a version where we can make RGA independent of DXC, but with 2.9.0 we're not that far yet, I think. (hashtag not an expert)

So for now this will have to do. But not sure about which DXC version best to use.

**Comment by mattgodbolt** [comment]
Any reason not to merge this anyway and have a look ? :)

**Comment by partouf** [comment]
RGA 2.0 says:

```
/opt/compiler-explorer/rga-2.9.0.25/rga

Target GPU detected:

gfx1030 (RDNA2)
	AMD Radeon PRO W6800
	AMD Radeon Pro V620
	AMD Radeon RX 6800
	AMD Radeon RX 6800 XT
	AMD Radeon RX 6900 XT
	AMD Radeon RX 6950 XT
	AMD Radeon(TM) Graphics

Building for gfx1030... failed.
ERROR: Result::ErrorInvalidShader: File output.spv.txt has an unknown extension; try -help to list supported input formats
Error: ERROR: 
=====  AMDLLPC FAILED  =====


RGA didn't emit expected ISA output.
Compiler returned: 0
```

(`-help` doesn't work so don't know what I can do to debug)

**Comment by partouf** [comment]
now live if anyone wants to see what its about

**Pull request merged**
