### PR TITLE
Update mlir.ts for issue #5902

### PR DESCRIPTION
**Pull request by Sameeranjoshi**
Fix for 
https://github.com/compiler-explorer/compiler-explorer/issues/5092

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Do you want to just enable the toggle or actually turn off filtering here more thoroughly? I haven't used mlir but as far as I've read it sounds like lines like `#map = affine_map<() -> (64)>` are actually important and not just comments or metadata.

It should be possible to change what is considered to be a comment by providing a custom `processAsm`.

**Comment by Sameeranjoshi** [comment]
I don't know the low level details of CE, I just followed what was mentioned in https://github.com/compiler-explorer/compiler-explorer/issues/5092#issuecomment-1574056122
If I did wrong code, please discard this and if some expert could push a patch to fix that would be great.
Thanks

**Comment by Sameeranjoshi** [comment]
Yes the lines are important.

**Comment by jeremy-rifkin** [comment]
If there is no scenario where it would make sense to filter these lines out I think it'd make sense to find another solution. I'd be happy to poke around and add something onto this pr to address this or I'd be happy to chat on discord about how to go about doing this

**Comment by mattgodbolt** [comment]
Thanks @jeremy-rifkin - would appreciate your help in doing this in an appropriate way: cheers!

**Comment by jeremy-rifkin** [comment]
I think this should work

**Comment by jeremy-rifkin** [comment]
I don't have mlir locally to test but I'm going to go ahead and merge this

**Pull request merged**
