### PR TITLE
Make tabbed panes active when reveals are sent

### LINKED ISSUE #3645: [BUG]: "Scroll to source" from ASM view doesn't switch active editor
### Describe the bug

The right click --> "Scroll to source" option doesn't swap the active editor view

### Steps to reproduce

Visit the reproducible link: https://godbolt.org/z/7e5ceqrPr

Select the ASM view for square1 or square2 and right click, select "Scroll to source"

Notice that the editor tab hasn't been switched

### Expected behavior

Editor tab should switch to the correct one selected from the ASM

### Reproduction link

https://godbolt.org/z/7e5ceqrPr

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by RubenRBS**
Closes #3645

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Now live - thanks @RubenRBS

**Comment by partouf** [comment]
Was this actually tested?

It makes the tab highlighted, but doesn't actually swap to the tab

**Comment by partouf** [comment]
The way to do it that works is https://github.com/compiler-explorer/compiler-explorer/blob/6512ad13bc6a8d7c5fa6715baf460efb88f93c47/static/hub.ts#L360

**Comment by partouf** [comment]
is live but should be fixed

**Pull request merged**
