### PR TITLE
Don't try to build and execute if the initial build failed

### LINKED ISSUE #4147: [BUG]: Failure to compile should prevent execution of code
### Describe the bug

With code execution enabled, an ill-formed program will fail to compile. This does not prevent the execution step from running, which attempts to recompile the code, most likely resulting in another failure to compile.

### Steps to reproduce

1. Visit https://compiler-explorer.com/z/TsWEnf8Pq, with source:
```C++
int;
```
2. Notice that the errors are doubled, once for each step, as indicated by `ASM generation compiler returned:` and `Execution build compiler returned:`:
```
<source>:1:1: error: declaration does not declare anything [-fpermissive]
    1 | int;
      | ^~~
ASM generation compiler returned: 1
<source>:1:1: error: declaration does not declare anything [-fpermissive]
    1 | int;
      | ^~~
Execution build compiler returned: 1
```

### Expected behavior

Failure to compile prevents the execution step from running.

### Reproduction link

https://compiler-explorer.com/z/TsWEnf8Pq

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Resolves #4147

### CODE REVIEW

**Comment by partouf** [comment]
I'm not a big fan of this, there's no guarantee that compilers always return 0 when things succeed, nor is there a guarantee that an executable build will always fail if a single source compilation failed

**Comment by jeremy-rifkin** [comment]
Good points and valid concerns. I have a very hard time imagining the executable build succeeding when the single-source compilation fails, but I know there's bound to be an odd-ball compiler or two. Not returning zero on success seems like a more pressing issue, though I don't know of any compilers right off hand that would do that.

**Comment by partouf** [comment]
> Good points and valid concerns. I have a very hard time imagining the executable build succeeding when the single-source compilation fails, but I know there's bound to be an odd-ball compiler or two. Not returning zero on success seems like a more pressing issue, though I don't know of any compilers right off hand that would do that.

We don't only just run C/C++ compilers, there's more languages and compilers to think of when doing this. We could always fix it afterwards when things break, but I'd rather just not break anything in the first place

**Comment by JohelEGP** [comment]
See also the thread starting at <https://cpplang.slack.com/archives/C28NX7947/p1684198154781779>
where @mattgodbolt suggests what could be done:
> [...] currently it's the case we run the two compiles in parallel. We should probably abort the second if it's doomed to fail

**Comment by jeremy-rifkin** [comment]
> See also the thread starting at https://cpplang.slack.com/archives/C28NX7947/p1684198154781779 where @mattgodbolt suggests what could be done:
> 
> > [...] currently it's the case we run the two compiles in parallel. We should probably abort the second if it's doomed to fail

I think the two compilations are actually not done in parallel at the moment, however that is something we could re-introduce.

> We don't only just run C/C++ compilers, there's more languages and compilers to think of when doing this. We could always fix it afterwards when things break, but I'd rather just not break anything in the first place

Very true. I did some looking through the codebase though and found we have precedent for checking the return code:

https://github.com/compiler-explorer/compiler-explorer/blob/64d68eb0fe92e54af75e7c4cdc791822a1429487/lib/base-compiler.ts#L2179-L2181

If we find a compiler that doesn't not use 0 to indicate success we'll probably want to make an overridable `checkSucceeded(asmResult)` method. But for now things seem fine.
Would you be more amenable to this change given this precedent @partouf?

**Comment by partouf** [comment]
> > We don't only just run C/C++ compilers, there's more languages and compilers to think of when doing this. We could always fix it afterwards when things break, but I'd rather just not break anything in the first place
> 
> Very true. I did some looking through the codebase though and found we have precedent for checking the return code:
> 
> https://github.com/compiler-explorer/compiler-explorer/blob/64d68eb0fe92e54af75e7c4cdc791822a1429487/lib/base-compiler.ts#L2179-L2181
> 
> If we find a compiler that doesn't not use 0 to indicate success we'll probably want to make an overridable `checkSucceeded(asmResult)` method. But for now things seem fine. Would you be more amenable to this change given this precedent @partouf?

I don't want to hold anyone back, I'm just warning you I'm not going to fix any bugs that might come from this.

**Comment by jeremy-rifkin** [comment]
Sounds good. Also happy to revert and re-evaluate if it's not a clear win or if things break.

**Review by mattgodbolt — APPROVED** [review]
I'm in favour, and 100% ack partouf's concerns and that partouf won't be fixing issues :) you can all blame me :)

**Comment by jeremy-rifkin** [comment]
I'll go ahead and merge this and we can deal with any ramifications as they come up 🐏

**Pull request merged**
