### PR TITLE
Add DXC 2212, 2306 and 2308 releases

### PR DESCRIPTION
**Pull request by llvm-beanz**
This change adds the following DXC releases:
* 1.7.2212
* 1.7.2308
* 1.8.2306-preview

### CODE REVIEW

**Review by mattgodbolt — CHANGES_REQUESTED** [review]
Can you fix the config issues the CI picker up on, please.

**Comment by mattgodbolt** [comment]
Those new compilers need to be listed in the "list of compilers" (which is what the CI system/tests are picking up on). Also, unfortunately these failed installation: https://github.com/compiler-explorer/infra/pull/1148 has the defails, we're getting 404s for those.

**Comment by mattgodbolt** [comment]
Ohhhh! I need to  build them _doh_

**Comment by mattgodbolt** [comment]
the preview failed to build too (see https://github.com/compiler-explorer/infra/issues/1163 for details); I have no bandwidth to look into this; so we can disable for now or else if you can help debug the build failure that'd be great.

**Comment by llvm-beanz** [comment]
I posted a PR to fix the misc-builder. An alternate approach we could take for the newer DXC builds would be to pull the binaries from GitHub. We didn't include Linux builds until recently (and the first one or two are basically unusable). I _think_ something like this could work to move the latest builds to pull from the GitHub releases:

```
diff --git a/bin/yaml/hlsl.yaml b/bin/yaml/hlsl.yaml
index fb320088..5008cea1 100644
--- a/bin/yaml/hlsl.yaml
+++ b/bin/yaml/hlsl.yaml
@@ -8,11 +8,22 @@ compilers:
         - trunk
   hlsl:
     dxc:
+      type: tarballs
+      url: https://github.com/microsoft/DirectXShaderCompiler/releases/download/{name}/linux_{build}.{arch}.tar.gz
+      compression: gz
+      check_exe: bin/dxc --version
+      dir: dxc-${name}
+      targets:
+        - name: "1.8.2306-preview"
+          build: "preview_2023_06_21"
+          arch: "x86_64"
+        - name: "1.7.2308"
+          build: "2023_08_14"
+          arch: "x86_64"
+    dxc-built:
       type: s3tarballs
       check_exe: bin/dxc --version
       targets:
-        - "1.8.2306-preview"
-        - "1.7.2308"
         - "1.7.2212"
         - "1.7.2207"
         - "1.6.2112"
```

**Comment by mattgodbolt** [comment]
Trying a new build of the preview now: https://github.com/compiler-explorer/infra/actions/runs/6963684112/job/19081588901

**Comment by partouf** [comment]
All of these have been built and installed, really, so I see no need to delay merging this

**Pull request merged**
