### PR TITLE
mp-units now use gsl-lite and links with fmt

### PR DESCRIPTION
**Pull request by mpusz**
Resolves mpusz/units#165

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
This is now live.

**Comment by mpusz** [comment]
It seems that the solution for fmt does not work :-(
https://godbolt.org/z/3zo37r

Is there a way to link with fmt lib?

**Comment by mattgodbolt** [comment]
Aww :( @partouf do you have any wisdom on how best to achieve "we need to link with fmt" -- I'm sorry to ask but I know you probably know the answer off the top of your head whereas I'd have to dig a bit!

**Comment by partouf** [comment]
The staticliblink method only works if it's part of your library. There is a different method to automatically load dependencies, but I don't think I've tested it recently. Will look into it.

**Comment by mattgodbolt** [comment]
A nasty hack is to `-DFMT_HEADER_ONLY` (but it takes a _very_ long time to compile)... and it won't stop the `-lfmtd` from being supplied on the command line :(

**Comment by mattgodbolt** [comment]
Thanks @partouf. Linking across multiple libraries is troublesome, as you can imagine @mpusz!

**Comment by partouf** [comment]
I think it's .dependencies=fmtd instead of .staticliblink

**Comment by partouf** [comment]
Quick scan over the code; I think .dependencies might not work either for the libraries stored on the conan environment. But will test and maybe make a fix.

**Comment by partouf** [comment]
Just realizing it can't work in general, because which version of fmt is it supposed to load? And what if the user then also has a different version selected?

It's nice to have things work out of the box, but I'm afraid a comment on the fmt requirement and having to select an fmt version in the library selection will have to do.

**Comment by partouf** [comment]
Changed in this way https://github.com/compiler-explorer/compiler-explorer/commit/1395435bfdc7a925286b17b793527c830f334dc5

**Comment by mpusz** [comment]
Thanks!

**Comment by partouf** [comment]
Now live

**Pull request merged**
