### PR TITLE
Add check for result of regex being null

### PR DESCRIPTION
**Pull request by gautam1168**
Fix for issue https://github.com/compiler-explorer/compiler-explorer/issues/4455

### CODE REVIEW

**Comment by matsjla** [comment]
Thanks for the patch!

Do you know if the original bug happens to still exist? Unless there is something faulty in our typing (quite possible!) I don't see how `m` can be a falsy value (empty array is truthy)

**Comment by gautam1168** [comment]
@matsjla I do not know if the original bug exists. However regular expression execution can return null values:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec

**Review by apmorton — CHANGES_REQUESTED** [review]
This patch is not appropriate since the rison module was converted to typescript. `m` can never be falsey since it is assigned through `unwrap` which will raise an exception if the return from the regex is null.

I don't know if the current behavior is correct, but this patch will not fix it.

**Comment by gautam1168** [comment]
Yeah I see the `unwrap` throws an error. I can change the PR to just add the types as @matsjla has requested or I could close it. Let me know.

**Comment by mattgodbolt** [comment]
If we don't have any strong evidence the types are wrong (other than the smoking gun of the error we saw once...) then I think probably we close this? I hate to get rid of a possible fix but either we trust our types or we don't

**Comment by gautam1168** [comment]
Yes I think it is safe to close it. I will make the PR again if this issue props up again. Looking at the unwrap function I don't see how it could have happened.

**Comment by partouf** [comment]
Thanks for the effort either way

**Comment by gautam1168** [comment]
I have deleted the branch so the ui is not cluttered with unused branches. I'm not sure if you keep around branches that get the pull requests resolved or not.

**Pull request closed without merging**
