### PR TITLE
Guard against missing buildResult in executor response

### PR DESCRIPTION
**Pull request by RubenRBS**
For #4030 but does not close it, needs more investigation

### CODE REVIEW

**Comment by RubenRBS** [comment]
Might be worth to take a look into how the output pane handles this

**Review by mattgodbolt — APPROVED** [review]
Defensive stuff is cool for tactical fixes: thanks! Ideally we'd work out what's going wrong as you say.

**Review by matsjla — APPROVED** [review]

**Comment by partouf** [comment]
Rather fix this sooner than later. Will investigate what's needed before tomorrow.

**Comment by partouf** [comment]
This is just the correct solution. This function was added in the editor only last month to support highlighting lines/errors. In executor.js this `if (result.buildResult)` is used throughout. That's just the way it is.

**Pull request merged**
