### PR TITLE
Add mlir-translate

### PR DESCRIPTION
**Pull request by harishch4**

### CODE REVIEW

**Review by junlarsen — COMMENTED** [review]
Nice, do you think it'd make sense to add mlir-translate for 17.0.1 and 18.1.0 as well?

Also, is there any significant difference between this and #6355

**Comment by harishch4** [comment]
> Nice, do you think it'd make sense to add mlir-translate for 17.0.1 and 18.1.0 as well?

If those versions are already installed, it does make sense. However, since "trunk" is being added, this should be fine, I guess.

> Also, is there any significant difference between this and #6355?

I wasn't aware that there's already a patch available. It looks almost similar to mine, but it's failing CI for some reason.

**Review by mattgodbolt — APPROVED** [review]
LGTM: thank you

**Comment by mattgodbolt** [comment]
This is rolling out now

**Pull request merged**
