### PR TITLE
urls werent being expanded in tree/ide mode

### PR DESCRIPTION
**Pull request by partouf**
The #include <url> sources weren't being expanded when compiling via Tree/IDE mode.

Because it's an async process, I've used Promise.all() to wait to resolve all the files first before starting the compilation.

### CODE REVIEW

**Comment by partouf** [comment]
I think I know why I didn't do this before; when you already have access to multiple files, why need the internet. You can just load a github repo, etc.

But there's really no reason why the user shouldn't just get whatever they expected in the normal mode.

I don't know. I'll leave it to someone else to decide if this is fine.

**Comment by RubenRBS** [comment]
I do think this is a valuable thing to have, yes!

**Comment by partouf** [comment]
example https://godbolt.org/z/d3rW8611M

**Comment by partouf** [comment]
(this is now live)

**Pull request merged**
