### PR TITLE
Install LLVM/Clang 13

### PR DESCRIPTION
**Pull request by supergrecko**
LLVM and Clang 13.0.0 releases

Infra: https://github.com/compiler-explorer/infra/pull/599

### CODE REVIEW

**Comment by ojeda** [comment]
Hmm... `13-final` was tagged a few hours ago, and LLVM 13 is not released yet.

**Comment by supergrecko** [comment]
LLVM 13 or llvmorg-13.0.0 was actually tagged four days ago https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.0

**Comment by ojeda** [comment]
The tagging message came today: https://lists.llvm.org/pipermail/llvm-dev/2021-October/153082.html And the actual announcement email has not been sent yet, either.

I am not sure of the precise release process, maybe Tom Stellard creates the tag in the repo sooner or he didn't have time to send the message on Friday. In any case, I think it is better to wait for the official announcements.

**Comment by supergrecko** [comment]
> The tagging message came a few hours ago (https://lists.llvm.org/pipermail/llvm-dev/2021-October/153082.html). And the release announcement email has not been sent yet (https://lists.llvm.org/pipermail/llvm-announce/).
> 
> I am not sure of the precise release process, maybe Tom Stellard creates the tag in the repository sooner or perhaps he did not have time on Friday. Maybe it has to do with the testers process too.
> 
> In any case, it is better to wait for the official announcements.

Apologies, I was notified through GitHub of the release and assumed it was good to go.

**Comment by apmorton** [comment]
I'm definitively in the "once a release is tagged in the canonical format and pushed to the official source control repo it's fair game" camp on this one.

If llvm is force-pushing tags that's somewhat unforgivable.

**Comment by ojeda** [comment]
> Apologies, I was notified through GitHub of the release and assumed it was good to go.

No worries!

> I'm definitively in the "once a release is tagged in the canonical format and pushed to the official source control repo it's fair game" camp on this one.
> 
> If llvm is force-pushing tags that's somewhat unforgivable.

They could publish a different name for the release, though. Even tag renames aren't unheard of in native Git projects like the kernel.

Assuming no extra information, official announcements are what take precedence in my view. Of course, if we know they promise to use always that tag, then it can even be good doing it as soon as possible, e.g. so that third-party tooling like CE has support at the time the announcement is made. But I would ask if that is OK with them out of deference even if we knew.

**Pull request merged**
