### PR TITLE
Add lang labeler filters

### PR DESCRIPTION
**Pull request by RubenRBS**
This makes the labeler action a bit more useful

Made it into a PR so someone can review, just in case I misplaced any compiler :)

### CODE REVIEW

**Comment by mattgodbolt** [comment]
I have an embarrassing admission to make... I have no idea what this is for! :blush: - I've seen the "labeler" action in the GH actions pane...but...what's the "one line, explain it to me like I'm a 5 year old (or an old C++ developer)" version?

**Comment by RubenRBS** [comment]
Automagically adds labels based on what files a PR edits 😬

**Comment by mattgodbolt** [comment]
Genius!

**Review by mattgodbolt — APPROVED** [review]
Looks great! thanks mate

**Pull request merged**
