### PR TITLE
Add standalone asm cleaner

### PR DESCRIPTION
**Pull request by jyn514**
- adds a node script which runs asm-parser on stdin
- currently uses default parameters from base-compiler
- TODO: make parameters configurable with CLI flags (use https://www.npmjs.com/package/minimist ?)
- TODO: add unit tests

Closes https://github.com/mattgodbolt/compiler-explorer/issues/1242

### CODE REVIEW

**Comment by jyn514** [comment]
I found some existing tests in `test/filter-tests.js`, I can modify those to test this as well.

**Comment by jyn514** [comment]
Not sure if I'm doing these tests right, the standalone script *always* uses the default filters so it should have different output at least some of the time.

**Comment by RabsRincon** [comment]
Hi! Sorry for taking so long to review the PR, it's been a busy weekend.

The idea behind the changes sounds really good, and the implementation (Thanks for improving the tests!) looks great. I feel like a way to call the script from either `make` or `yarn` is missing, but I don't know how necessary that would be. Do you think it is something we might want?
:)

**Comment by jyn514** [comment]
Would `/etc/scripts` be a better place?

I'm not sure why we'd need to call this from the makefile, unless you want to make this part of the build? Since it's executable you should be able to call this like any other script, I tested it and it doesn't depend on the current directory. I was personally planning to use this to clean up `gdb` output for my local debugging which I think this does pretty well.

Thanks for the feedback!

**Comment by mattgodbolt** [comment]
I like the look of this! I think having it in `etc/scripts` might be a better place. As for a `make` target, it might be cool to:

* support command-line parameters
* maybe have a `make` target or some kind of (npm? yarn?) way of publishing a more "sealed" solution. I know it's possible to `npm install` tools globally, and making something that can be easily used by others would be ace.

I don't know how best to do this, but maybe even a separate package entirely that can be `npm installed` that uses `compiler-explorer` as a dependency that we can publish on `npm` ?

I'm pretty cool with how it is now though :)

**Comment by jyn514** [comment]
If you want an NPM package it might make sense to go the other way: a self-contained package that compiler-explorer depends upon. That way people who want to use it don't have to install a website along with the script.
I imagine that's a lot more work than the other way, but I think it's a cleaner approach. If I get `make asm-cleaner` to output a standalone, that would be most of the work I think.

**Comment by jyn514** [comment]
It looks like the only dependencies are `lib/asm-parser`, `lib/asmregex`, and `lib/utils`.

It also depends on `lib/base-compiler.js:getDefaultFilters`, which we could probably factor out into a configuration file or something.

**Comment by jyn514** [comment]
Something like this: https://github.com/jyn514/asm-file-cleaner

I need to change compiler-explorer around so there's not duplicated code though.

**Comment by mattgodbolt** [comment]
@jyn514 I was hoping not to copy the CE code, as it will get out of date. I was thinking more:

* CE publishes itself to `npm` as a library.
* Some other tool depends on it and provides it with a nice front-end to the library.

That might be overkill: perhaps we should just support the asm cleaner directly in CE and publish it from here :) Would mean a bit more work on our side to handle the version bumping in `package.json` and all that (we can make a script to do it though).

**Comment by mattgodbolt** [comment]
It looks like github now can help us with npm publishing; I'll explore whether we can get us published by travis somehow on every build, which would open the door to "ce as a library" for this.

**Comment by mattgodbolt** [comment]
Mind you; that would make the package depend on many unnecessary things....perhaps it's worth a bit of a rethink to get this working. Extracting and improving the ASM parsing has been long on the todo-list anyway (even just internally).

**Comment by jyn514** [comment]
Just to check - you still want to publish this as part of compiler-explorer as a whole, not as a standalone library? I think the second makes more sense but I'm willing to go with the first option if that's what you prefer.

**Comment by mattgodbolt** [comment]
Hmm, I guess you're right. I don't know :)  I'm mildly against separating it out as it'll make changing it down the line much more difficult. I've never found an ergonomic development process when you're editing a project in tandem with a library it needs; but I can learn :)

**Comment by mattgodbolt** [comment]
I should have added: but I'm starting to warm to the idea if we can come up with a decent interface between the library and the users.

**Comment by jyn514** [comment]
> I've never found an ergonomic development process when you're editing a project in tandem with a library it needs; but I can learn :)

Maybe it could still be part of the same git repository, but published separately? That way it's easy to modify but you still don't have to pull in all of CE to use it.

I haven't looked at the API in a while so I'll leave that bit up to you, I think it would be nice to make the filters separate from the whole `base-compiler` though.

Thanks for working with me on this :)

**Comment by mattgodbolt** [comment]
No worries; sorry for the radio silence forever on this! I can't promise much time but I'd be up for publishing a subset of this repo with a separate `npm` package and dependenceis (so long as we have some tests?) even as just a starting point. But really, anything :)

**Comment by jyn514** [comment]
Well this is odd, `npx mocha --recursive` works fine but `npm run test` fails.

```
$ npm run test
// every filter test fails with the following error:
  69) filters-cases/arm-moose.asm:
     AssertionError: filters-cases/arm-moose.asm case error: expected '' to deeply equal { Object (asm) }
      at Context.<anonymous> (test/filter-tests.js:88:28)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
$ npx mocha --recursive
  437 passing (1s)
```

**Comment by jyn514** [comment]
Oh I think this has something to do with `getStdin` behaving differently in a TTY context. I can probably just use `fs.readToString` instead.

**Comment by jyn514** [comment]
How does it sound to merge this as is (with a standalone script in `/etc/scripts` but no npm package) and then make a follow-up PR to turn `asm-cleaner` into a library?

I'm having a bit of trouble with the test suite: when I run `npm test` or `mocha --recursive` alone all the tests pass, but if I run `npx nyc --reporter=lcov mocha --recursive` on top I suddenly get a slew of test errors that it expects JS objects and not strings. Is there a separate runner for coverage than for normal unit tests?

**Comment by mattgodbolt** [comment]
> How does it sound to merge this as is (with a standalone script in `/etc/scripts` but no npm package) and then make a follow-up PR to turn `asm-cleaner` into a library?

Sounds great!

> I'm having a bit of trouble with the test suite: when I run ~`npm test`~ or `mocha --recursive` alone all the tests pass, but if I run `npx nyc --reporter=lcov mocha --recursive` on top I suddenly get a slew of test errors that it expects JS objects and not strings. Is there a separate runner for coverage than for normal unit tests?

I don't know much about `npx` -- `npm run ci-test` is what the CI does and trying it locally just worked for me. I'd happily accept patches to fix ehaviour to make it more standard node packagey: I'm an oldschool Makefile person by default! :)

> Edit: this was the same issue as before that `npm test` behaves differently than `mocha --recursive`. Not sure what's going on.

I'm afraid I'm not sure. If the `npm run ci-test` works for you (or just `make test` and `make lint`) then all's good. If there's a way to make it more standard, then we can make a follow up issue (and PR) to track this.

**Comment by partouf** [comment]
I also noticed the pre-commit hook vs npm run test / link catches different things, it's rather annoying, but haven't actually looked into it. Probably should make those equal.

**Comment by mattgodbolt** [comment]
> I also noticed the pre-commit hook vs npm run test / link catches different things, it's rather annoying, but haven't actually looked into it. Probably should make those equal.

Oh! Yes! Absolutely :)

**Comment by mattgodbolt** [comment]
I'm pretty sure this is going to be obviated by @partouf 's #2199 work in https://github.com/compiler-explorer/asm-parser. That would give a single executable that does this work. As this PR is seemingly out of date and is in conflict, would it still be profitable to merge this, or shall we defer to the new asm parser?

**Comment by jyn514** [comment]
I think it makes sense to use the new rewrite. Sorry for taking so long on this!

**Pull request closed without merging**
