### PR TITLE
Add missing data definition directives (fixes #4275)

### LINKED ISSUE #4275: [BUG]: Directives-Filter removes .half and .dword directives
### Describe the bug

Usually directives such as .byte, .word, etc. are not filtered, even if the directives-filter is set. This seems not to work for .half and .dword directives as created by rv64gc for example.

See this example: https://godbolt.org/z/dr8Pdc3s7

For the input:
```
extern const char test_char = 42;
extern const short test_short = 42;
extern const int test_int = 42;
extern const long test_long = 42;
extern const long long test_longlong = 42;
```

the generated output with the directives filter enabled on rv64gc gcc12.2.0 is:
```
test_char:
        .byte   42
test_short:
test_int:
        .word   42
test_long:
test_longlong:
```

### Steps to reproduce

1. Visit godbolt.org
2. Select C++
3. Select RISC-V rv64 gcc 12.2.0 or loongarch64 gcc 12.2.0 for example (or any other compiler that generated those directives)
4. Paste into the source window: `extern const int test_int = 42;`
5. Make sure the directives filter is enabled
6. View the generated and filtered assembly output

### Expected behavior

Directives such as .dword and .half are not filtered in alignment with similar directives such as .word, .byte, etc.

### Reproduction link

https://godbolt.org/z/dr8Pdc3s7

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by Bueddl**

### CODE REVIEW

**Comment by RubenRBS** [comment]
Thanks for taking the time to look into the code yourself and submitting a bugfix, we really appreciate it :)

**Comment by RubenRBS** [comment]
Can you fix the unicorn warning in the failing test? Also, this probably changes some of the test results for asm parsing

**Comment by partouf** [comment]
Not needed to fix this problem, so just a note to myself that this needs to be added to https://github.com/compiler-explorer/asm-parser/blob/main/src/utils/regexes.hpp#L17

**Comment by Bueddl** [comment]
> Can you fix the unicorn warning in the failing test? Also, this probably changes some of the test results for asm parsing

Thanks! Will have a look at this (I ran the checks but obviously overlooked that)!

**Comment by partouf** [comment]
this is now live

**Pull request merged**
