### PR TITLE
Approval tests

### PR DESCRIPTION
**Pull request by mattgodbolt**
Move to approvals to do the approval-style tests we had in filters-cases.

You can configure which diff viewer it uses with ~/.approvalsConfig

Pros:
* standard diff-based thing
* easy to "bless" all the differences (see `forceApproveAll`)
* fairly standard pattern
* forces a comprehensive all permutations and combinations vs
  the ad hoc subset we picked before
Cons:
* really wants to name the files *.approved.txt
* spawns _all the diffs_ at once and so an overarching change
  can crush your computer with diff (e.g. if you use `meld` like
  I do, you end up with 100+ diffs opening)
* comprehensive testing means this takes longer, now ~16s to do
  all these tests

Arguably some of these diffs are just too big, and maybe we shouldn't even do them all. Thoughts welcomed!

### CODE REVIEW

**Comment by partouf** [comment]
ill need to test this in combination with my asmparser branches and see how it turns out with a lot of changes on my setup

**Comment by mattgodbolt** [comment]
Got it! We can leave it parked for as long as we need, or even just close it. If we're happy the code hasn't changed we can do a one off "all are good" run in the other branch. It was just an evening's "fun"

**Comment by partouf** [comment]
Setting `reporters: ['donothing']` in `optionsOverride` helps to not get overwhelmed, but then the question is; how to start a diff after the testing while there are 2 files.

I think for me it's probably setting `forceApproveAll` so I can look at something in the default diff of my IDE.

**Comment by mattgodbolt** [comment]
Right :( I think I'll probably close this PR unmerged; the default case seems unhelpful - we either get 1,000 windows pop up and kill our computers, or we have to "approve all" and use an external diff tool to check...

I wonder if we're "doing it wrong" - @claremacrae might be able to offer advice?

**Comment by claremacrae** [comment]
Hi Matt, thanks for pinging me... Don't close it yet! I'm looking at the changes, and will put some suggestions together...

I haven't used Approval  Tests for JS before, so I'm interested to see it in action. The concepts should be the same as in other languages, anyway...

**Comment by mattgodbolt** [comment]
Thanks Clare! Appreciate any words of wisdom you might have for us! No rush :)

**Comment by claremacrae** [comment]
> Right :( I think I'll probably close this PR unmerged; the default case seems unhelpful - we either get 1,000 windows pop up and kill our computers, 

Wow. That's a lot of approval files! Which also means it's a lot of tests, which is great news.

With the previous implementation, how were failures managed, and how were the expected outputs updated?

1. Regarding making failures easier to manage by preventing excessive diff tools from flooring a machine, I would have a look at creating a JS version of this - which I've used myself in my own code, but never ported to the C++ library:

https://github.com/claremacrae/ApprovalTests.cpp.Nursery/blob/main/ApprovalTestsNursery/reporters/FirstNFailuresReporter.h

```cpp
    /*!
     \brief Handle only up to a given number of failures. After that, just do nothing and return false.

     Example use case: a GUI comparison tool creaks after being asked to show more than a
     certain number of image comparisons.
    */
```

----

2. Regarding reviewing large numbers of diffs, @EmilyBache  has written some scripts to analyse differences between received an approved, after approval tests fails. It shows you patterns of differences, and may be of interest.

https://github.com/emilybache/ApprovalTools

I think the one you are interested in is [analyze.py](https://github.com/emilybache/ApprovalTools/blob/master/analyze.py)

There is also `approve_all.py` - for accepting all the new versions... (received files)

----

3. > or we have to "approve all" and use an external diff tool to check...

It's still useful to have an "approve all", so long as all the members of the development team understand that if there are failures in approval tests, they need to review the differences, and not just automatically go ahead and commit all the updated approved files.

If there is any place in the code where people can enable auto-approve, it might be worth some sort of slightly stern comment there saying to treat every unexpected change in output as a likely discovery of a bug to be investigated thoroughly, before approving the new output.

----

4. > I wonder if we're "doing it wrong" - @claremacrae might be able to offer advice?

I don't think there is a right or a wrong, but I wonder if there are ways to make it more practical...  based on this subset, I see there are quite a few more additional output files than before... and very few of the outputs are recognised as renames from the previous output...



Does this change improve the test coverage, by increasing the number of outputs, perhaps?

I wonder whether there might be any value in grouping together some of the related outputs in to a single file, so that you have fewer outputs that are bigger...

Ordinarily, I would say it's good to have each approved file have a single responsibility - but as you have discovered, there may be practical consequences of that.

---

5. It's worth checking what the JS ApprovalTests does on your CI if there is a failure. In the C++ version, we use environment variables to produce text-based diffs in this situation, which gives useful console output instead launching diff tools, or silently just saying "it failed".

---

Re your comments in the PR:

> really wants to name the files *.approved.txt

You might have a look at this - you can probably customise the names. It might be harder to change the .approved bit - but you really should be able to control the extension, I would hope.

https://github.com/approvals/Approvals.NodeJS/blob/master/lib/Namer.js

> spawns all the diffs at once and so an overarching change can crush your computer with diff (e.g. if you use meld like I do, you end up with 100+ diffs opening)

See above...

> comprehensive testing means this takes longer, now ~16s to do all these tests

16s for that many tests is pretty good? Writing fewer files, grouped together, may perhaps help??

---

I've very happy to chat about this, if any of the above needs clarifying...

**Comment by claremacrae** [comment]
If the output files are JSON, you **REALLY** want to make the extension be .json, so when you view files in IDEs and diffing tools, syntax-highlighting is correct.

**Comment by mattgodbolt** [comment]
> If the output files are JSON, you **REALLY** want to make the extension be .json, so when you view files in IDEs and diffing tools, syntax-highlighting is correct.

Absolutely! I wish I could find how to configure it :( Seems very awkward, basically had to override the default and reimplement a lot of the functionality.

Thanks for the other comments; I'll take a look later!

**Comment by claremacrae** [comment]
This appears to be how to specify the file extension?

https://github.com/approvals/Approvals.NodeJS/blob/21789c2cb56ef90e04783b4b95a1cc57e80c0ed7/test/StringWriterTests.js#L23-L26

**Comment by claremacrae** [comment]
> This appears to be how to specify the file extension?
> 
> https://github.com/approvals/Approvals.NodeJS/blob/21789c2cb56ef90e04783b4b95a1cc57e80c0ed7/test/StringWriterTests.js#L23-L26

Maybe not - as it doesn't show how to inject a StringWriter with a custom extension in use... But it might give some clues.

**Comment by mattgodbolt** [comment]
Right: this is what I found before and it looked like I needed to wrap the whole test in my custom code in order to take advantage of it. Injecting a StringWriter doesn't seem possible, one has to call the test internals with it, unless I'm missing something?

**Comment by mattgodbolt** [comment]
> Does this change improve the test coverage, by increasing the number of outputs, perhaps?

Yes, it does. Not _necessarily_ in a useful way, but in a much more clear and obvious way. In the old code, if the "golden" file wasn't there at all, we treated it as "don't care", and we only put the cases that were problematic in. Now we have the cross-product of test cases x [all possible flags], which is strictly better coverage, but takes longer, and means up to 6x as many tests.

On balance, this is probably the right thing to do, or else we should consider separating subdirectories of things that are "only test on _all flags on_" or similar.

**Pull request merged**
