### PR TITLE
Set instruction sets for msvc compilers

### LINKED ISSUE #4788: [BUG] MSVC arm compilers have the wrong instructionSet
MSVC arm compilers appear to have instructionSet=amd64 instead of arm.

Repro: Pull up the assembly docs for any instruction at https://godbolt.org/z/aj8bWb4hx

The instructionSet is correct for the msvc wine arm compilers.

### LINKED ISSUE #6189: [BUG]: arm64 msvc points to the wrong documentation (it points to x64 documentation)
### Describe the bug

The `view assembly documentation` feature in arm64 with msvc points to x64 instead of arm64, and thus can not actually return the documentation. For example for the `b` instruction it returns:
> There was an error fetching the documentation for this opcode (Error: Unknown opcode 'B').
as seen here:
https://godbolt.org/z/894YxGo6T

### Steps to reproduce

It is available in the godbolt link

### Expected behavior

To actually mention it is a branch instruction

### Reproduction link

https://godbolt.org/z/894YxGo6T

### Screenshots

Not applicable

### Operating System

MSVC arm64

### Browser version

brave v1.63.162

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Fixes #6189
Fixes #4788

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]

**Comment by partouf** [comment]
this requires a windows update, im not doing that right now

**Comment by jeremy-rifkin** [comment]
sweet, thanks!

**Comment by mattgodbolt** [comment]
lol "windows update" :D made me think "oh no not that..." but I now realise you mean "update the windows nodes" :D

**Comment by partouf** [comment]
correct

**Comment by partouf** [comment]
It took me an hour to get a normal discovery running because of AWS weirdness, let alone to do a windows instance update again and then rediscover. A bad moment in the day

**Pull request merged**
