### PR TITLE
Add simdjson 3.10.0

### PR DESCRIPTION
**Pull request by vient**

### CODE REVIEW

**Comment by vient** [comment]
`make check` passed, but I don't know if it checks anything regarding this.

**Comment by partouf** [comment]
can you add it here too? https://github.com/compiler-explorer/infra/blob/main/bin/yaml/libraries.yaml#L1988

**Comment by vient** [comment]
Like this? https://github.com/compiler-explorer/infra/pull/1384

**Comment by partouf** [comment]
> Like this? [compiler-explorer/infra#1384](https://github.com/compiler-explorer/infra/pull/1384)

yes, thank you

will merge this tomorrow when the binaries have been built

**Comment by vient** [comment]
How often is CE deployed? Don't see new library yet.

**Comment by partouf** [comment]
this is now live

**Pull request merged**
