### PR TITLE
Also demangle quoted identifiers in LLVM IR

### PR DESCRIPTION
**Pull request by narpfel**
This fixes one of the two problems reported in #6558.

### CODE REVIEW

**Comment by narpfel** [comment]
It seems the version of `c++filt`pre-installed on `windows-2019` is [8.1.0](https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md#tools), which ignores the hashes in Rust identifiers.

**Comment by narpfel** [comment]
Is it okay to just skip the demangler tests on Windows?

**Comment by partouf** [comment]
> Is it okay to just skip the demangler tests on Windows?

Yes, no problem

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Pull request merged**
