### PR TITLE
Rust 1.68.0

### PR DESCRIPTION
**Pull request by ojeda**
Infra: https://github.com/compiler-explorer/infra/pull/961.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Thanks as always!

**Comment by ojeda** [comment]
My pleasure!

**Comment by mattgodbolt** [comment]
will be out before the weekend I hope!

**Comment by ojeda** [comment]
That would be wonderful, but no rush at all!

**Comment by jeremy-rifkin** [comment]
This is live

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
