### PR TITLE
add scnlib 0.4

### PR DESCRIPTION
**Pull request by dvirtz**
corresponding infra PR: https://github.com/compiler-explorer/infra/pull/561

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi! Thank you for taking the time to implement the support for the library from the getgo, we really appreciate it!

The code on both PRs looks good, but as the lib needs building, it might take us some time to merge it while we ensure it would work properly. Thank you! (Again)

**Comment by mattgodbolt** [comment]
We've been having some trouble with our library building infrastructure (I broke somethihng...) apologies for the delay while we get this working.

**Comment by dvirtz** [comment]
no worries. thanks for the update.

**Comment by partouf** [comment]
This is now live

**Comment by dvirtz** [comment]
thanks!

**Pull request merged**
