### PR TITLE
Add ptxas

### PR DESCRIPTION
**Pull request by partouf**
Needs some work

#2038

Todo
- [x] Not return errors when using binary mode
- [x] Labels?
- [x] Filters?

image

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Looking great so far. The asm parser is the tricky bit, and you've seen the horrid mess I've made in the "normal" asm parser. Any extraction of useful utils from that would be welcomed, but frankly a new pair of eyes and a fresh restart are probably best. No pressure though; copy paste and edit style stuff works too! :)

**Comment by partouf** [comment]
> Looking great so far. The asm parser is the tricky bit, and you've seen the horrid mess I've made in the "normal" asm parser. Any extraction of useful utils from that would be welcomed, but frankly a new pair of eyes and a fresh restart are probably best. No pressure though; copy paste and edit style stuff works too! :)

I think the biggest problem here is that I have no idea what all of these sass codes mean, labels also don't seem to work like in normal assembly. Actually there doesn't seem to be a way of telling what labels are. Will have to go dig in the documentation and conjure up a way to figure it out.

**Comment by partouf** [comment]
Ah, right, it seems that in this example there were no labels. Just an EXIT, which is a flow control command. https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#maxwell-pascal
Not that that makes anything clearer.

**Comment by partouf** [comment]
It actually looks like nvdisasm returns the same assembly, but nicely annotated with labels. And this is already supported by the default parser.
One drawback, however, is that it's missing the opcodes. But that is added easily with -hex. So I think I'll be using that one instead of cuobjdump.

**Pull request merged**
