### PR TITLE
Cpp 6502 as compiler

### PR DESCRIPTION
**Pull request by partouf**
Adds @lefticus 's current 6502-c++ as a C++ compiler

Infra PR: https://github.com/compiler-explorer/infra/pull/727

### CODE REVIEW

**Comment by partouf** [comment]
my naming is all over the place, sad times

**Comment by lefticus** [comment]
*I* don't even have this working in a reproducible configuration yet!

**Comment by partouf** [comment]
> *I* don't even have this working in a reproducible configuration yet!

Ha! I didn't really know what to look for if it's doing things right, but it was a fun little excersize to get working. We don't have to merge it.

**Comment by lefticus** [comment]
It's fine to merge it for sure, and it would be awesome.

**Comment by partouf** [comment]
this is now live https://godbolt.org/z/cffxh8YKc

**Comment by Madrid76** [comment]
> this is now live https://godbolt.org/z/cffxh8YKc

Please add the other legendary 8-bit chip: https://z88dk.org/ as a C -> Z80 assembler compiler

**Comment by partouf** [comment]
> > this is now live https://godbolt.org/z/cffxh8YKc
> 
> Please add the other legendary 8-bit chip: https://z88dk.org/ as a C -> Z80 assembler compiler

z88dk is now live

**Pull request merged**
