### PR TITLE
Rust 1.45.2

### PR DESCRIPTION
**Pull request by ojeda**
Note: untested.
See https://github.com/compiler-explorer/infra/pull/379

### CODE REVIEW

**Comment by RabsRincon** [comment]
Hi @ojeda . I just wanted to explain the delay with this PR: We're currently on the process of moving the Rust instalation machinery to the new python based tooling, so we're leaving new versions on hold until it's done.
Also, note that the last Rust version to have a minor update added to the site was 1.27.1!

Thanks for your patience :)

**Comment by ojeda** [comment]
No problem @RabsRincon !

I considered adding 1.45.2 since that were 2 minors versions in a row that happened fairly quickly with soundness bugs. Of course, resources aren't unlimited, so reject it if you are concerned about that.

**Comment by mattgodbolt** [comment]
I hope to get the remainder of the work done tonight and I'll ensure rust 1.45.2 gets added when I do!

**Comment by partouf** [comment]
This is now live

**Pull request merged**
