### PR TITLE
add scnlib version 2.0.0

### PR DESCRIPTION
**Pull request by correaa**
add version 2.0.0 of scnlib

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by correaa** [comment]
Ok, it compiles in CE  but it seems that the scn library is not header only, so it is trying to like with `-lscn` although I don't pass that flag.

https://godbolt.org/z/sf8v5zo1q

Can somebody help me with some pointers on how to make this non-header-only library with CE?

**Comment by partouf** [comment]
> Ok, it compiles in CE but it seems that the scn library is not header only, so it is trying to like with `-lscn` although I don't pass that flag.
> 
> https://godbolt.org/z/sf8v5zo1q
> 
> Can somebody help me with some pointers on how to make this non-header-only library with CE?
> 
> All this if it is possible at all, I know there are some contingencies about .so .a libraries.
> 
> I am thinking that perhaps the problem is that, if I install locally, only .a file is generated. Maybe I have to pass options to make shared libraries?

libraries get built every night, but this was merged when the builds had already started, you're going to have to wait a day

**Comment by correaa** [comment]
ok, thanks.

Now it starts linking but it needs another library.
It finds `-lscn` but fails to find other libraries like `simdutf`. Since it is a dependency in libscn (located in build/_deps when I find it locally), I am not sure how CE handles it.
Perhaps one has to add simdutf as a separate CE library?

https://godbolt.org/z/j1qeKrcb1

**Comment by partouf** [comment]
It's best to use the dependencies with which it was built with, unless it's only dynamically linked.

Because of this line, only libscn.a is packaged: https://github.com/compiler-explorer/compiler-explorer/blob/9fa88d50d50a75dbc5f72c220b9c426b6bc34986/etc/config/c%2B%2B.amazon.properties#L4251

And because this is different from v1, you will have to override it separately for v2

For example by adding the line:
`libs.scnlib.versions.200.staticliblink=scn:simdutf`

I see in the CMake file that it's also linked to fast_float, perhaps this should be added as well

**Comment by correaa** [comment]
ok, trying this: https://github.com/compiler-explorer/compiler-explorer/pull/6149
I don't see a local installation to generate a fast_float binary, so I am doing one step at a time.

**Comment by correaa** [comment]
I made some progress, but now it cannot find simdutf

https://godbolt.org/z/7a3hn5Eza

```
ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-13.2.0/bin/../lib/gcc/x86_64-linux-gnu/13.2.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lsimdutf: No such file or directory
collect2: error: ld returned 1 exit status
Execution build compiler returned: 1
```

**Comment by partouf** [comment]
right, i havent forced rebuilds yet, so the conan packages are missing the new binary
give me some time

**Comment by correaa** [comment]
right, i didn't know how manual or automatic the builds are.
so I was waiting at least 24hrs to raise any question.

**Comment by correaa** [comment]
Sorry to ask again, please let me know if I am doing something wrong or if it is just a matter of waiting for a rebuild.

**Comment by partouf** [comment]
it looks like our buildsystem is more stubborn than expected, i'll have to figure something else out to make it work

**Pull request merged**
