### PR TITLE
support new IR Dump header

### LINKED ISSUE #5587: [BUG]: LLVM optimization pipeline of trunk broken
### Describe the bug

LLVM Opt Pipeline Viewer of a trunk clang/LLVM compiler displays incorrect pass contents for IR passes (machine IR passes display fine).

This is presumably due to https://github.com/llvm/llvm-project/pull/66412/files#diff-9bcb7cbad2f3a6a1516397a3d059d03c91dcfdbd9edda564baddf1bb2652d928L745-R850, which added a leading semicolon to IR dump separation lines.

### Steps to reproduce

1. select a trunk clang compiler, e.g. "x86-64 clang (trunk)"
2. add new → LLVM Opt Pipeline

### Expected behavior

IR passes have correct contents.

### Reproduction link

https://godbolt.org/z/Y7a4KzGo5

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by partouf**
Fixes #5587

### CODE REVIEW

**Comment by partouf** [comment]
Not yet tested with the real deal, doing so now, but did manage to add unittest that did not work without the change, so good sign this is probably the solution.

**Comment by partouf** [comment]
It seems to work, except that I don't see the diff colors?

Screenshot from 2023-10-15 18-39-22

**Comment by jeremy-rifkin** [comment]
How odd, probably a monaco issue since this pr couldn't have broken it (as far as I can tell). I think I've run into stuff with monaco's diff being finicky.

**Comment by partouf** [comment]
doesn't work on a normal diff viewer either, so yeah..

**Review by jeremy-rifkin — APPROVED** [review]
Change looks good to me

**Pull request merged**
