### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by AnderMendoza**
Hello, in this PR I am adding links to the existing issue templates in the project, to speed up the issue generation process for future contributors. Also edit the style of the logo and initial text of the project.

Attached screenshot:
image

### CODE REVIEW

**Review by mattgodbolt — COMMENTED** [review]
Hi, I think these are well-intentioned changes, but please can we use Markdown here. This makes the tpo of the file substantially harder to maintain and edit unless you're doing it in a UI.

**Comment by AnderMendoza** [comment]
> Hi, I think these are well-intentioned changes, but please can we use Markdown here. This makes the tpo of the file substantially harder to maintain and edit unless you're doing it in a UI.

@mattgodbolt sure, I'll change it now.

**Comment by AnderMendoza** [comment]
@mattgodbolt ready, I attached a screenshot of the result.

image

**Comment by mattgodbolt** [comment]
Thanks: looks good. I appreciate the time, and that MD doesn't look _all_ that much better :/ but it's consistent with the majority of the document at least!

**Pull request merged**
