### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by apmorton**
Other than minor version bumps:

- moved to devDependencies
  - deep-equal-in-any-order
- removed
  - acorn
  - eslint-plugin-mocha
  - requirejs
  - uglify-js

### CODE REVIEW

**Review by partouf — APPROVED** [review]
Tested without issues

**Comment by mattgodbolt** [comment]
LGTM! Did a local merge of main into this (will commit) but seems ok!

**Review by mattgodbolt — APPROVED** [review]
Look good: thanks! (forgive me merging for you; seemed like to test it I needed to do so anyway so might as well push).

**Comment by apmorton** [comment]
Looks like requirejs got readded in the merge conflict resolution

**Comment by mattgodbolt** [comment]
Ah nuts, sorry....do you mind doing the needful and merging once your original goals were achieved...I won't break it any more :")

**Pull request merged**
