### PR TITLE
Unbundle and disassemble device code

### PR DESCRIPTION
**Pull request by partouf**
As described in https://github.com/compiler-explorer/compiler-explorer/issues/2244 - I have tested icx and clang so that it produces bundles and have tried to get them unbundled for the device view.

The device code is disassembled to LLVM-IR. In #2244 it is also discussed to convert possible gpu code to for example spir-v, I have not done this here yet.

The following things should work with these changes:

Using Clang
https://godbolt.org/#z:OYLghAFBqd5QCxAFwE4FN0BoCWIIDGAtgIYDW6AgqsAM4gDkDWBA9kQA44A26qAMiQB2wAK4lg6AJIATEAQCkAJgBCylS1G1k7APKjkHAwDEe6ISSLpGzAGZn6sdDJw7UskAEYs93h%2B%2B%2B5pbW6AAelhy8AHQEHBxYoEy4tFJCBNyiMs6MAAzMOLQAsiQ4QgDKrKKoBNYMecm6HOa5zNzCwB5MAJRdyQDCxRQACqisAFboBMiMnsxjXlhC6ADupn5ySr3cjACszEItWKyMACoY6ADUygDMs1jTdQw9WAjoJFmo%2BL1kXjtRAGwAFgAnDslAB2HaApQADh2nk81yw2wYgOYRC8ORyi0OxyS9GxDzyvTgsCQbCyAFEXG5cPhAhYrCAwhForF4rZWEJkGUCCReF5AT4ucgAKq0dBDUKHebeNoieTqdRYCW8KY4Ln4cwyPqsDJEA5KLDa/ildAAOVERAARnwvMCsBxWLRXBqhLr9YbHc7XVzTUtLTa7Z4HarJsg3WVkCRUMgPVavWH1VyozHkP6LVbbZ8Qyro7H4waQEbtGmM4Hs/berRKtVajdSulMpcFNc%2BgRtC5WK3KQocpQ%2B5RSsgLqRShAugpwWp%2BxcLsOLuartcACIXTzoGGtmeUOe2bisEgjgBUoWXa6Wywu%2B8PyAUOxU5vvK%2B3g73B6PF2PAE9zxdL9eH53g%2BT47C%2B1w7m%2BVxKNcHCoBIpAXOwHAXPmkgjsgbxELQFwuNoqA4NaBiXBwMb8rw3DXqwqCjiQHAQDoIAXKE94qDkICgSuXS0fRtijBiFzfqx7GcZOs5UagEALjgf45Nu87Ln0i7yTgSqqJO05QXu1FSdyFxjLJ8kGa2SmeFickQfpakqBpO5zvZgmsapYHQWoq4XNcp5Oc%2Br7iXOU4vuJAWDlBcHDrYEDKEoyg7MA959EIUVYI5D47M%2Bk4QSF4lZLwmFXA%2Bz7Mb5u64eguUtgVLlCZl/YBU8yK7PsuLMuEnBsnE9wtM8rzvHaE5YD81zggCMKAoCMJmdcwJAp4YINai6KYtiByPEcNgqiAhJdVgpJQDAiDyMhZioHShBHbwnzpO0AD6aCiEIZA%2BDwmGoPQEDWjMzDWqUMbfp9LDsFY3K6EI3B/QwdxZKQIgCqtLgYOqABu6D0BDzBhJMxH/cOZWHNwhHwag366lk/1oDgGJo70%2B4SLQABqOArI0zRo8K3K8vy1ieEKnLcuKkrSqtsrIu0iqqMq%2BPWo4/WsBwEZcqjAC0nJNEInAXMrsvmJwitoegyC0K2K5CIjcuhECismzgLgkIrBCZCQGt2w7iukcgCBGwA9LLyCe2wnDHYrYSRNRfB%2Bw7nsIlEfz1Em8sHBA2qFgc3gmmaFbBt6Lrx8nCxOtnbrllmmdx5G%2BZxnqCYLKXKbl0XQY5nmaa594paxvXlaeNWtY1AsaCYJ9WyNTiq14qEML/IrQIXFdIgXAxqD3WQ3EQH01nJdSrjUdBtzJbqAcXTvXfMESTzfCA1zXFEl837fd/zWiWAYpf1932/l//CP9R4swBKdY8JJ9oQCQFkRGOAainVAeA6wWs1YcEtqbZA5tAQIOtjgW29sZAkGNDSai1sFi8x5HyAU3M2ZiglFKGU1cyrhjdFqIQOpK5FlTgwjumd86%2BndEwlOWdOFsMbjXco5cW4qhocmIRZZ07FwEcI7h1c65SIbl4Xo/d0D4KpvNPYX9mB4hXOgMBNQLgMxWHwZiE8p6AhnvKYA887oPRXpvNwR897nVMTcY%2B/9iS9B6h8L4D9Fov3fu/T%2BK1v7rT/qfQB8BgEgEqIYAwp1/ZcAuuaYIjBx6T2nrPGxC8l5dHRrggicgAgig5iQnmIp%2BaUKFgsZY8EODbRRFo0JOjGD6HiSOVgtgzGZMsdk2xi97Hz33sktxMEPGRKHgtJ%2BF8r5BLftota%2BJNqeLPgNEAgJ/gAn%2BDsYEwJuaeEhDkcEQ15rXCaqPdakz5pKAuWEpI1zkavToYCIAA

and

Using ICPX
https://godbolt.org/#z:OYLghAFBqd5QCxAFwE4FN0BoCWIIDGAtgIYDW6AgqsAM4gDkDWBA9kQA44A26qAMiQB2wAK4lg6AJIATEAQCkAJgBCylS1G1k7APKjkHAwDEe6ISSLpGzAGZn6sdDJw7UskAEYs93h%2B%2B%2B5pbW6AAelhy8AHQEHBxYoEy4tFJCBNyiMs6MAAzMOLQAsiQ4QgDKrKKoBNYMecm6HOa5zNzCwB5MAJRdyQDCxRQACqisAFboBMiMnsxjXlhC6ADupn5ySr3cjACszEItWKyMACoY6ADUygDMs1jTdQw9WAjoJFmo%2BL1kXp5RAOxKf7/HKeHJAnYADhyOX%2BOyw2wYABZ9odjkl6Dl7i1enBYEg2FkAKIuNy4fCBCxWEBhCLRWLxWysITIMoEEi8LxInzM5AAVVo6CGoUO828bRE8nU6iwgt4UxwzPw5hkfVYGSIB28Kv4pXQADlREQAEZ8EBKLEcVi0VyKoRqjVarBWm3IO26paGk1mi2y9Dyt3MsrIEioZAOo1OuWTQPlENhj0Go2mz6%2B7Sh8PqyMLdMJvVelPmnK9WiVaq1AD0ACoqwocpQLlWLmUAJp9fgXYy6ABKFz6fIAIg2QBcAGox1ioC6UGSku0XInhTi8OsN2v1xt91gcACeqBwwAQyAuFotW6ykRIO%2BbrFsyGWocu/GQMiiq8b76bupqQkFMguohCB8FzIK804cCQBBgd%2B5iClgY58DazInlEOQXBAoGXMoSgwb%2B6DYV0CjXGoG5NjulQXKQ15CKwx5aJcoEFBcgQXGENQcMepQXGwy44MINQXMsrgICB0E4D%2BgpvqRFwthRVEXKwxohlxJDcdu163qJT7ibBlwkMgn6fhcxnGUehggBWFbLNZUQkBBUHoFEk7ABW3A6XhtAVvwUh9ES%2BplESAC0SioYZ0kmRcfJCLwtC0BcGAAI6iDgGD/sa152ZE4kkMavAXG0ywKVOEjnP%2BOgXFxyz7m6IjwaWd4PhgRkRS42j7saBjOABQF8FpFy4YKFVxa1aA4B1yBdchwhXEoSiUGUFxSGU2EXCo81LVgzUmQA6lIJwABK6HyJwXNtlDdt2lD6icUhEgtPZ9ro%2BoDntUhPfdxjTvqLYXAA0lIz3wegwm9WEHAYLFRUVbxzhSWuEXNpgfUDZcTJTphFy0E0BA4PYBD5e04iSBcwCsAAbnwQilMAFxNKgRAFEhv4XMIMhbcZbkMyGsZxYBwEYyjcMftJAACazWBcFNTJOAD67xzsyMRxJ%2BFarmrSjXKU6SZFh1x9BypPVQgRBEUS6ua2kGRZFceuKm1bwm9cZv1jcWtW7rfRS24ptqy7GtuzrNt9O2Fa0Du6RRAgytO77lDpCQkP9kOZT%2BhOU4jkYuXiZj4fbCAWRkzpMvRtLU4KP8JGUJnbkECA74VSyCl0/pk4QF0hDMtoOfpCA%2BfoIXAnKAAbAXOldGpv7HuTfD7tb5eVxFuMQKPNRRJIyAy5eyBo0Qbdr%2BgG/GpBFBAW3NsDkRA7d3nR8ECfcjyJkJCERX9cRdoD9sAYQdEX0M1KH2QcDYV6o0qEBf%2BP89aYxfL3FU3AiILwRhgZAVQhAXE8Agt%2BVx/hX39IKeeWDjLINQRcQKGDiJYPLhfDc2DqGUCoZgl29ZSjHlIKUCALCWY0AIPBKCoZGyhmAGTBQOw1A7AHOPAhNC2CTzBlOGRXcbQAC90Ay2PPqc%2B6CYTaMYQ2Ceijc691QO0S444CBlBwCo%2Be%2BoGEUKYXosOPcQAdVsLYPgv8ZCVFyvhJ2FwXH0IrmYixVicG6OMo4m%2BohXHuL1p40Q3jTZ%2BKiWoQJkxgn4VCXYhxhjnFRLcagDxXiVy%2BJcX0eeQTLEZIvlk%2BullFpUzdBySpDcjDHhkPpEg9cpF6OMgo48JADCsAuDIKqrhVHHkvtfXukEaixV7kQVgWRe6tXZKgGQMtRkTV0VggZ5UEBy00f4/eG8ZnoFih4zZ4zTZtzCSZXZQz9nGkOck45csCCzNoBc6qVynY3KyRFNG6FOE4E0TkBBFUg4XBscRCq0pVCSNfjQiK%2BzOmiJwCIq%2BkybRCA4ePJs2LcW3ORTLY0IiVDovEZotgtBcWbmpYS/5JkGE0OZfQmhETe5JXQKIS4RAdwAEUeU8vnkneaqdS43MyZXWpFYtxEFIOAgA4qMUQHBuIYH0naeu9zuI00mWS4eGKIAcpAAgVmvAy5KCHggBFiDemd36YM%2BKbx1kTOuFfE1py5kgAWUskAGq2aMvtZPFmTrLlqM0Z695Zz6A%2BsWdYEAlztlItDeVVSkyjnrzeR83%2BAa1HXJtUS1NQynkZpeVmr1ny9Z5oMr8wtQbi3cWebYPorzK2/3DbWokEB63SpTQgKIEFjHcF4NwGWaMIAVJUZtFNCM50RQNe6o1JqcCBr6OQokFVbXcTJRSzF7qWa7oxTNFQfij3iPBVQwijLbF9r0XywV3LHK0HiVzQgwBr13uMt0iKfTG01sjTkyt8z41GJdUWnV%2Bz8ZlpbW26N5zq0uvzb8z9WC4neMxkaUFqFbBFsBRwxuILJlgphURqB0LT3otUOoW1hDMNEBPZMqD57ql2toVgj%2Bvcv5urKVA7CZQsNMRHCtX%2Bv96OQL/pxmkQF4E3tCfYohB8SEkelTgp4CJdiokeEcGkS5IiOQZNiR4zxXjvDNG3LAPxrghR2Dsf4Q9riOaHs5pEkIkRKHhIiFEiw0Q2FlCALEDw8i4hgIgeQ7AuAWvJB3TgZhPjiVCKeC0WJfATVQPQCAxpDjGlKKGHcMxmA8SsCyXQ0V8sMDuFkBVwBOTaZcBgBUFN6DabCJMTqBXcAsn9IcNyxpjGoB3GqJZ2nRpEAK70WwbQ6CjhwCsRozQKt2F5GyDk1hPDciZCyAUQoRTabFAidoUpqOqARGNRwFntw80YIFD%2Bl9FDHZUJ4f4pCpAVkuxWHikW%2BCBTBtwScfAKwsP9IFBkwVwQhRyFEP4/xPAfYi3F1y%2BkznIFcqUUQoRAeW0DoFV773PtxZ%2B6ESI/3UCY4mtwEHcQwezVQlDgEsP8cWsRxNbQqOhDo8x9rLIodc6kO4G9jicPYsWsJ8TjApOgcU9B0l2n0OGfw6Z20FnKO3Ls4x711HxoCC5yiKWUhtgIn64iYFeM68q0DiEGTDioQh5IkCpb1dfEQdPyN7nQKgEqTOECm0E07TSHbRot70oFBUCBUalTEQcVArO/aYFCCoFL4C5R4z77v2ScfafhWTwfwkSoX14H43vWsYpTJswEusZlRAQjJqBYOp8zJjNN4F0tpmTV6dM32MiYCyN79AGO0wYMxt5zOK2MA%2B8yegb58bwuZMyOhzPGZAXfJ9eBLGWGoHW0CYBXxphgewfPafRKESEQ9Aq24qgQUIJ5we07QhAMpD34JnCRjcbwcqvuWtuF0ZgQWnjfBANcSHGHJEZzHYIeHIOzIAgATm5C82YDGzBCxAOAPz80xCM2CywDxDCxAWixARAGN0t2t1t3t0LhcBIBjxICwGcFcEnFXQ6021ZHZE5HWx5C20FGFFFGHz7yVAgBVCH21CAiX29Cn2dGtBb3tCzBryb1EM73ryEM4JjH7wXz4N7wUKDAX0EMLGnyUIkKjHUNkM0N6E32BjkE8C2E0333qHRAHH7h0jHFm2WF6iPxPzPwSyvxp0h1vyfywg1lfzVGF16hfy/zQN/0s3NE80YG8yQMsJQIC2COeERCUC02iKSB/2eApnSztBACRCAA%3D%3D

Also ICX with openmp
https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEgBykrgAyeAyYAHI%2BAEaYxCAAnKQADqgKhE4MHt6%2BASlpGQKh4VEssfFJdpgOmUIETMQE2T5%2BXIFVNQJ1DQTFkTFxibb1jc25bcM9faXliQCUtqhexMjsHAD06wDULEwELF60AHTIyckgWwCye8R4qleHjsm0eKKOAlvYqqzPmFte6SMWwA8slGJdlCCqFRaKgmPggSYNABBcwAZjCyG8WC2JjRbgUBHwqCOCDx2CRqLMGIYWK8OLxbl2BAQpPJlPRmOxf0ZhPQL2ibLRFJRHOpWBo4SuyIAGlsuGZ/JSwgQtqiAKwWS6ykzqgAiuq1Ov1pC2Vk12pluoNFuNetNbkNlutTrtDoA%2BkJsAAlACSyOCrqt%2BqDLrRVlFKIIAE8wRKtiqzcDgYHw5SY3HMFQE4ItgAVACaygpacjyIsyeCW2QCGqAGt3cRMApHhBC8WtgAqJgOLxiU3t7BdzCqMEOTDoU1eBjpYDhdBbBhzXEAdgjyK2m62/GIWwg09n84TuLReq2GjxFmPjMXl4T1msy5Ma8pW7fCaoEB7BD7tENeGtLYwDAPEzxHMcCAnf9rSfF8UXfBCtmSW5BE/cwzAANTELw/hYPAFGZGstj2HMsHuUDcTMdV0COT5R2qSD0AucxqPQ19EI4rd0NNZFezEZiqJo3U3AYbiE1NcCGKgzUAJNYi%2BL/GSYMvdjOK2Jsf2IBhzxU%2BDEOfA09M3AzVPUzBNO0rhdNRFdDNRFEADdUDwBd3XdPYCFuaIvEgty9wgBhnIYF5wjmZcPBYZIfMwCA5g5OCN0otFkKYYBdi2VBIq2EZgHM7LMFYBQtnwQkvOipCGjEehaG3EgdiYZIICIC5kVNCxl12RqiCoYhMouNwn3VR0jLU0axvGzcWSbeF3RePCCAgBV/DivTn3XN8dz3RM8BPM8L3Da98WlK0DoAyxH1MzaIETbRdp0g7bpvZ0HofSwVsSzcrsTOs7v2q8fqenUDrrV72tM99HSUkNNW0QCH1PNVoOhiwQf1LszUNVGbQsWGQ1LRKTNFWyORRRNdjCWLV3W2rd2u3Mdoov7DrcY67zOqw3suuq6dVR6EaZvmWeeq9YfOt6qfBxGoex3GzwohnLC2W6AFp5WshDzQsWSZbhhGdtVx7Fas/G30J%2BzEq%2B%2BnfrZk8haBq92YuvTLd562Htt1mXrFsHne5763f%2Bj3ha2EHvfexC3E9H1/UDaXDVlyirARjUtZdTUsfRzWsfjsN13YiKosg2LrPYvBswgYCa3rRtm1bHnOyfMwADZIYsC9kfb%2B0tsEBvKJbqO/QDQ1O%2BH61TUtdHLTCiWRuQlU0LMMwADFkV9YJsBtET0Lik2tw05ZLPV1c7PYufUIgdDlGRIQvU30TF536n960%2B689sjgFloTh1V4PwOC0UgqBOCOm9lsBQSwVg8mpDwUgBBNAfwWHWEA6oND6E4JIX%2B8DAGcF4AoEAqC4H/w/qQOAsAYCIBQJlZIdA4jkEoGgSKND4ivFUGYDQi8NCoJoLQSCxA8EQGiFg6IYQGjRk4DAhhbBBDAmCmIohpAsC7CMOIeR%2BAmw1Acs2LBI5qjRXEbwFUmAv7yIFMQURHgsBYM8ngFg%2BiFgwlSgoDCeBMAAHdQSMH0TIQQIgxDsCkN4%2BQSg1BYN0FwfQhhjCg30HgaIeDIALFQMkd4M5ODKwAI5JMYFlZW/AwQMEisrHK5kFCgQUNQ4gTcMG2CMQxTILgGDuE8C0PQIQwj9DKIMcJqR0gpLGK0fIvTMjTAGPEcJHQUndFGM08YNT7CTJGL0dpMwumTGmTkAZhIpjLNGRIBY4DlirD0J5TAaweCf2/pg%2BRQCOCqH8E3ZWVSEzIHuGwxeRwNAfL3CAjmNhPj4CILudE4StgFyYUlLgcxeCEK0GFUgSCUFoI4NU2xiK/4AJubg/BsD4ELFIRQrADlXiYDoRAQlxKQBZIKckZW5S8CVOkBOQgJAXJ6H4D40Q4gAnsqCSodQ8iwlzLqc4CArh%2BmtMaSMzp8R1SDMKFkGZAyenyqlbMWVEzaiLPFeM2pnQGBTKWSUXZ6qtWKr0FsxoqrBjqgWCczArLuDEOMT/Ug6LeA3L1JgIlqwtjOLcXELYdyHlPJYVsN5ZgPlfIgLgZlQLoEOioeC4FUKcVELhcYlFyDUFuuwRwLFBDcWIKzUitEVyMU4NTbCi5HAzBlvdRWmFCDSCaL4fUyQQA%3D%3D

icx with spirv target:
https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:15,positionColumn:2,positionLineNumber:15,selectionStartColumn:2,selectionStartLineNumber:15,startColumn:2,startLineNumber:15),source:'%23include+%3CCL/sycl.hpp%3E%0A%0Ausing+namespace+cl::sycl%3B%0A%0Avoid+vector_add(queue+%26q,+buffer%3Cfloat,+1%3E+%26a,%0A++++buffer%3Cfloat,+1%3E+%26b,+buffer%3Cfloat,+1%3E+%26c)+%7B%0A++q.submit(%5B%26%5D(handler+%26cgh)+%7B%0A++++auto+a_handle+%3D+a.get_access%3Caccess::mode::read%3E(cgh)%3B%0A++++auto+b_handle+%3D+b.get_access%3Caccess::mode::read%3E(cgh)%3B%0A++++auto+c_handle+%3D+c.get_access%3Caccess::mode::write%3E(cgh)%3B%0A++++cgh.parallel_for%3Cclass+kernel%3E(a.get_range(),+%5B%3D%5D(id%3C1%3E+index)+%7B%0A++++++c_handle%5Bindex%5D+%3D+a_handle%5Bindex%5D+%2B+b_handle%5Bindex%5D%3B%0A++++%7D)%3B%0A++%7D)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:icx202200,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-fsycl+-fsycl-targets%3Dspir64',selection:(endColumn:42,endLineNumber:7,positionColumn:42,positionLineNumber:7,selectionStartColumn:42,selectionStartLineNumber:7,startColumn:42,startLineNumber:7),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+icx+2022.0.0+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:50,l:'4',m:52.73752012882448,n:'0',o:'',s:0,t:'0'),(g:!((h:device,i:(device:sycl-spir64-unknown-unknown,editorid:1,fontScale:14,fontUsePx:'0',j:1,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),treeid:'1'),l:'5',n:'0',o:'Device+Viewer+x86-64+icx+2022.0.0+(Editor+%231,+Compiler+%231)',t:'0')),header:(),k:100,l:'4',m:47.26247987117552,n:'0',o:'',s:0,t:'0')),k:50,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

### CODE REVIEW

**Comment by dkm** [comment]
(first link points to 127.0.0.1)

**Comment by partouf** [comment]
> (first link points to 127.0.0.1)

:D thanks

**Comment by partouf** [comment]
this is now live

**Comment by RubenRBS** [comment]
For the first link I get a `<Compilation failed: this.devices is undefined>` - is it expected?

**Comment by partouf** [comment]
right, my clang trunk was different from production clang trunk, if you switch to clang 14 it works

**Comment by rscohn2** [comment]
It's great! I did not realize how well it was working until now because I was getting errors with the first link and thought it required something extra to be installed.

**Comment by partouf** [comment]
Changed the first link to use clang14 just in case someone else stumbles upon this PR and wants to try it out

**Pull request merged**
