### PR TITLE
Add Qt (Core only)

### PR DESCRIPTION
**Pull request by amyspark**
:wave: 

Hey @mattgodbolt,

This PR is the counterpart  tohttps://github.com/compiler-explorer/infra/pull/928, adding Qt to Compiler Explorer.

Please note I've not been able to test it -- see the associated PR for further context.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
I'm so sorry this has languished: we have had a bunch of big internal refactorings. I'll take a look now: hopefully we can move this forward!

**Comment by mattgodbolt** [comment]
Sorry this is taking so long, I'm still working (slowly!) on the library build part of it.

**Comment by partouf** [comment]
This is now live, Thanks for your PR and patience!
https://godbolt.org/z/dTxsTT16d

**Comment by dangelog** [comment]
Hi,

Is there any major blocker for supporting other Qt modules, like QtGui or QtWidgets?

**Pull request closed without merging**
