### PR TITLE
Adds .hidden for libraries

### PR DESCRIPTION
**Pull request by RubenRBS**
Needs a review for the wording when no libs are available

This comes from a suggestion form #2778

### CODE REVIEW

**Comment by partouf** [comment]
Code checks out.

As to the text, maybe we just shouldn't see the library at all. So maybe `return false;` and don't add it to the search results and dom?

**Comment by RubenRBS** [comment]
I need a reminder on how to update the failing tests. Manually?

**Comment by partouf** [comment]
manually add `hidden: false` things to json within the `libs.should.deep.equal(` bits, indeed.

**Review by partouf — APPROVED** [review]

**Review by mattgodbolt — APPROVED** [review]
LGTM!

**Comment by mattgodbolt** [comment]
Now live.

**Pull request merged**
