### PR TITLE
Fix catch2 include directory

### LINKED ISSUE #1479: [REQUEST] Incorporate Catch2 using its single header rather than its include directory
**Is your feature request related to a problem? Please describe.**
[Catch2](https://github.com/catchorg/Catch2) is advertised as a 'header-only' library - which leads one to expect it to be usable within executable code on Compiler Explorer, using the 'a.out' option.

However, Compiler Explorer incorporates Catch2 using its `include` directory, which contains all the component header/source files that make up Catch2. These files are glued together with a Python script when a Catch2 release is built. Including Catch2 with 

```c++
#include <catch.hpp>
```

brings in all the declarations needed by Catch2, but not all the definitions. This leads to linker errors.

**Describe the solution you'd like**
Rather than Catch2's `include` directory, add the directory `single_include/catch2` to the include path. This directory contains the generated single-include version of Catch2. 

**Describe alternatives you've considered**
One workaround is to `#include` the 69 `.cpp` files that are part of Catch (see [this example](https://www.godbolt.org/z/VlW2dO)). That's not an easy list to remember, however :smirk:

### PR DESCRIPTION
**Pull request by AMS21**
Fixes #1479

Note that catch2 versions prior to v2.3.0 did not have the Catch2 sub directory inside single_include. [v2.2.3](https://github.com/catchorg/Catch2/tree/v2.2.3/single_include) [v.2.3.0](https://github.com/catchorg/Catch2/tree/v2.3.0/single_include/catch2)

### CODE REVIEW

**Comment by partouf** [comment]
I would like to know, from anyone who's been using Catch2 with CE and possibly has shared linked examples of it, that this isn't a breaking change for them.

If it is, I would feel more comfortable in having new versions for the single header include folders.

**Comment by AMS21** [comment]
I definitely see your point but, as far as I understand the issue with Catch2 here, you couldn't get the library to work as intended by just including catch.hpp because its missing all the implementation files and you needed to also include the cpp files for it to work anyways. So all shared linked using catch2 just by including the header won't compile anyways and should work after this fix. The links we would break are the ones including the cpp files.
At least that's how I see it, please correct me if I'm wrong.

**Comment by partouf** [comment]
It only doesn't work if you execute/binary mode with catch, normal examples like before we added execution got compiled fine.
Like this example in #1479 without bin/exec https://www.godbolt.org/z/ccAs4s

**Comment by AMS21** [comment]
Ah okay. Thanks for clearing that up :)

**Comment by RabsRincon** [comment]
It adds some burden on the config side of things, but what about having both versions? Either as different lib versions or as a different lib althogether, maybe?

**Comment by AMS21** [comment]
Should both be relatively easy to implement. But since I don't really use the catch library I might not be the best person to make that decision.

**Comment by mattgodbolt** [comment]
I'm not a user either: I don't know who would be linking with catch2 or trying to run, but it would be nice. @philsquared any thoughts? :)

**Comment by partouf** [comment]
Executing with catch is obviously useful, the question is how would we do it.

I tried using the raw github link, but without optimization it also generates too much asm, so that doesn't even work either. And with optimization it takes too long.

-E Preprocessing phase looks to be quick. Compiling just takes a long time. Clang/gcc doesn't seem to matter.

I don't know how to solve this...

**Comment by marcpawl** [comment]
This looks like a generic problem in that adding a library adds the include path, but not the libraries.  So we can compile but not execute something that uses a library.  In my case I was using google-benchmark.

**Comment by philsquared** [comment]
Sorry, I completely missed this the first time around!

Is the issue, here (with the "too much asm generated/ takes too long") because the whole of Catch2 is being compiled (ie using `CATCH_CONFIG_MAIN`)?

Or is the code being linked with a pre-built library built with `CATCH_CONFIG_MAIN` and the CE entered code just does `#include "catch.hpp"`?

If the former, is the latter possible to do?

**Comment by partouf** [comment]
> Sorry, I completely missed this the first time around!
> 
> Is the issue, here (with the "too much asm generated/ takes too long") because the whole of Catch2 is being compiled (ie using `CATCH_CONFIG_MAIN`)?

Yes, I also tried it just now with a local copy of the hpp files like we do with boost, but that doesn't seem to make a difference.

> 
> Or is the code being linked with a pre-built library built with `CATCH_CONFIG_MAIN` and the CE entered code just does `#include "catch.hpp"`?
> 
> If the former, is the latter possible to do?

Pre-built will be difficult. There's a lot of compilers and compiler arguments to consider when supporting C++ prebuilt libraries.

**Comment by partouf** [comment]
I checked recently if we could maybe prebuild something of Catch2 and use that, but I couldn't get cmake to produce a linkable binary. Not sure what I was doing wrong, because I think it should be possible.

**Comment by mattgodbolt** [comment]
Thanks Partouf.

**Comment by philsquared** [comment]
I've been a bit hands-off with Catch2 lately (hoping to change that) - but I know @horenmar and co have been working on making Catch2 buildable from cpp files - with some parallel work on libs.

**Comment by partouf** [comment]
It seems that a new preview release includes a static library that can be made with cmake, I'll see if that does the trick https://github.com/catchorg/Catch2/releases/tag/v3.0.0-preview2

**Comment by partouf** [comment]
Forgot to mention here, but Catch2 v3 fixes compilation time for the user as long as we can provide the static library, for which there are things in the works.

So for decluttering sake, I'm closing this PR in favor of https://github.com/compiler-explorer/compiler-explorer/pull/1945

**Pull request closed without merging**
