### PR TITLE
New Compiler: Hexagon-clang

### PR DESCRIPTION
**Pull request by quic-rvarghes**
**Related to:** compiler-explorer/infra#1061

**Goal:-**
To enable back-end support for hexagon clang compiler so that it can be used on the Compiler Explorer's website ([https://godbolt.org/.](https://godbolt.org/)) This will be particularly useful to people working on Hexagon Digital Signal Processor (DSP) developed by Qualcomm Technologies.

**Information about Hexagon DSP:-**
[https://developer.qualcomm.com/software/hexagon-dsp-sdk/dsp-processor](https://developer.qualcomm.com/software/hexagon-dsp-sdk/dsp-processor)

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Confirmed the referenced path is good! thank you - merging now :)

**Comment by abhikran-quic** [comment]
Thanks @mattgodbolt and @partouf ! :)

**Comment by mattgodbolt** [comment]
I was planning on doing a release tonight but hit an issue (unrelated to your change). Hoping to get it out in the next day or so though!

**Comment by mattgodbolt** [comment]
I managed to get the release out: this is now live (asuming it worked; I didn't test this specifically!)

**Comment by FabianSchuetze** [comment]
Thanks for the addition of the hexagon-clang compiler. I have tried it, but I couldn't compile a simple example. See here: https://godbolt.org/z/q46reeG7M 

The example works locally on with my toolchains (Hexagon SDK 6, and 5.5.11). 

Does anybody know what's wrong with my example? 

I'm not sure of the OP is still active, so I'm also tagging @androm3da  which raised a related question and still seems to be active in quic related projects (I beg your pardon, @androm3da !)

**Pull request merged**
