### PR TITLE
Add few clang compiler alias for BPF target

### PR DESCRIPTION
**Pull request by dkm**
Add 3 latest clang version aliases to BPF target.

refs #4408

Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

### CODE REVIEW

**Comment by borkmann** [comment]
Thanks so much! Not blocking for the PR of course, but could you also add clang trunk as well? That would be very useful too.

**Comment by dkm** [comment]
@borkmann we usually use binutils for objdump and demangler (c++filt). Is it a valid choice also for bpf?

**Comment by borkmann** [comment]
> @borkmann we usually use binutils for objdump and demangler (c++filt). Is it a valid choice also for bpf?

For BPF, is it possible to use in all cases LLVM pendants?
```
cat foo.c 
int square(int num)
{
	return num * num;
}
clang -target bpf -c foo.c -o foo.o
```
Will give:
```
llvm-objdump --disassemble-symbols=square foo.o 

foo.o:	file format elf64-bpf

Disassembly of section .text:

0000000000000000 <square>:
       0:	63 1a fc ff 00 00 00 00	*(u32 *)(r10 - 4) = r1
       1:	61 a0 fc ff 00 00 00 00	r0 = *(u32 *)(r10 - 4)
       2:	2f 00 00 00 00 00 00 00	r0 *= r0
       3:	95 00 00 00 00 00 00 00	exit
```
That's the more commonly used disasm output in BPF community.

I know that the BPF gcc trunk uses the non-LLVM one at the moment.

Each could use their own by default, but if it is possible, it would actually be really nice for users to pick a choice when they compare gcc vs clang outputs to results are easier to compare.

**Comment by dkm** [comment]
Ok thanks, I'll see what I can do. I don't think I've seen any usage of `llvm-objdump` yet, so not sure our post-processing will work, or even if we know how to call it.

**Comment by partouf** [comment]
> Ok thanks, I'll see what I can do. I don't think I've seen any usage of `llvm-objdump` yet, so not sure our post-processing will work, or even if we know how to call it.

you'll need to also set `objdumperType=llvm`

**Review by RubenRBS — APPROVED** [review]
+1 on this

**Comment by dkm** [comment]
Ok, so this is not working :(
The reason being that our "compile to binary" is really "link to binary" (another reason for me undusting https://github.com/compiler-explorer/compiler-explorer/pull/3232 ), and we use `gcc` as the linker drivers.
```
clang version 16.0.0 (https://github.com/llvm/llvm-project.git 8304f6de94872cdcaba63039a61b8860fe367620)
Target: bpf
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk/bin
 "/opt/compiler-explorer/clang-trunk-20230107/bin/clang-16" -cc1 -triple bpf -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name example.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -v -fcoverage-compilation-dir=/app -resource-dir /opt/compiler-explorer/clang-trunk-20230107/lib/clang/16 -fdeprecated-macro -fdebug-compilation-dir=/app -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/example-87b770.o -x c++ <source>
clang -cc1 version 16.0.0 based upon LLVM 16.0.0git default target x86_64-unknown-linux-gnu
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /opt/compiler-explorer/clang-trunk-20230107/lib/clang/16/include
 /usr/include
End of search list.
 "/usr/bin/gcc" -L. -o /app/output.s /tmp/example-87b770.o -Wl,-rpath,.
/usr/bin/ld: /tmp/example-87b770.o: Relocations in generic ELF (EM: 247)
/usr/bin/ld: /tmp/example-87b770.o: Relocations in generic ELF (EM: 247)
/usr/bin/ld: /tmp/example-87b770.o: Relocations in generic ELF (EM: 247)
/usr/bin/ld: /tmp/example-87b770.o: Relocations in generic ELF (EM: 247)
/usr/bin/ld: /tmp/example-87b770.o: Relocations in generic ELF (EM: 247)
/usr/bin/ld: /tmp/example-87b770.o: Relocations in generic ELF (EM: 247)
/usr/bin/ld: /tmp/example-87b770.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
clang-16: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
Compiler returned: 1
```
Possible solutions:
- use bpf-gcc for linking. I still feel this is not what we want, but that's the easy fix
- really only compile (no link) to binary (see PR above)
- disable binary altogether.
I'll try number 1 until 2 is implemented :)

**Pull request merged**
