### PR TITLE
Added cppitertools

### PR DESCRIPTION
**Pull request by niekbouman**
Hope this works. (I did run `make check`)

Related to:
https://github.com/compiler-explorer/infra/pull/405

best regards,
Niek

### CODE REVIEW

**Review by mattgodbolt — COMMENTED** [review]
Thanks! It looks like the PR to the infra hasn't popped the code in the right place:
```
$ ls /opt/compiler-explorer/libs/cppitertools/
BUILD           WORKSPACE       chunked.hpp                        compress.hpp  dropwhile.hpp  filterfalse.hpp  itertools.hpp     range.hpp     sliding_window.hpp  test/                zip_longest.hpp
CMakeLists.txt  accumulate.hpp  cmake/                             conanfile.py  enumerate.hpp  groupby.hpp      permutations.hpp  repeat.hpp    sorted.hpp          unique_everseen.hpp
LICENSE.md      batched.hpp     combinations.hpp                   count.hpp     examples/      imap.hpp         powerset.hpp      reversed.hpp  starmap.hpp         unique_justseen.hpp
README.md       chain.hpp       combinations_with_replacement.hpp  cycle.hpp     filter.hpp     internal/        product.hpp       slice.hpp     takewhile.hpp       zip.hpp
```

I'll fix that up and then merge this once I've confirmed the code's being placed in the right directories!

**Review by mattgodbolt — APPROVED** [review]
Looks good now! Thanks for this. This will make it to the site the next time we

**Comment by mattgodbolt** [comment]
...next time we update (probably in a day or two)

**Comment by partouf** [comment]
> #include <enumerate.hpp>
> #include <iter/enumerate.hpp>
> #include <cppitertools/enumerate.hpp>

`#include <cppitertools/enumerate.hpp>` works

**Comment by stayprivate** [comment]
Ah figure out my mistake. I though I was using cppitertools trunk but had selected v2.0.

Thanks for the quick response.

**Pull request merged**
