### PR TITLE
Add missing webasm target for clang in C

### PR DESCRIPTION
**Pull request by xgupta**
Fix issue [2559](https://github.com/compiler-explorer/compiler-explorer/issues/2559)

### CODE REVIEW

**Review by partouf — APPROVED** [review]
LGTM

**Comment by xgupta** [comment]
It may be basic but I was not able to test changes. i.e. There is only a clang default to select from the compiler tab, though I have built LLVM/Clang with WebAssembly support.

**Comment by mattgodbolt** [comment]
@xgupta to test locally you'll need to make the same changes to your c.local.properties (I tend to `cp etc/config/c.amazon.properties etc/config/c.local.properties` or similar). but this looks good; thanks!

**Comment by partouf** [comment]
This is now live, Thanks!

**Pull request merged**
