### PR TITLE
Pass -fsyntax-only when getting GCC options and test that -masm= is really supported

### PR DESCRIPTION
**Pull request by ibuclaw**
Hosting on a site with nearly 200 cross compilers, pretty much all are without a capable assembler installed.  One bug I ran into was that when invoking `gcc --target-help` and others, the compiler still creates a dummy file to which the driver attempts to assemble it.  This naturally fails and so the GCC Tree/RTL feature is not picked up.

A few of the cross compilers are for Darwin i686/x86_64.  For both of these targets, `-masm=` is available as an option (it is picked up from the i386 target options).  But the darwin support code will reject it if present on the command-line.  So in order to properly disable, gcc needs to be ran again with `-masm=intel` passed, and if there's an error, we know it is really unsupported.

### CODE REVIEW

**Comment by ibuclaw** [comment]
> Will have to see and remember what this all is used for and if it doesn't break anything, but seems ok

I actually skipped running the testsuite, it looks like there's some tests that assume the BaseParser is able to handle undefined help args.  So I've just overridden getOptions instead.

**Comment by partouf** [comment]
Btw, can you run npm run lint and fix the styling things;

Travis returned these;
```
/home/travis/build/compiler-explorer/compiler-explorer/lib/compilers/argument-parsers.js
   95:1  error  Expected indentation of 16 spaces but found 2 tabs  indent
   96:2  error  Mixed spaces and tabs                               no-mixed-spaces-and-tabs
   97:1  error  Expected indentation of 24 spaces but found 3 tabs  indent
   98:1  error  Expected indentation of 24 spaces but found 3 tabs  indent
   99:2  error  Mixed spaces and tabs                               no-mixed-spaces-and-tabs
  100:1  error  Expected indentation of 16 spaces but found 2 tabs  indent
```

**Comment by partouf** [comment]
Testing this on production to see if at least all the compilers show up as intended (might also affect argument help texts but not super important), otherwise ill tweak this in master.

**Comment by partouf** [comment]
Some weird things going on with the microsoft compilers, but I assume that's not because of these changes. So looks good, Thanks!

**Pull request merged**
