### PR TITLE
resolve #4330

### LINKED ISSUE #4330: [BUG]: `Result: [Object object]` in log for wine
### Describe the bug

exec.ts outputs a `Result [Object object]` at startup

### Steps to reproduce

run with wine
look at log output

### Expected behavior

something useful :)

Comes from:
https://github.com/compiler-explorer/compiler-explorer/blob/c363d1a07d0cffb05601ad914c3b557fd2be5257/lib/exec.ts#L356
```ts
        logger.info(`Killing any pre-existing wine-server`);
        let result = await child_process.exec(`${server} -k || true`, {env: env});
        logger.info(`Result: ${result}`);
        logger.info(`Waiting for any pre-existing server to stop...`);
        result = await child_process.exec(`${server} -w`, {env: env});
        logger.info(`Result: ${result}`);
```

the two log lines here...either json stringify...or remove...

### Reproduction link

Not applicable

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by guoci**
#4330

### CODE REVIEW

**Comment by partouf** [comment]
I'm not entirely sure about this one. I think we'd like to not wait on these, just delete the logging. Thoughts @mattgodbolt ?

**Comment by mattgodbolt** [comment]
This is fine: if this blocks it's probably better to get an error here and it actually means we'll log something sensible insted of my silly `[Object object]`. That said: deleting is OK too

**Comment by partouf** [comment]
> This is fine: if this blocks it's probably better to get an error here and it actually means we'll log something sensible insted of my silly `[Object object]`. That said: deleting is OK too

Yes, but you changed these to async https://github.com/compiler-explorer/compiler-explorer/pull/3558 intentionally to speed up the instance startup

**Comment by mattgodbolt** [comment]
> > This is fine: if this blocks it's probably better to get an error here and it actually means we'll log something sensible insted of my silly `[Object object]`. That said: deleting is OK too
> 
> Yes, but you changed these to async #3558 intentionally to speed up the instance startup

Oh boy! Er, in that case: let's use a `.then(x=>log...)` or delete them!

**Comment by guoci** [comment]
> I'm not entirely sure about this one. I think we'd like to not wait on these, just delete the logging. Thoughts @mattgodbolt ?

At #3558, I think the intention was to block:
https://github.com/compiler-explorer/compiler-explorer/pull/3558/files#diff-70e99669ad474fc9312f1b4a7a7ace302661b7f14542a52d1ba0966571af0d47R330-R333
But the usage was incorrect, `child_process.exec` doesn't return a promise. The await keyword was later removed at 910d69f233414ebfb0b680e012f44ced14505016 (lint), since it had no effect.

**Comment by partouf** [comment]
> > I'm not entirely sure about this one. I think we'd like to not wait on these, just delete the logging. Thoughts @mattgodbolt ?
> 
> At #3558, I think the intention was to block: https://github.com/compiler-explorer/compiler-explorer/pull/3558/files#diff-70e99669ad474fc9312f1b4a7a7ace302661b7f14542a52d1ba0966571af0d47R330-R333 But the usage was incorrect, `child_process.exec` doesn't return a promise. The await keyword was later removed at [910d69f](https://github.com/compiler-explorer/compiler-explorer/commit/910d69f233414ebfb0b680e012f44ced14505016) (lint), since it had no effect.

I checked our discord history earlier to doublecheck and Matt complained about Wine startup slowing our instance startup down, and it really is noticeable even if it's just a few seconds. And after that the commit was done. So whatever the reason, it used to be execSync or similar and now not anymore. The logging was just forgotten about because sometimes it does log something sane as if everything's fine.

**Comment by mattgodbolt** [comment]
Let's remove it then: we hope to one day wean off of WINE altogether, but it hasn't been a source of issues for so long!

**Review by jeremy-rifkin — APPROVED** [review]
I think this looks good to me, if I am understanding things correctly.

**Comment by partouf** [comment]
is now live

**Pull request merged**
