### PR TITLE
Replace demanglerClassFile with demanglerType

### PR DESCRIPTION
**Pull request by apmorton**
This change aligns demangler type configuration with compiler type configuration.
This is a prerequisite to landing ES6 Modules, because it facilitates elimination of dynamic import statements.

These changes originate from #2132

### CODE REVIEW

**Comment by partouf** [comment]
I understand this is needed. Bit worried about this being a breaking change.

I could think of a few people that may or may not be using this on their own CE instance, but won't be able to name them all. Wonder if we should ping them just to be sure.

The error here https://github.com/compiler-explorer/compiler-explorer/pull/2225/files#diff-cf7015fc34df9efce4e455e54c550070R296 might also be enough

**Comment by partouf** [comment]
Ping @pseyfert @CrustyAuklet @madduci @lanza @dbroemmel @ibuclaw 
Just in case you have CE instances running yourselves.

This is a potentially breaking change if you use/merge/rebase CE after this PR is merged. You will get an error if you're using the `demanglerClassFile` property in your local properties files.

All that's needed to repair, is to replace for example:
`demanglerClassFile=./demangler-cpp`
with
`demanglerType=cpp`

See this PR for more details.

**Review by partouf — APPROVED** [review]

**Comment by partouf** [comment]
Note for ourselves; the Windows team probably needs to be aware of this as well

**Comment by ibuclaw** [comment]
Thanks for the heads up! Seems reasonable to me.

**Pull request merged**
