### PR TITLE
Add the github ureact library

### PR DESCRIPTION
**Pull request by YarikTH**
Proposing to add the µReact library to the live site. https://github.com/YarikTH/ureact

Followed the steps as best as I could in https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md#adding-a-new-library-to-the-live-site

Feedback on improving the hooks and the organizations of files in the repository is welcome.

This PR is related to infra's PR https://github.com/compiler-explorer/infra/pull/1062

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Can you take a look at the errors mentioned in the file. You can run this check locally too: 
```
python3 ./etc/scripts/util/propscheck.py
```
which will help debug and diagnose. Thanks!

**Comment by YarikTH** [comment]
whoops!

```
libs.ureact.versions.main.version=main
libs.ureact.versions.main.path=/opt/compiler-explorer/libs/ureact/main/include
libs.ureact.versions.main.version=dev
libs.ureact.versions.main.path=/opt/compiler-explorer/libs/ureact/dev/include
```

**Comment by YarikTH** [comment]
Fixed and rebased

**Comment by YarikTH** [comment]
Copy comment about versions here. Because it is not cool to be stuck with the current state of branches forever:
https://github.com/compiler-explorer/infra/pull/1062#issuecomment-1669022614

**Comment by YarikTH** [comment]
Now, when nightly build are set up, it seems this PR is ready to merge

**Comment by mattgodbolt** [comment]
Thanks for your patience: we're getting there!

**Pull request merged**
