### PR TITLE
Tsify the parsed_pug_file loader

### PR DESCRIPTION
**Pull request by jeremy-rifkin**

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
`loader: './etc/scripts/parsed_pug_file.ts',` works under `make dev` but not `npx webpack`... I am not sure why. Under webpack-cli the loader is evidently parsed as though it's js.

**Comment by mattgodbolt** [comment]
I _think_ it's probably ok for this to be js still (I don't think it will hold us up...maybe?)

**Comment by partouf** [comment]
Yeah, I think this file is isolated from the rest of the project

**Comment by jeremy-rifkin** [comment]
Indeed. Converting this is not a necessity but figured I’d try. I am still looking for an explanation for why it works for the middleware and not webpack cli.

**Comment by jeremy-rifkin** [comment]
Closing for at least now

**Pull request closed without merging**
