### PR TITLE
Update eslint plugins, heed its warnings; mostly about structuredCloned (TIL)

### PR DESCRIPTION
**Pull request by mattgodbolt**
Also contains:
- `String.raw` (TIL) - in since node.js 4.x
- Typing fixes and `...result` fixes in arg parsers, bug perpetrated by yours truly.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Well, Cypress is unhappy with:
```
    } could not be cloned. {"stack":"DataCloneError: function (property, defaultValue) {\n        return get(base, property, defaultValue);\n    } could not be cloned.\n    at new DOMException (node:internal/per_context/domexception:53:5)\n    at structuredClone (node:internal/structured_clone:23:17)\n    at ClientOptionsHandler.setCompilers (file:///home/runner/work/compiler-explorer/compiler-explorer/lib/options-handler.ts:308:33)\n    at onCompilerChange (file:///home/runner/work/compiler-explorer/compiler-explorer/app.ts:501:36)\n    at main (file:///home/runner/work/compiler-explorer/compiler-explorer/app.ts:506:11)"}
```

**Comment by mattgodbolt** [comment]
so we probably have been json to/fromming all manner of junk that doesn't rounttrip through json since forever

**Comment by partouf** [comment]
So in a couple of these a function gets stored in `CompilerInfo` https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compiler-finder.ts#L330

This is basically a way to get special property settings specific to this context without having to store things in `compiler-finder.ts` (e.g. https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/buildenvsetup/ceconan.ts#L62)

But of course this causes issues when using `structuredClone()`

The function getting lost during copy isn't a problem, because at that point the compilers have already been instantiated including buildenvsetup. That's why `parse(stringify())` wasn't a problem. (although the function gets manually reintroduced when reading a discovery json)

We can probably just use the function directly instead of storing it. Gonna give that a try.

**Comment by partouf** [comment]
Those are fixed and simplified.

But the Tools remain, they are classes (they get replaced again later)

Bit too complicated to fix that at the moment.

Basically I'm still reverting the change in options-handler.

**Comment by mattgodbolt** [comment]
Closing in favour of a (slower) more incremental revamp where necessary (already in progress on another branch...)

**Pull request closed without merging**
