### PR TITLE
Following a  discord discussion, eliminate EventHub.mediateDependentC…

### PR DESCRIPTION
**Pull request by OfekShilon**
…alls.

### CODE REVIEW

**Comment by partouf** [comment]
oh, oops, this broke a frontend unit test it seems

**Comment by OfekShilon** [comment]
> oh, oops, this broke a frontend unit test it seems

What failed? I couldn't see anything

**Comment by partouf** [comment]
> > oh, oops, this broke a frontend unit test it seems
> 
> What failed? I couldn't see anything

https://github.com/compiler-explorer/compiler-explorer/pull/6185#issuecomment-1962527985

**Comment by OfekShilon** [comment]
@partouf  are these tests not included in `make test`? How can i run them locally in the future?

**Comment by partouf** [comment]
It's best to just make branches on the compiler-explorer account+repo instead of your own account, then you have all the tests

**Comment by mattgodbolt** [comment]
> are these tests not included in `make test`

no; unfortunately they're slow and resource-hungry (and a little flakey) so we decided not to make them part of the regular tests

> How can i run them locally in the future?

It's a bit of a pain but [some docs here](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/UsingCypress.md).

**Pull request merged**
