### PR TITLE
LLVM IR pane improvements

### LINKED ISSUE #5062: [REQUEST]: LLVM-IR suggested enhancements
### Is your feature request related to a problem? Please describe

The LLVM-IR contents somewhat lag behind the shiny and new llvm-opt-pipeline view.

### Describe the solution you'd like

(1) When LLVM-IR view is active, it would be helpful to build with `-fno-discard-value-names`. This (most of the time) preserves var names in the IR.

(2) It would be helpful to add the filter checkboxes from llvm-opt-pipeline pane, to optionally declutter the view. At least the removal of debug info is very useful.

Thanks for all your great work!

### Describe alternatives you've considered

Curl up into fetal posture and cry

### Additional context

Not applicable

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
This PR will add filtering and other output options to the LLVM IR pane

image
image

Closes #5062
Related to #5045

### CODE REVIEW

**Comment by OfekShilon** [comment]
Is there anything holding this back from being merged?

**Comment by jeremy-rifkin** [comment]
Just need to implement the stuff on the back end, I've just been slow getting back to this. Got sidetracked with some other stuff 😄

**Review by RubenRBS — APPROVED** [review]

**Comment by jeremy-rifkin** [comment]
Should be about there now, cc @OfekShilon.

I'm not sure I'm entirely happy with the filtering choices / behavior yet

**Comment by OfekShilon** [comment]
> Should be about there now, cc @OfekShilon.

I'm afraid I'm unable to see any difference - not on the live site nor on a local instance. Was this reverted?

**Comment by jeremy-rifkin** [comment]
It hasn’t been merged into the main branch yet

**Review by jeremy-rifkin — COMMENTED** [review]
Alright, updated the filtering behavior and now should be good to go

**Comment by partouf** [comment]
this is now live

**Comment by OfekShilon** [comment]
You guys are the best

**Comment by OfekShilon** [comment]
@jeremy-rifkin  Could it be that the symbol demangling option doesn't work yet?

image

**Comment by jeremy-rifkin** [comment]
Yeah, there's a caching issue (more or less). Fixed it in #5153 but haven't deployed yet.

**Pull request merged**
