### PR TITLE
Rust 1.57.0

### PR DESCRIPTION
**Pull request by ojeda**
Infra: https://github.com/compiler-explorer/infra/pull/640

### CODE REVIEW

**Review by dkm — APPROVED** [review]

**Comment by dkm** [comment]
Thanks ! I'll let @mattgodbolt or @partouf  finish the install :)

**Comment by ojeda** [comment]
You're welcome! :)

**Comment by partouf** [comment]
this is now live

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
