### PR TITLE
update pahole name

### PR DESCRIPTION
**Pull request by madhur4127**
Depends on https://github.com/compiler-explorer/infra/pull/899 and fixes https://github.com/compiler-explorer/compiler-explorer/issues/4405
update pahole version and name

### CODE REVIEW

**Comment by madhur4127** [comment]
@mattgodbolt thanks!

Can you please take a look at PR in infra please?

Because actual pahile version isn't trunk atm

**Comment by mattgodbolt** [comment]
Looks like installing the trunk `pahole` didn't work and has now maybe broken our production `pahole` - https://godbolt.org/z/q3nbcY9hr - I would expect some `pahole` output for this, right?

**Comment by madhur4127** [comment]
Absolutely right.

I used the code from the broken MR: https://compiler-explorer.com/z/1P4zdjcY5

No output: https://godbolt.org/z/W4eh3qhrW

One strange thing is that, in the `Add tool` drop down, I still see `pahole` but I should see `pahole (trunk)`

**Comment by mattgodbolt** [comment]
I haven't pushed the rename to prod yet - only our staging instance has that change - our staging instance is up at https://godbolt.org/staging

However, the binary is shared, so when I updated it, it immediately affecting the prod environment.

**Comment by mattgodbolt** [comment]
I'm going to roll back the change and reinstall the old version for now.

**Comment by mattgodbolt** [comment]
(if only to see if that fixes things)

**Comment by mattgodbolt** [comment]
The old build is failing!

```
/tmp/build/pahole/dtagnames.c: In function ‘print_malloc_stats’:
/tmp/build/pahole/dtagnames.c:17:16: error: ‘mallinfo’ is deprecated [-Werror=deprecated-declarations]
   17 |         struct mallinfo m = mallinfo();
      |                ^~~~~~~~
```

will hack something

**Comment by mattgodbolt** [comment]
Ok I got the old version built

But it still isn't working: https://compiler-explorer.com/z/MWfqn4onq

I have no idea now, and unfortunately I have to do my day job. I'll try and look later

**Comment by mattgodbolt** [comment]
Ok! I realise what it is now - it's not your fault at all @madhur4127 !

```
ubuntu@ip-172-30-0-108:~$ /opt/compiler-explorer/pahole/bin/pahole
/opt/compiler-explorer/pahole/bin/pahole: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/compiler-explorer/pahole/bin/pahole)
/opt/compiler-explorer/pahole/bin/pahole: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/compiler-explorer/pahole/lib/libdwarves.so.1)
/opt/compiler-explorer/pahole/bin/pahole: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/compiler-explorer/pahole/lib/libdw.so.1)
/opt/compiler-explorer/pahole/bin/pahole: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/compiler-explorer/pahole/lib/libdw.so.1)
/opt/compiler-explorer/pahole/bin/pahole: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/compiler-explorer/pahole/lib/libelf.so.1)
```

we updated our main node to be ubuntu 22.04, but our workers are still on 20.04.  We need to port this to our build infrastructure instead of the head node! I'll look at this at lunch!

**Comment by madhur4127** [comment]
oh, I was scratching my head as to why it didn't work 😭. Thank you so much for looking into this!

I use U22 locally so I didn't observe this bug when I tested my changes. Apologies!

**Comment by mattgodbolt** [comment]
@madhur4127 there's literally no way at all you could have known! this is a latent issue on our side! Thanks for your patience: I'm trying to fix this preoprly now (I am going to be late to work heheh)

**Comment by madhur4127** [comment]
thanks for the kind words! 

You could say you took too long to decide what to wear hahaha

**Comment by mattgodbolt** [comment]
pahole is back and is running at trunk, and should build daily! Phew :) Thanks again for this, I'll be updating the site to say "pahole (trunk)" shortly

**Pull request merged**
