### PR TITLE
Pull Request: `nasm-hello.asm` -> `hello_nasm.asm`

### PR DESCRIPTION
**Pull request by TaiHusk**

### CODE REVIEW

**Comment by mattgodbolt** [comment]
This is now live

**Comment by partouf** [comment]
ugh this is now duplicated instead of renamed

**Comment by mattgodbolt** [comment]
I will fix.

**Comment by mattgodbolt** [comment]
Actually I just reverted. If someone wants to try again, feel free (or let me know why this needed renaming in the first place?)

**Comment by mattgodbolt** [comment]
See 19ed6d000

**Comment by TaiHusk** [comment]
> See [19ed6d0](https://github.com/compiler-explorer/compiler-explorer/commit/19ed6d000e2a6e5ecbf0bd1acbc16709bcd1ccc5)

Oops, you seem to have misunderstood a bit. I should have removed 'hello-nasm.asm' because in the GUI the '-' character is displayed from the filename, since 'hello_nasm.asm' is displayed in the GUI as 'hello nasm'.

**Comment by mattgodbolt** [comment]
Thank you for clarifying. We would welcome a PR to rename to fix this, but I have limited time to fix up other folks' PRs so I tend to revert mistaken changes instead of trying to repair thing.

**Pull request merged**
