### PR TITLE
Support LLVM IR filters for the output of `mlir-translate`

### PR DESCRIPTION
**Pull request by MacDue**
This enables the LLVM IR filters for the output of `mlir-translate` (with `-mlir-to-llvmir`). The filters are still disabled for `mlir-opt` (which only outputs MLIR) as there's currently no support for MLIR filtering.

### CODE REVIEW

**Comment by OfekShilon** [comment]
Thanks for submitting this!  
Did you try just passing an empty `disabledFilters` to `MLIRCompiler.constructor`? If yes, can you please elaborate on what didn't work?

**Comment by partouf** [comment]
Regarding the `languageId` / `getCompilerResultLanguageId` change; I think it would be better to use detection of language during the parsing process unless it's really not possible.

**Comment by MacDue** [comment]
> Regarding the `languageId` / `getCompilerResultLanguageId` change; I think it would be better to use detection of language during the parsing process unless it's really not possible.
> 
> (I know this is probably my fault for adding `getCompilerResultLanguageId` probably, but it was only meant to return a default)

Those changes can be dropped for now (that was more needed for my prototype of #6882). The filters work without it as the language can be detected from the options/output.

**Comment by mattgodbolt** [comment]
Did you drop those changes? It's not easy to tell (the force push upsets the nice comment history)

**Comment by MacDue** [comment]
> Did you drop those changes? It's not easy to tell (the force push upsets the nice comment history)

I did 😄

**Review by junlarsen — APPROVED** [review]

**Comment by junlarsen** [comment]
Sorry for taking so long, thanks!

**Pull request merged**
