### PR TITLE
Re-enable rescan when launched with pre-discovered compiler list

### PR DESCRIPTION
**Pull request by igor-makarov**
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/3858

### CODE REVIEW

**Comment by igor-makarov** [comment]
@partouf I've update the PR with the persistence logic that I proposed in #3858. 

This means that compilers won't be removed if they are no longer available. For this, a redeploy would be needed. However, this is also the case right now.

**Comment by partouf** [comment]
Could be a solution, I'll give it some thought

**Comment by igor-makarov** [comment]
Thank you @partouf!

**Comment by igor-makarov** [comment]
@partouf sorry to bother you, but after you ran the CI, I noticed it failed on a test.

I made a change to fix it but the CI won't re-run due to first time contributor status.

**Comment by partouf** [comment]
I just realized this isn't really going to work either, because newly launched instances will have the wrong versions until the rescan hits.
I think we should go in a different direction on this.

**Comment by igor-makarov** [comment]
@partouf I've added a boot-time rescan to address the issue you mentioned. It runs async after boot completes, so it does not block it.

**Comment by mattgodbolt** [comment]
Hi! Thanks so much for this. I agree with Partouf (though not necessarily on the direction, we'll chat) -- my concern about this approach is that when a new node boots up it will immediately read the (old) information. Eventually it will refresh (async after boot like you said), but in the meantime it will have old information. As we cycle nodes quite often, this means there's a decent chance the nodes on the site will all disagree on what versions we have around. That's not the end of the world, admittedly, but it's a step into making our (already problematic) inconsistencies greater.

That all said: this might be a pragmatic stepping stone to make things better in the short term. We'll discuss on the Discord! Thanks!

**Comment by mattgodbolt** [comment]
Sorry we still don't have a good solution for this. I have gotten very much behind on a bunch of things. We do want to fix this still, so this is just an apology for not having done so yet still.

**Comment by igor-makarov** [comment]
Thank you for the update @mattgodbolt! Keep up the good work, this project has been an amazing thing---thank you for it!

**Comment by RubenRBS** [comment]
Hi! We are going to go back to the drawing board for this and other releated issues, so unfortunately this PR is not something we'll merge. Either way, thanks a lot for all your work on this, we really appreciate :)

**Pull request closed without merging**
