### PR TITLE
Add NVHPC SDK 22.11

### PR DESCRIPTION
**Pull request by trxcllnt**
Related infra PR: https://github.com/compiler-explorer/infra/pull/877

### CODE REVIEW

**Comment by RubenRBS** [comment]
Merging this now, should be live soon-ish. Thanks again!

**Comment by RubenRBS** [comment]
Quick question: Was the arm variant not updated on pourpose? I was adding some props in #4304 and noticed it's missing

**Comment by partouf** [comment]
this is now live

**Comment by trxcllnt** [comment]
@RubenRBS yes, unfortunately the ARM version of NVHPC SDK installer checks the machine platform and error's out if it's not an `aarch64` CPU. Since the CE compilers are installed on an x86 machine, we can't install the ARM SDK unless they lift this restriction (or CE can run the installer on ARM/in QEMU).

**Comment by RubenRBS** [comment]
Oh, thanks for the clarification!

We're playing around with the idea of adding native arm instances to the environment, so this is something that might be doable in the future

**Pull request merged**
