### PR TITLE
Add Thrust/CUB 1.11.0.

### PR DESCRIPTION
**Pull request by allisonvacanti**
Adds new versions of the CUDA Thrust/CUB libraries.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Looks great. Thanks again. Will get deployed with the next update (once the install happens in infra etc etc :)

**Comment by mattgodbolt** [comment]
For your amusement, and beyond off-topic, every time I see "Thrust" I think of this: https://bbc.godbolt.org/?&disc1=sth%3ASuperior%2FThrust.zip&autoboot

**Comment by allisonvacanti** [comment]
That's just eerie, it references cub, too xD

image

Thanks for getting this in so quickly!

**Comment by mattgodbolt** [comment]
it does! :ghost: spoooooky! :)

**Comment by mattgodbolt** [comment]
More importantly (and relevantly); I've this should be online now, I've just pushed the latest version to the live site.

**Comment by allisonvacanti** [comment]
Tested it out, and everything is working as expected 👍 Thanks again! I'm always impressed by how quickly ya'll get things done :)

**Comment by mattgodbolt** [comment]
Thanks @allisonvacanti . In honesty this time was lucky chance (plus an easy-to-merge PR; thank you!)... so much stuff in the backlog... (/me tries not to get disheartened by the 364 open issues...)

**Pull request merged**
