### PR TITLE
Make Rust examples more idiomatic

### PR DESCRIPTION
**Pull request by redzic**
Hi,

I adjusted some of the Rust examples here to make them more idiomatic. The Sum over array non-idiomatic versions have both been made to be more idiomatic, although they still use manual pointer manipulation to generate slightly fewer instructions. These examples still generate the same assembly on rustc 1.51 with compiler flags `-C opt-level=3 -C target-cpu=znver2`. The square executable example has also been adjusted, and it actually generates much fewer instructions (around ~500 down to ~200 on default x86 target).

~~Actually, it might even be worth removing the non-idiomatic aligned example, because it seems to generate the exact same assembly as the non-aligned version on both x86 and `aarch64-unknown-linux-gnu`.~~ (not true on default x86 target, but seems true for newer targets like znver{1,2,3})

### CODE REVIEW

**Comment by RubenRBS** [comment]
Hi! Thank you for taking the time to improve the state of Rust on CE, we really appreciate it!

Unfortunately, while there might be something to be said about the Square_executable.rs existing code, the rest of the changes of this PR are a bit misguided, and we can't merge it, as their main change is to make code be more idiomatic in files named "non-idiomatic"! 
The main pourpose of those files is to show how diferent code compiles as an starting example for those who want to dig about, so having the code be like it currently is valuable on our eyes.

Again, I'm thankful that you spent your time trying to improve things, but as it stands, I'm against merging this PR. But! Maybe we can work on adding an alternative to the already existing idiomatic example  :)

**Comment by redzic** [comment]
Hi, I'm actually the one who originally wrote the non-idiomatic Rust examples for those sum functions (https://github.com/compiler-explorer/compiler-explorer/issues/2133). At the time of writing the examples, I was just trying to get the generated assembly to be as close as possible to the "Sum over array (Optimized)" C++ example when compiling with clang and -O3. I think my changes are still considered unidiomatic, since they use raw pointers directly to save a few instructions before the main loop. In Rust code, it the norm to write code like this using functional constructs like iterators, maps, filters, etc, even when using unsafe code. There's rarely ever a need to write those styles of loops manually. The main point of those examples that I changed, in my opinion, are to showcase the use of raw pointers and `unsafe` code and how that affects the generated assembly, and not the style of the loop (which doesn't affect the generated assembly). I think that in general, the examples should probably reflect how typical code may be written and therefore it should probably be ok to use those language features.

I think that the examples should probably be renamed though.
Maybe it could be something like this to more accurately reflect the point of each of the examples:
`Sum over array (Non-idiomatic aligned)` -> `Sum over array (Raw pointers, aligned)`
`Sum over array (Non-idiomatic)` -> `Sum over array (Raw pointers)`
`Sum over array (Optimized)` -> `Sum over array (Aligned)`
`Sum over array (Unreachable)` -> `Sum over array (Unsafe)` (or maybe just keep the name as "Unreachable")

**Comment by RubenRBS** [comment]
:$ Sorry about not recognizing nor checking your past commits beforehand!

I do actually agree with you in that we should also provide examples that show typical code you are likely to find, but I would still keep the existing examples around. Im now worried that the UI might not be able to handle any valuable improvement we can make in that area. As for example, your naming idea, which seems great to me! 

Again, there needs to be some care taken with the UI, but that sounds like a great first step :)

Again, thank you for your time!

**Comment by partouf** [comment]
> I think that the examples should probably be renamed though.
> Maybe it could be something like this to more accurately reflect the point of each of the examples:
> `Sum over array (Non-idiomatic aligned)` -> `Sum over array (Raw pointers, aligned)`
> `Sum over array (Non-idiomatic)` -> `Sum over array (Raw pointers)`
> `Sum over array (Optimized)` -> `Sum over array (Aligned)`
> `Sum over array (Unreachable)` -> `Sum over array (Unsafe)` (or maybe just keep the name as "Unreachable")

Can you rename these to match this? (spaces are underscored)

**Comment by redzic** [comment]
examples have been renamed

**Comment by partouf** [comment]
this is now live

**Pull request merged**
