### PR TITLE
Add ClangIR output for clangir compiler

### PR DESCRIPTION
**Pull request by Lancern**
Currently the clangir compiler is implemented by a special clang variant whose compilation options list gets appended with `-Xclang -fclangir -Xclang -emit-cir`. This introduces a problem: we no longer gets access to its LLVM IR output and assembly output because `-emit-cir` is an exclusive option.

This patch resolves this problem by introducing a new ClangIR pane, similar to the LLVM IR pane or Rust MIR pane. A new output kind named `ClangIR` is added to the "Add new..." drop down menu and it toggles the ClangIR pane. This patch then removes `-Xclang -emit-cir` from the options list of the clangir compiler. The clangir compiler will then output assembly code just like other clang compilers. The removed options will be added back when compiled from the ClangIR pane.

### CODE REVIEW

**Comment by bcardosolopes** [comment]
Not sure how easy is this (or if it's relevant to this PR), but is it possible to get CIR output to have the syntax highlighting as MLIR has in compiler explorer?

**Comment by Lancern** [comment]
> Not sure how easy this is (or if it's relevant to this PR), but is it possible to get CIR output to have the syntax highlighting as MLIR has in compiler explorer?

This PR should have already considered this. It sets the language syntax of the Monaco editor in the ClangIR pane to `mlir`. See `static/panes/clangir-view.ts:56`.

**Comment by bcardosolopes** [comment]
Awesome, thanks for the clarification (and for adding this)

**Comment by OfekShilon** [comment]
Thank you very much for this contribution! 
All the places where it touches common source files seem to not interfere with other compilers, so it looks safe enough to merge. We'd appreciate if you'd be available for potential fixes if any issues arise after deployment.

**Comment by Lancern** [comment]
@OfekShilon Thanks for your review and approval!

> We'd appreciate if you'd be available for potential fixes if any issues arise after deployment.

I'll follow up on this as the community also has some further clangir flags / options they want to make available on compiler explorer.

**Comment by partouf** [comment]
this is now live

**Pull request merged**
