### PR TITLE
Revert "Tsify rison.js (#4510)"

### PR DESCRIPTION
**Pull request by partouf**
This reverts commit e1cc30941d68aed64440b1aa0172029b48d639a7.

### CODE REVIEW

**Comment by partouf** [comment]
Testing this locally, but; URL that I'm testing seems undecodable on the LZString level part of the decode, not in the rison parts

**Comment by partouf** [comment]
does fix #4521

**Review by mattgodbolt — APPROVED** [review]
Sounds like a pragmatic solution for now: we can revert the revert and fix it up after. thanks!

**Comment by partouf** [comment]
now live

**Comment by jeremy-rifkin** [comment]
This doesn't fix #4521

**Pull request merged**
