### PR TITLE
Add clang-rocm 6.0.2 and 6.1.2 for C++

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Looks good; thank you for all this work!

**Comment by yxsamliu** [comment]
also added rocm 6.0.2/6.1.2 for CUDA

**Comment by yxsamliu** [comment]
fixed an empty separator

**Review by mattgodbolt — APPROVED** [review]

**Comment by yxsamliu** [comment]
Thanks for merging the PR. I still did not see them in the compiler-explorer web site. Anything else needs to be done for them to show up in compiler-explorer web site? Thanks.

**Comment by partouf** [comment]
it will be a bit longer, but I will push the changes to the site later day

**Comment by dkm** [comment]
This is now live :rocket:

**Comment by yxsamliu** [comment]
Thanks for adding them to compiler-explorer. I can see them in the UI. However, 6.0.2 and 6.1.2 seems not working due to missing directories /opt/compiler-explorer/libs/rocm/6.0.2 and /opt/compiler-explorer/libs/rocm/6.1.2. Did I miss something?

https://godbolt.org/z/Yj5dv3ne6

**Pull request merged**
