### PR TITLE
Add support for Microsoft Visual C++ 6

### PR DESCRIPTION
**Pull request by kadler**
Not sure how useful it is, but I managed to get MSVC6 working with
Compiler Explorer, so I figured I'd share my changes. MSVC6 can be
installed on Windows 10 with some coaxing and works fine in my
basic testing. I copied the existing MSVC files and made changes there
instead of trying to merge the two. That might be possible, I'm just not
well versed enough to know how to do it cleanly and if the changes
weren't going to be accepted I was going to to waste time on it.

Example MSVC6 assembly output:
```
        TITLE   example.cpp
        .386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT   SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT   ENDS
_DATA   SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA   ENDS
CONST   SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST   ENDS
_BSS    SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS    ENDS
_TLS    SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS    ENDS
FLAT    GROUP _DATA, CONST, _BSS
        ASSUME  CS: FLAT, DS: FLAT, SS: FLAT
endif
PUBLIC  ?square@@YAHH@Z                                 ; square
_TEXT   SEGMENT
_x$ = 8
?square@@YAHH@Z PROC NEAR                               ; square
; File example.cpp
; Line 1
        push    ebp
        mov     ebp, esp
; Line 2
        mov     eax, DWORD PTR _x$[ebp]
        imul    eax, DWORD PTR _x$[ebp]
; Line 3
        pop     ebp
        ret     0
?square@@YAHH@Z ENDP                                    ; square
_TEXT   ENDS
PUBLIC  _main
_TEXT   SEGMENT
_main   PROC NEAR
; Line 5
        push    ebp
        mov     ebp, esp
; Line 6
        push    42                                      ; 0000002aH
        call    ?square@@YAHH@Z                         ; square
        add     esp, 4
; Line 7
        pop     ebp
        ret     0
_main   ENDP
_TEXT   ENDS
END
```

### CODE REVIEW

**Comment by kadler** [comment]
BTW, here's the diff between the existing asm parser and the vc6 parser:
```diff
--- lib/asm-parser-vc6.js       2021-08-31 16:13:54.228569982 -0500
+++ lib/asm-parser-vc.js        2021-08-27 10:19:14.315128681 -0500
@@ -27,17 +27,17 @@
 import { logger } from './logger';
 import * as utils from './utils';
 
-export class Vc6AsmParser extends AsmParser {
+export class VcAsmParser extends AsmParser {
     constructor(compilerProps) {
         super(compilerProps);
         this.asmBinaryParser = new AsmParser(compilerProps);
-        this.miscDirective = /^\s*(include|INCLUDELIB|TITLE|\.|else$|endif$|if @Version|FLAT|ASSUME|THUMB|ARM64|TTL|END$)/;
+        this.miscDirective = /^\s*(include|INCLUDELIB|TITLE|\.|THUMB|ARM64|TTL|END$)/;
         this.localLabelDef = /^([$A-Z_a-z]+) =/;
         this.commentOnly = /^;/;
         this.filenameComment = /^; File (.+)/;
         this.lineNumberComment = /^; Line (\d+)/;
-        this.beginSegment = /^(CONST|_BSS|_DATA|_TLS|\.?[prx]?data(\$[A-Za-z]+)?|CRT(\$[A-Za-z]+)?|_TEXT|\.?text(\$[A-Za-z]+)?)\s+SEGMENT|\s*AREA/;
-        this.endSegment = /^(CONST|_BSS|_DATA|_TLS|[prx]?data(\$[A-Za-z]+)?|CRT(\$[A-Za-z]+)?|_TEXT|text(\$[A-Za-z]+)?)\s+ENDS/;
+        this.beginSegment = /^(CONST|_BSS|\.?[prx]?data(\$[A-Za-z]+)?|CRT(\$[A-Za-z]+)?|_TEXT|\.?text(\$[A-Za-z]+)?)\s+SEGMENT|\s*AREA/;
+        this.endSegment = /^(CONST|_BSS|[prx]?data(\$[A-Za-z]+)?|CRT(\$[A-Za-z]+)?|_TEXT|text(\$[A-Za-z]+)?)\s+ENDS/;
         this.beginFunction = /^; Function compile flags: /;
         this.endProc = /^([$?@A-Z_a-z][\w$<>?@]*)?\s+ENDP/;
         // on x86, we use the end of the segment to end a function
@@ -156,12 +156,12 @@
         };
 
         const checkBeginFunction = (line) => {
-            if (this.definesFunction.test(line)) {
+            if (this.beginFunction.test(line)) {
                 currentFunction = {
                     lines: [],
                     initialLine: undefined,
                     name: undefined,
-                    file: currentFile,
+                    file: undefined,
                 };
                 resultObject.functions.push(currentFunction);
             }
```

**Comment by partouf** [comment]
I think this is great, (even though it probably won't appear on the website anytime soon)

I was considering whether or not the parser should extend from VcAsmParser, but that one might change in the future while this one won't. So I think this is fine as is.

**Review by partouf — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Thanks! A test or two to ensure we don't break it would be great; but I don't midn merging this as-is :) Thanks for the work - I'd love to get VS6 on the site but I do'nt know how likely that will be. I'll mention it to our friends who administrate the Windows side of things.

**Comment by kadler** [comment]
Thanks!

I noticed that for VS2005 and VS2008 that only the first function shows up. I have to uncheck Filter->Library Functions to show the rest. I'm guessing they'll need similar fixes to VC6 (maybe related to filename parsing?). When I get time, I'll try to figure it out, add some tests, and send a PR.

**Pull request merged**
