### PR TITLE
Add rustfmt as code formatting tool for Rust

### PR DESCRIPTION
**Pull request by supergrecko**
Rust code is now formattable out-of-editor like Clang-Format does for C/C++

image

I'm working on adding the Ctrl + F9 monaco editor keybinding we have to run clang-format for rustfmt, but it looks like a nontrivial task so I'll leave that out of this patch.

See #2564

Infra: https://github.com/compiler-explorer/infra/pull/560

### CODE REVIEW

**Comment by partouf** [comment]
If you want, you can add maybe a fake argument (`--fix` or something) that sets the tool's `result.sourcechanged` (`true` if format was succesful) and `result.newsource` (to the output). That will change the editor's source automatically after the results are in.

**Review by partouf — APPROVED** [review]

**Comment by supergrecko** [comment]
> If you want, you can add maybe a fake argument (`--fix` or something) that sets the tool's `result.sourcechanged` (`true` if format was succesful) and `result.newsource` (to the output). That will change the editor's source automatically after the results are in.

Interesting... I think it's best if we keep the current behaviour with the format tools not editing the source editor and leave that for the Ctrl + F9 keybinding.

Currently performing a bit of internal surgery on the format API handler, making it able to handle multiple formatters.

**Comment by mattgodbolt** [comment]
> Interesting... I think it's best if we keep the current behaviour with the format tools not editing the source editor and leave that for the Ctrl + F9 keybinding.

Agreed there :)

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Thanks @supergrecko - gonna merge. Ping me on slack and we can try and work through the autoformat. The formatting stuff was added before we separated by language, so it's rather hardcoded for C++ currently.

**Comment by mattgodbolt** [comment]
This is now live :)

**Pull request merged**
