### PR TITLE
Fix #4931 and #2218

### LINKED ISSUE #4931: [BUG]: Lines with local labels in gcc inline assembly are silently skipped
### Describe the bug

[Local labels](https://sourceware.org/binutils/docs/as/Symbol-Names.html) (i.e. those with names consisting of digits) are silently skipped in the output code. Tested with ARM gcc, but other gcc targets are also likely affected.

### Steps to reproduce

1. Visit godbolt.org
2. Paste following code into the source pane:
```
#define MTX_UNLOCKED 1
#define MTX_LOCKED 0

void lock(unsigned int *mtx)
{
    asm volatile(
        "mov r3, %1\n"
        "1:\tswp r3, r3, [%0]\n\t"
        "cmp r3, %1\n\t"
        "beq 1b"
    :
    : "r"(mtx), "i"(MTX_LOCKED)
    : "r3", "cc", "memory");
}

void lock2(unsigned int *mtx)
{
    asm volatile(
        "mov r3, %1\n"
        "1:\n\t"
        "swp r3, r3, [%0]\n\t"
        "cmp r3, %1\n\t"
        "beq 1b"
    :
    : "r"(mtx), "i"(MTX_LOCKED)
    : "r3", "cc", "memory");
}
```
3. Choose "ARM gcc 11.2.1 (none)" compiler
4. Add "-O3 -march=armv4t -pedantic -Wall -Wextra" to the compiler options
5. The output pane will show code without labels:
```
lock:
        mov r3, #0
        cmp r3, #0
        beq 1b
        bx      lr
lock2:
        mov r3, #0
        swp r3, r3, [r0]
        cmp r3, #0
        beq 1b
        bx      lr
```

### Expected behavior

The output pane should show code with local labels:
```
lock:
        mov r3, #0
1:	swp r3, r3, [r0]
        cmp r3, #0
        beq 1b
        bx      lr
lock2:
        mov r3, #0
1:
        swp r3, r3, [r0]
        cmp r3, #0
        beq 1b
        bx      lr
```

### Reproduction link

https://godbolt.org/z/jbrW9jMG6

### Screenshots

Not applicable

### Operating System

_No response_

### Browser version

_No response_

### PR DESCRIPTION
**Pull request by OfekShilon**
I saw the discussion in #2034 and the other linked issues. AFAICT this small PR solves only these two (4931 & 2218).

### CODE REVIEW

**Comment by mattgodbolt** [comment]
This seems to cause some tests to fail: can you take a look and see if those appear to be improvements or not... e.g.

```
* Showing diff for /home/runner/work/compiler-explorer/compiler-explorer/test/filters-cases/avr-loop.asm.none.approved.txt vs /home/runner/work/compiler-explorer/compiler-explorer/test/filters-cases/avr-loop.asm.none.received.txt
...
```

That seems to be a change we wouldn't want, I think?

**Comment by OfekShilon** [comment]
@mattgodbolt  yes sorry, I saw these but won't be able to work on them further at least until the weekend. Should I close the PR until I can submit a new one in better state?

**Comment by OfekShilon** [comment]
@mattgodbolt I added 82 changed filter tests and checked ~10 of them - it seems like the fix was indeed needed. 

GAS for MIPS occasionally generates weird labels like -
```
$LFB0 = .
```
(cf [here](https://gcc.godbolt.org/z/T8Pae7o7T)). These could be considered as symbols initialized to hold their location, but are interchangeable with labels. See discussion [here](https://stackoverflow.com/questions/60966030/gcc-for-mips-emits-assembly-label-with) and GAS reference [here](https://ftp.gnu.org/old-gnu/Manuals/gas-2.9.1/html_chapter/as_5.html#SEC49).  Personally I'm comfortable with considering them a label.

**Comment by partouf** [comment]
> @mattgodbolt I added 82 changed filter tests and checked ~10 of them - it seems like the fix was indeed needed.
> 
> GAS for MIPS occasionally generates weird labels like -
> 
> ```
> $LFB0 = .
> ```
> 
> (cf [here](https://gcc.godbolt.org/z/T8Pae7o7T)). These could be considered as symbols initialized to hold their location, but are interchangeable with labels. See discussion [here](https://stackoverflow.com/questions/60966030/gcc-for-mips-emits-assembly-label-with) and GAS reference [here](https://ftp.gnu.org/old-gnu/Manuals/gas-2.9.1/html_chapter/as_5.html#SEC49). Personally I'm comfortable with considering them a label.

I believe we call these assignments, follows this regex https://github.com/compiler-explorer/compiler-explorer/blob/286e83530d9a333137093008c17e46f3f690b636/lib/parsers/asm-parser.ts#L113

**Comment by OfekShilon** [comment]
> I believe we call these assignments, follows this regex
> 
> https://github.com/compiler-explorer/compiler-explorer/blob/286e83530d9a333137093008c17e46f3f690b636/lib/parsers/asm-parser.ts#L113

Great, so no additional fix is needed for there.

I'm not sure about the `labelDef` regex here:
https://github.com/compiler-explorer/compiler-explorer/blob/286e83530d9a333137093008c17e46f3f690b636/lib/parsers/asmregex.ts#L34

I never came across `*proc `-prefixed labels, but if they're out there - the current addition to the asm-parser logic won't work on them. (the added condition `match[0] === line` would be false). Do you know where I might test on such labels?

**Comment by partouf** [comment]
> > I believe we call these assignments, follows this regex
> > https://github.com/compiler-explorer/compiler-explorer/blob/286e83530d9a333137093008c17e46f3f690b636/lib/parsers/asm-parser.ts#L113
> 
> Great, so no additional fix is needed for there.
> 
> I'm not sure about the `labelDef` regex here:
> 
> https://github.com/compiler-explorer/compiler-explorer/blob/286e83530d9a333137093008c17e46f3f690b636/lib/parsers/asmregex.ts#L34
> 
> I never came across `*proc `-prefixed labels, but if they're out there - the current addition to the asm-parser logic won't work on them. (the added condition `match[0] === line` would be false). Do you know where I might test on such labels?

I think this might be for cc65-ish compiler https://regexr.com/7n24r
Found example asm here https://forums.atariage.com/topic/296494-calling-asm-proc-from-c/

But we have a custom parser for this https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/asm-parser-cc65.ts

So it could safely be removed from labelDef, I think, but I believe @mattgodbolt might have concocted this regex decades ago...

**Comment by OfekShilon** [comment]
> But we have a custom parser for this https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/parsers/asm-parser-cc65.ts
> 
> So it could safely be removed from labelDef, I think, but I believe @mattgodbolt might have concocted this regex decades ago...

So the current PR would not cause regressions there too and AFAICT it is safe. I leave the potential cleanup of `labelDef` to the more knowledgeable.

**Comment by partouf** [comment]
Hm, I'm seeing in the diff's that this also adds a lot of dwarf directives that probably should have been filtered out, but I guess they only disappeared because of this bug.

We might want to do some extra effort to filter those out properly with the directives filter (even if used).

But I think we can do that later

**Comment by OfekShilon** [comment]
> Hm, I'm seeing in the diff's that this also adds a lot of dwarf directives that probably should have been filtered out, but I guess they only disappeared because of this bug.

I see assignments that are now considered labels (mentioned above) but couldn't find dwarf directives. Can you please link to one?

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/pull/5706/files#diff-9caf69c04d977b532e1c9ece681deb2e9b2600dde82f635de625a4ade739be4aR115

**Comment by OfekShilon** [comment]
We might be referring to the same thing. Are you talking about things like `.Lset1 = .Linfo_end1-.Linfo_begin1`?

Actually I think it's safe to exclude occurrences of ` = ` from the label regex. I'll do that some time soon.

**Comment by mattgodbolt** [comment]
Thanks @OfekShilon :)

**Pull request merged**
