### PR TITLE
Rust 1.70.0

### PR DESCRIPTION
**Pull request by ojeda**
Infra: https://github.com/compiler-explorer/infra/pull/1025

### CODE REVIEW

**Review by RubenRBS — APPROVED** [review]

**Comment by mattgodbolt** [comment]
I did a site update that should have picked this up, but the rust compilers hadn't been installed on our nodes: I'm now fixing this and will re-update! Should be live shortly: thanks!

**Comment by mattgodbolt** [comment]
I just did the changes but 1.70.0 isn't turning up, and I can't work out why....I am going to have to bail til tomorrow as it's late here

**Comment by mattgodbolt** [comment]
I'm hoping it's some aggressive caching and when I wake up it'll all Just Work™

**Comment by mattgodbolt** [comment]
worked out what it was. PEBKAC, should appear in the next hour...

**Comment by ojeda** [comment]
Thanks Matt!

**Pull request merged**
