### PR TITLE
Add vast-trunk compiler

### PR DESCRIPTION
**Pull request by xlauko**
More context in https://github.com/compiler-explorer/infra/pull/1209

### CODE REVIEW

**Comment by xlauko** [comment]
Is there a method to offer preset arguments that users can modify, similar to `unwiseOptions`, but without receiving a warning? VAST can generate various MLIR outputs, and their configuration is determined by `-vast-emit-mlir=<dialect>`. It would be convenient to have this set by default but also allow users to customize the target dialects.

**Review by mattgodbolt — COMMENTED** [review]
This seems like it's ready to go?

**Comment by mattgodbolt** [comment]
Oh sorry!
>  Is there a method to offer preset arguments that users can modify, similar to unwiseOptions, but without receiving a warning? VAST can generate various MLIR outputs, and their configuration is determined by -vast-emit-mlir=<dialect>. It would be convenient to have this set by default but also allow users to customize the target dialects.

There is not, no. We've debated this a lot but there's not a good UI for it. As users switch between compilers we don't want to keep adding and removing options from their commandline as that is annoying and likely wrong.

**Comment by xlauko** [comment]
Then it is good to go. Thanks for help :)

**Review by mattgodbolt — APPROVED** [review]
Awesome!

**Comment by mattgodbolt** [comment]
I'm testing on our staging instance and:

```
[VAST Error] Failed to convert type: si32
PLEASE submit a bug report to https://github.com/trailofbits/vast/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/vast-trunk/bin/vast-front -g -o /app/output.s -mllvm -x86-asm-syntax=intel -S -std=c++20 <source>
1.	<eof> parser at end of file
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM-17.so.1 0x00007f1458666406 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 54
1  libLLVM-17.so.1 0x00007f14586645b0 llvm::sys::RunSignalHandlers() + 80
2  libLLVM-17.so.1 0x00007f14585bad70
3  libc.so.6       0x00007f1457242520
4  vast-front      0x000055cbbe4b16d5
vast-front: error: clang frontend command failed with exit code 133 (use -v to see invocation)
Ubuntu clang version 17.0.6 (++20231209124227+6009708b4367-1~exp1~20231209124336.77)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/vast-trunk/bin
vast-front: error: unable to execute command: Aborted (core dumped)
vast-front: note: diagnostic msg: Error generating preprocessed source(s).
Compiler returned: 1
```

with source `int moo = 2;` -- I will probably continue to roll this out to production if only to give something to start with and improve on :)

But if you are around in the next 10-15m -> https://godbolt.org/staging/z/GK5ev1o1s is the link I'm using

**Comment by mattgodbolt** [comment]
An empty `void moo() {}` works, but `int moo() { return 3; }` does not.

**Comment by mattgodbolt** [comment]
This is now live on the main site: let me know if I can help diagnose what's going on. Could easily be the dodgy build I made.

**Comment by partouf** [comment]
I noticed with using `-v` it was using the system's gcc and headers, which might be too old, I added a recent `--gcc-toolchain` and I think that fixes the problem: https://godbolt.org/z/W4hb8qb7Y

**Comment by partouf** [comment]
oh, `-S` still doesn't work with that, only link to binary works

**Comment by xlauko** [comment]
> But if you are around in the next 10-15m -> https://godbolt.org/staging/z/GK5ev1o1s is the link I'm using

Sorry, my EU hours did not overlap anymore. I am looking into that now :)

But in general, vast is still missing lot of lowering to assembly. Generating only `mlir` seems to work, with `-vast-emit-mlir=hl` option to emit high level dialect for C/C++.

**Comment by xlauko** [comment]
`vast-front -g -o test.s -mllvm -x86-asm-syntax=intel -v -S ./test.c` with `int moo() { return 3; }` works locally, at least on my machine with. So might be problem with the toolchain.

However, I am confused with our error there, and have no idea how toolchain solved that:

```
[VAST Error] Failed to convert function type: !core.fn<() -> (si32)>
[VAST Error] Failed to convert func arguments
```

**Comment by xlauko** [comment]
Found some UB and small issues on our side. CE installation should be fine :)

**Comment by lkorenc** [comment]
We merged some changes addressing issues raised in this thread :)
Hopefully nothing new will pop out after rebuild and all will be working as intended.

**Pull request merged**
