### PR TITLE
Fix the cuda and microsoft compilation from /noscript

### LINKED ISSUE #4516: [BUG] Proxy requests can somehow have unexpected bodies
Sentry Issue: [COMPILER-EXPLORER-AEW](https://sentry.io/organizations/compiler-explorer/issues/3841685776/?referrer=github_integration)

```
TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received [Object: null prototype]
  File "/infra/.deploy/lib/handlers/compile.js", line 113, in ProxyServer.<anonymous>
    proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Fixes #4516

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
When I test msvc in staging with the example `square` function I get
```
# Compilation provided by Compiler Explorer at https://godbolt.org/
<Compilation failed>
# Compiler exited with result code 2
Standard out:
example.cpp
<source>(1): error C2447: '{': missing function header (old-style formal list?)
```

Same with CUDA:
```
# Compilation provided by Compiler Explorer at https://godbolt.org/
<Compilation failed>
# Compiler exited with result code 1
Standard error:
<source>(1): error: expected a declaration

1 error detected in the compilation of "<source>".
```

**Comment by partouf** [comment]
Nice

This was never tested before with remotes, makes sense it has bugs

**Comment by jeremy-rifkin** [comment]
Ok, msvc works now but cuda gives an error "Missing options property"

**Comment by partouf** [comment]
doesn't really look like a care-free implementation, can we not restore the original body and send that?

**Comment by jeremy-rifkin** [comment]
@partouf I did try but could not get anything to work

**Comment by dkm** [comment]
This is live :rocket:

**Pull request merged**
