### PR TITLE
Win build

### PR DESCRIPTION
**Pull request by partouf**

### CODE REVIEW

**Comment by partouf** [comment]
Sort of works, i think its now uploaded to the wrong place, also its a different buildnumber than the linux build?

**Comment by partouf** [comment]
For it to be the same gh-number, it would need to run in the regular workflow, I think. Unsure we can connect the two unless we do a different kind of lookup based on commit hash? But where/how?

**Comment by partouf** [comment]
The not landing the correct S3 folder is probably a BRANCH variable issue.

I had to reconstruct the bash string manipulation into powershell and output it somewhere, but not sure I did it right, or if in the right location.

Pwsh version: https://github.com/compiler-explorer/compiler-explorer/pull/4547/files#diff-e4d097393300d70dad5b3139d268b790a678a4bb9f0267080090b5c06bbd791cR45

Bash version: https://github.com/compiler-explorer/compiler-explorer/blob/main/etc/scripts/build-dist.sh#L44

**Comment by partouf** [comment]
Do you have any thoughts on the gh-number @mattgodbolt - it would be nice to have the same buildnumber to deploy to windows instances, but obviously adding that to the linux build workflow might slow down the entire process of updating while hardly ever needing to actually test windows.

**Comment by mattgodbolt** [comment]
> Do you have any thoughts on the gh-number @mattgodbolt - it would be nice to have the same buildnumber to deploy to windows instances, but obviously adding that to the linux build workflow might slow down the entire process of updating while hardly ever needing to actually test windows.

Yeah I see the quandary here. I would like the versions to be the same but I don't want to pessimize the regular build, at least until we have a clear plan for our own windows rollout.  If this is just for testing then I think separate version numbers are OK (if annoying)

**Comment by mattgodbolt** [comment]
It's also possible we could launch this build as a child build of the main build and get it to pass the GH run number over.

**Comment by partouf** [comment]
> It's also possible we could launch this build as a child build of the main build and get it to pass the GH run number over.

ahh right, maybe so, will investigate

**Comment by partouf** [comment]
will iterate when merged

**Pull request merged**
