### PR TITLE
Rust 1.66.0

### PR DESCRIPTION
**Pull request by ojeda**
Infra: https://github.com/compiler-explorer/infra/pull/902

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
As always, looks great. thanks! Should be out by the weekend!

**Comment by ojeda** [comment]
My pleasure! Weekend sounds great.

**Comment by mattgodbolt** [comment]
It's your lucky day - this is live now :)

**Comment by mattgodbolt** [comment]
and thank you once again!

**Pull request merged**
