### PR TITLE
[julia_wrapper] Fix compatibility with Julia v1.10

### PR DESCRIPTION
**Pull request by giordano**
Fix error reported at https://github.com/compiler-explorer/compiler-explorer/pull/5927#issuecomment-1882396045.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
I'm 100% trustin you here :) I haev no idea what's going on !

**Comment by giordano** [comment]
This code is peeking into internals of the Julia compiler, which aren't part of the public API, so subject to changes between different versions, although we've been good between v1.7-1.9, breaking changes aren't _that_ frequent.

Apparently, when the wrapper asks for the methods that have been compiled, it used to always get an iterable object (a `Core.SimpleVector` which is an internal lightweight implementation of vectors), but for some reason in Julia v1.10 when there's a single method (which is the case for the default example here on compiler explorer), one can get a single instance of the object `Core.MethodInstance`, outside of the vector mentioned above, and so running a for loop over it would fail. The trick I used here was to wrap the object in a 1-tuple, so that the for loop would work again.

**Comment by mattgodbolt** [comment]
This is now live: let me know if it worked out!

**Comment by giordano** [comment]
Yes, it's working nicely now: https://godbolt.org/z/xGrj1rqss.  Thanks!

**Comment by mattgodbolt** [comment]
Fantastic! thank you!

**Pull request merged**
