### PR TITLE
Opt remarks: replace hover-over-sidebar display with inline text

### PR DESCRIPTION
**Pull request by OfekShilon**
inlineoptrem

### CODE REVIEW

**Comment by OfekShilon** [comment]
BTW I hope to give a lot more attention to the optview pane in the near future. 
In-advance feedback is very welcome: https://github.com/orgs/compiler-explorer/projects/9/views/1

**Comment by OfekShilon** [comment]
@mattgodbolt I think you expressed interest in something like this too, a while back

**Comment by mattgodbolt** [comment]
Yes!! I absolutely did! Thank you !

**Review by RubenRBS — APPROVED** [review]
This looks great! :)

**Comment by OfekShilon** [comment]
@mattgodbolt  @RubenRBS  thanks! I noticed later that 'stack usage' uses the same sidebar display. Should I convert it too?

**Comment by RubenRBS** [comment]
If it translates easily, then I'd also like this there yes! But dont sweat it too much if not!

**Comment by partouf** [comment]
this is now live

**Comment by OfekShilon** [comment]
I should probably add a wrap-line checkbox. Opt-remarks can get long.

**Pull request merged**
