### PR TITLE
Bump to latest monaco

### PR DESCRIPTION
**Pull request by mattgodbolt**
Currently blocked as during dev we see:

```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 76:0-57
Module not found: Error: Can't resolve './contrib/stickyScroll/browser/stickyScroll.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
 @ ./static/themes.ts 29:22-46
 @ ./static/main.ts 47:34-56

ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 84:0-77
Module not found: Error: Can't resolve './contrib/viewportSemanticTokens/browser/viewportSemanticTokens.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
 @ ./static/themes.ts 29:22-46
 @ ./static/main.ts 47:34-56
```

which seem to be related to newer features in monaco. Filed https://github.com/microsoft/monaco-editor/issues/3796 to hopefully get help on what's going on.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Should fix #4355

**Comment by mattgodbolt** [comment]
`make` works just fine: that is, `npm run webpack` is happy. But the "dev" webpack process complains as above. Both seem to be newly-added features in monaco 35

**Comment by mattgodbolt** [comment]
This looks good now - the dev issues were fixed with a `make clean` (ugh)

**Comment by jeremy-rifkin** [comment]
This is live

**Pull request merged**
