### PR TITLE
A few extra Clang 13.0.0 entries

### PR DESCRIPTION
**Pull request by ojeda**
A few missing entries that were left after rebasing my branch.

### CODE REVIEW

**Review by mattgodbolt — APPROVED** [review]
Thanks!

**Comment by mattgodbolt** [comment]
You beat me to it @apmorton !

**Comment by apmorton** [comment]
https://www.youtube.com/watch?v=CJh1hmmLLzw

**Comment by mattgodbolt** [comment]
This is now live, thank you!

**Comment by ojeda** [comment]
You're welcome!

**Pull request merged**
