### PR TITLE
Add Dart execution wrapper

### PR DESCRIPTION
**Pull request by miDeb**
- Add `dartaotruntime` as the execution wrapper
- Enable execution

### CODE REVIEW

**Comment by RubenRBS** [comment]
Should it be set for the default version too?

**Comment by miDeb** [comment]
I guess so? I'll add the `objdumper` there as well.

**Comment by RubenRBS** [comment]
Thank you! :)

**Comment by partouf** [comment]
Looks Ok, but can you give an example where the command line arguments are used?

**Comment by partouf** [comment]
for execution, users can supply arguments with the execution pane, but the default example uses an environment variable (i think)

**Comment by miDeb** [comment]
Ah, I didn't think of user-supplied arguments for execution. I'll check tomorrow if I need to change something to handle them correctly... The example reads an input from an environment variable to avoid the code from being optimized away.

**Comment by miDeb** [comment]
I just checked, and execution arguments seem to be working fine.

**Pull request merged**
