### PR TITLE
Add language tooltips

### LINKED ISSUE #703: Add tooltips/explanation of each language/pseudolanguage
Some folks have been confused by (e.g.) what cppx is

### PR DESCRIPTION
**Pull request by RubenRBS**
This would close #703, but mayeb we want to keep iterating on it before marking it as completed. Right now it shows the built-in browser tooltip for titles, but maybe we want to use Bootstrap's popups at least for the button?

### CODE REVIEW

**Comment by partouf** [comment]
Code lgtm, but would need to see it in action

**Comment by RubenRBS** [comment]
imagen

imagen

**Comment by partouf** [comment]
Not the prettiest, but perhaps good enough.

**Comment by RubenRBS** [comment]
We can make the button use a popup instead, might feel better. Will try

**Comment by RubenRBS** [comment]
imagen

**Pull request merged**
