### PR TITLE
Fix tomselect arrow padding

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
Quick fix for a bug that happens in staging and never locally
image
image

### CODE REVIEW

**Comment by partouf** [comment]
does happen for me locally when unchecking the padding in my chrome locally, not sure why it didn't show up for you

**Comment by jeremy-rifkin** [comment]
Yeah, if you uncheck the padding you can reproduce. But loading local as-is without messing in dev tools was fine whereas loading it on staging was not.

**Comment by partouf** [comment]
superweird

**Comment by dkm** [comment]
this is live :rocket:

**Pull request merged**
