### PR TITLE
Add SIMDe library

### PR DESCRIPTION
**Pull request by JacquesLucke**
This adds the [SIMDe](https://github.com/simd-everywhere/simde) library for C and C++. It is a header-only library. Note that I am not affiliated with the simde project. I'm just adding the library, because it would be useful for me and hopefully others too.

Please let me know if there is anything else I have to do.

### CODE REVIEW

**Comment by partouf** [comment]
Thanks! I will handle the rest

**Comment by JacquesLucke** [comment]
Thanks! :)

**Comment by partouf** [comment]
This is now live

**Comment by JacquesLucke** [comment]
Nice. That was faster than I expected.

**Pull request merged**
